<?php
namespace App\Services;

use App\Core\Database as DB;
use App\Core\Helpers as H;

final class CustomDesignService
{
    public const STATES=['new','in_progress','proof_review','revision_requested','completed','cancelled','refunded'];
    private const HISTORICALLY_PAID=['paid','partially_refunded','refunded'];
    private const WORKFLOW_PAYMENTS=['paid','partially_refunded'];
    private const MAX_FILES=10;
    private const MAX_SIZE=26214400;
    private const IMAGE_MIMES=['image/jpeg'=>'jpg','image/png'=>'png','image/webp'=>'webp'];

    public static function transitionFor(string $state,string $action,string $side):?string
    {
        return match("$state:$action:$side"){'new:start:seller'=>'in_progress','revision_requested:start_revision:seller'=>'in_progress','in_progress:proof:seller'=>'proof_review','proof_review:revision:buyer'=>'revision_requested','proof_review:approve:buyer'=>'in_progress','in_progress:final:seller'=>'completed',default=>null};
    }

    public static function buyerFinalEligible(string $customStatus,string $paymentStatus):bool
    { return $customStatus==='completed'&&in_array($paymentStatus,['paid','partially_refunded'],true); }
    public static function retryEligible(?string $customStatus):bool{return $customStatus===null||$customStatus==='new';}
    public static function workflowPaymentEligible(string $paymentStatus):bool{return in_array($paymentStatus,self::WORKFLOW_PAYMENTS,true);}

    public static function containCommunicationFailure(callable $operation,?callable $reporter=null,?callable $fallback=null):bool
    {
        try{$operation();return true;}catch(\Throwable $error){try{($reporter??static fn(\Throwable $e)=>NotificationService::reportFailure('custom_order_communication',$e))($error);}catch(\Throwable){try{($fallback??static fn()=>error_log('Asset Moth custom-order communication and failure reporting failed.'))();}catch(\Throwable){}}return false;}
    }

    public function seller(int $userId):array
    { return DB::row('select * from designers where user_id=? and status="approved"',[$userId])??H::abort(403); }

    public function saveService(int $userId,?int $id,array $input,array $files):array
    {
        $seller=$this->seller($userId);$errors=[];$title=trim($input['title']??'');$description=trim($input['description']??'');$price=round((float)($input['price']??0),2);$days=(int)($input['turnaround_days']??0);$revisions=(int)($input['included_revisions']??0);
        if($title===''||mb_strlen($title)>190)$errors[]='Title is required and must be 190 characters or fewer.';if($description==='')$errors[]='Description is required.';if($price<.5)$errors[]='Price must be at least $0.50.';if($days<1||$days>365)$errors[]='Turnaround must be between 1 and 365 days.';if($revisions<0||$revisions>100)$errors[]='Included revisions must be between 0 and 100.';
        $questions=[];foreach((array)($input['questions']??[]) as $key=>$question){$text=trim((string)$question);if($text!=='')$questions[]=['text'=>mb_substr($text,0,500),'required'=>!empty($input['question_required'][$key])];}
        try{$uploads=$this->validateUploads($files['examples']??[],'image');}catch(\InvalidArgumentException $e){$errors[]=$e->getMessage();$uploads=[];}if($errors)return$errors;
        $stored=[];$remove=[];DB::begin();try{
            if($id){DB::row('select id from custom_design_services where id=? and designer_id=? for update',[$id,$seller['id']])??H::abort(404);DB::exec('update custom_design_services set title=?,description=?,price=?,turnaround_days=?,included_revisions=?,buyer_instructions=?,is_active=? where id=?',[$title,$description,$price,$days,$revisions,trim($input['buyer_instructions']??''),!empty($input['is_active']),$id]);}
            else{$slug=H::slug($title).'-'.substr(bin2hex(random_bytes(4)),0,8);DB::exec('insert into custom_design_services(designer_id,slug,title,description,price,turnaround_days,included_revisions,buyer_instructions,is_active) values(?,?,?,?,?,?,?,?,?)',[$seller['id'],$slug,$title,$description,$price,$days,$revisions,trim($input['buyer_instructions']??''),!empty($input['is_active'])]);$id=(int)DB::id();}
            DB::exec('delete from custom_service_questions where custom_service_id=?',[$id]);foreach($questions as $n=>$q)DB::exec('insert into custom_service_questions(custom_service_id,question_text,is_required,sort_order) values(?,?,?,?)',[$id,$q['text'],$q['required'],$n]);
            $removeIds=array_values(array_filter(array_map('intval',(array)($input['remove_images']??[]))));if($removeIds){$marks=implode(',',array_fill(0,count($removeIds),'?'));$remove=DB::rows("select image_path from custom_service_images where custom_service_id=? and id in ($marks)",array_merge([$id],$removeIds));DB::exec("delete from custom_service_images where custom_service_id=? and id in ($marks)",array_merge([$id],$removeIds));}
            foreach($uploads as $upload){$path=$this->store($upload,'examples',false);$stored[]=public_path(ltrim($path,'/'));DB::exec('insert into custom_service_images(custom_service_id,image_path,sort_order) values(?,?,?)',[$id,$path,0]);}DB::commit();foreach($remove as $old)$this->unlinkPublic($old['image_path']);return[];
        }catch(\Throwable $e){if(DB::pdo()->inTransaction())DB::rollBack();foreach($stored as $path)@unlink($path);throw$e;}
    }

    public function submitRequest(array $service,int $buyerId,array $input,array $files):int
    {
        if(!$buyerId||$buyerId===(int)$service['seller_user_id'])H::abort(403);$errors=[];foreach(['design_request'=>'Detailed design request','required_text'=>'Required wording/names/text','design_direction'=>'Theme/style/design direction'] as $key=>$label)if(trim($input[$key]??'')==='')$errors[]="$label is required.";
        $answers=[];foreach(DB::rows('select * from custom_service_questions where custom_service_id=? order by sort_order,id',[$service['id']]) as $q){$answer=trim((string)($input['answers'][$q['id']]??''));if($q['is_required']&&$answer==='')$errors[]='Please answer: '.$q['question_text'];$answers[]=['question_id'=>(int)$q['id'],'question'=>$q['question_text'],'required'=>(bool)$q['is_required'],'answer'=>$answer];}
        $uploads=$this->validateUploads($files['references']??[],'image_or_pdf');if($errors)throw new \InvalidArgumentException(implode(' ',$errors));$brief=[];foreach(['design_request','required_text','design_direction','color_preferences','dimensions','file_format','intended_use','additional_notes'] as $key)$brief[$key]=trim((string)($input[$key]??''));$brief['answers']=$answers;
        $billing=StripeService::normalizeBillingAddress(['line1'=>trim($input['billing_line1']??''),'line2'=>trim($input['billing_line2']??''),'city'=>trim($input['billing_city']??''),'state'=>trim($input['billing_state']??''),'postal_code'=>trim($input['billing_postal_code']??''),'country'=>strtoupper(trim($input['billing_country']??'US'))]);$checkout=new CheckoutOrderService;
        $price=CreditService::formatCents(CreditService::parseCents((string)$service['price']));$identity='custom-tax:'.$buyerId.':'.hash('sha256',json_encode([(int)$service['id'],$price,$billing],JSON_THROW_ON_ERROR));$tax=$checkout->calculateTax([['id'=>'custom-'.$service['id'],'total_price'=>$price]],$billing,$identity);$taxAmount=CreditService::formatCents($tax['tax_cents']);$grossCents=CreditService::parseCents($price)+$tax['tax_cents'];if((int)$tax['total_cents']!==$grossCents)throw new \RuntimeException('Stripe Tax total did not match the authoritative custom-service snapshot.');$creditService=new CreditService;$available=$creditService->balances($buyerId)['available'];$breakdown=CreditService::checkoutBreakdown($price,'0.00',$taxAmount,$available,($input['use_credits']??'')==='1');$creditCents=$breakdown['credit_cents'];$credits=CreditService::formatCents($creditCents);$total=CreditService::formatCents($breakdown['final_cents']);$rate=StripeService::commissionRate();$stored=[];
        DB::begin();try{
            $fresh=DB::row('select s.*,d.display_name,d.user_id seller_user_id from custom_design_services s join designers d on d.id=s.designer_id where s.id=? and s.is_active=1 and d.status="approved" for update',[$service['id']]);if(!$fresh||CreditService::formatCents(CreditService::parseCents((string)$fresh['price']))!==$price)throw new \DomainException('The service price changed. Review the service and try again.');
            $order=$checkout->createOrder(['user_id'=>$buyerId,'subtotal'=>$price,'tax_amount'=>$taxAmount,'tax_snapshot'=>$tax['snapshot'],'tax_calculation_id'=>$tax['id'],'billing_snapshot'=>json_encode($billing,JSON_THROW_ON_ERROR),'credits'=>$credits,'total'=>$total,'currency'=>StripeService::currency(),'amount_cents'=>CreditService::parseCents($total),'stripe_paid_amount'=>$total,'commission_total'=>round((float)$price*$rate,2)]);if($creditCents>0){$credits=$creditService->reserve($buyerId,$credits,$order,'order:'.$order.':credit:reserve');$creditCents=CreditService::parseCents($credits);$total=CreditService::formatCents($grossCents-$creditCents);DB::exec('update orders set credits_applied=?,credit_reserved=?,credit_payment_status=?,total=?,stripe_amount_total=?,stripe_paid_amount=? where id=?',[$credits,$credits,$creditCents>0?'reserved':'none',$total,$grossCents-$creditCents,$total,$order]);}
            $item=$checkout->addItem(['order_id'=>$order,'custom_service_id'=>$fresh['id'],'title'=>$fresh['title'],'slug'=>$fresh['slug'],'designer_id'=>$fresh['designer_id'],'seller_name'=>$fresh['display_name'],'license_type'=>'custom','license_name'=>'Custom design agreement','license_description'=>$brief['intended_use'],'license_snapshot'=>json_encode(['intended_use'=>$brief['intended_use']],JSON_THROW_ON_ERROR),'fulfillment_type'=>'custom_design','unit_price'=>$price,'total_price'=>$price,'commission_rate'=>$rate]);
            DB::exec('insert into custom_orders(order_id,order_item_id,custom_service_id,buyer_user_id,designer_id,status,service_snapshot,brief_snapshot,agreed_price,turnaround_days,included_revisions) values(?,?,?,?,?,"new",?,?,?,?,?)',[$order,$item,$fresh['id'],$buyerId,$fresh['designer_id'],json_encode(['title'=>$fresh['title'],'description'=>$fresh['description'],'buyer_instructions'=>$fresh['buyer_instructions']],JSON_THROW_ON_ERROR),json_encode($brief,JSON_THROW_ON_ERROR),$price,$fresh['turnaround_days'],$fresh['included_revisions']]);$custom=(int)DB::id();
            foreach($uploads as $upload){$path=$this->store($upload,'references',true);$stored[]=app_path('storage/protected_uploads/'.$path);DB::exec('insert into custom_order_files(custom_order_id,uploader_user_id,file_kind,original_name,storage_path,mime_type,file_size) values(?, ?,"reference",?,?,?,?)',[$custom,$buyerId,$upload['original_name'],$path,$upload['mime'],$upload['size']]);}$checkout->addSellerEarning($order,null,(int)$fresh['designer_id'],$buyerId,$price,$rate);$created=DB::row('select * from orders where id=?',[$order]);$items=DB::rows('select * from order_items where order_id=?',[$order]);if(CreditService::parseCents($total)===0){$finalizer=new OrderFinalizationService;$finalizer->finalize($order,'internal-credit-order:'.$order,true);DB::commit();$finalizer->communicate($order);H::redirect('/dashboard/order/'.$order);}$session=$checkout->checkout($created,$items);DB::exec('update orders set stripe_checkout_session_id=?,stripe_payment_status="pending" where id=?',[$session['id']??null,$order]);DB::commit();header('Location: '.$session['url'],true,303);exit;
        }catch(\Throwable $e){if(DB::pdo()->inTransaction())DB::rollBack();foreach($stored as $path)@unlink($path);throw$e;}
    }

    public function transition(array $order,int $userId,string $action,array $files=[]):void
    {
        $stored=[];$historyId=0;$next='';$kind=null;DB::begin();try{$current=DB::row('select co.*,o.payment_status,d.user_id seller_user_id from custom_orders co join orders o on o.id=co.order_id join designers d on d.id=co.designer_id where co.id=? for update',[$order['id']])??H::abort(404);$seller=$userId===(int)$current['seller_user_id'];$buyer=$userId===(int)$current['buyer_user_id'];if(!$seller&&!$buyer)H::abort(404);if(!self::workflowPaymentEligible($current['payment_status']))throw new \DomainException('Payment must remain eligible for active custom work.');
            $side=$seller?'seller':'buyer';$next=self::transitionFor($current['status'],$action,$side);if($next===null)throw new \DomainException('The custom order changed; refresh before trying that action.');$from=$current['status'];$kind=$action==='proof'?'proof':($action==='final'?'final':null);$uploads=$kind?$this->validateUploads($files[$kind]??[],$kind==='proof'?'image_or_pdf':'delivery'):[];if($kind&&!$uploads)throw new \InvalidArgumentException('A protected file is required.');$revision=$action==='revision';DB::exec('update custom_orders set status=?,revisions_used=revisions_used+?,completed_at=case when ?="completed" then now() else completed_at end where id=? and status=?',[$next,$revision?1:0,$next,$current['id'],$from]);if(DB::pdo()->query('select row_count()')->fetchColumn()!=1)throw new \DomainException('The custom order changed; refresh and try again.');
            DB::exec('insert into custom_order_status_history(custom_order_id,from_status,to_status,actor_user_id,transition_source,note) values(?,?,?,?,"user",?)',[$current['id'],$from,$next,$userId,mb_substr(trim($_POST['note']??''),0,1000)]);$historyId=(int)DB::id();foreach($uploads as $upload){$path=$this->store($upload,$kind.'s',true);$stored[]=app_path('storage/protected_uploads/'.$path);DB::exec('insert into custom_order_files(custom_order_id,uploader_user_id,file_kind,original_name,storage_path,mime_type,file_size,revision_number) values(?,?,?,?,?,?,?,?)',[$current['id'],$userId,$kind,$upload['original_name'],$path,$upload['mime'],$upload['size'],(int)$current['revisions_used']]);}DB::commit();
        }catch(\Throwable $e){if(DB::pdo()->inTransaction())DB::rollBack();foreach($stored as $path)@unlink($path);throw$e;}
        $recipient=$userId===(int)$current['seller_user_id']?(int)$current['buyer_user_id']:(int)$current['seller_user_id'];$audience=$recipient===(int)$current['buyer_user_id']?'buyer':'designer';$title=['proof'=>'Proof available','revision'=>'Revision requested','approve'=>'Proof approved','final'=>'Final file available'][$action]??'Custom-order status changed';self::containCommunicationFailure(fn()=>NotificationService::create($recipient,$action==='final'?'custom_final_available':'custom_order_status',$audience,$title,'Custom order #'.$current['id'].' is now '.str_replace('_',' ',$next).'.','custom-order-history:'.$historyId.':recipient:'.$recipient,$audience==='buyer'?'/buyer/custom-orders/'.$current['id']:'/seller/custom-orders/'.$current['id']),static fn(\Throwable $e)=>NotificationService::reportFailure('custom_order_notification_'.$historyId,$e));if($action==='final')self::containCommunicationFailure(fn()=>EmailQueueService::customFinalAvailable((int)$current['id'],$historyId),static fn(\Throwable $e)=>NotificationService::reportFailure('custom_order_final_email_'.$historyId,$e));
    }

    public function systemTransitionByOrder(int $orderId,string $to,string $source):bool
    {
        if(!in_array($to,['cancelled','refunded'],true)||!in_array($source,['stripe_cancel','stripe_expired','stripe_refund'],true))throw new \InvalidArgumentException('Invalid system transition.');$owns=!DB::pdo()->inTransaction();if($owns)DB::begin();try{$o=DB::row('select * from custom_orders where order_id=? for update',[$orderId]);if(!$o){if($owns)DB::commit();return false;}$from=$o['status'];if(in_array($from,['cancelled','refunded'],true)&&$from!==$to||$from==='completed'&&$to!=='refunded'){if($owns)DB::commit();return false;}$changed=$from!==$to;if($changed)DB::exec('update custom_orders set status=? where id=? and status=?',[$to,$o['id'],$from]);$key=$source.':'.$to;DB::exec('insert ignore into custom_order_status_history(custom_order_id,from_status,to_status,actor_user_id,transition_source,system_event_key,note) values(?,?,?,null,?,?,?)',[$o['id'],$from,$to,$source,$key,'Payment lifecycle transition.']);$historyAdded=(int)DB::pdo()->query('select row_count()')->fetchColumn()===1;if($owns)DB::commit();return $changed||$historyAdded;}catch(\Throwable $e){if($owns&&DB::pdo()->inTransaction())DB::rollBack();throw$e;}
    }

    public function order(int $id,int $userId,?string $side=null):array
    {$row=DB::row('select co.*,o.payment_status,o.total,d.user_id seller_user_id,u.name buyer_name,d.display_name from custom_orders co join orders o on o.id=co.order_id join designers d on d.id=co.designer_id join users u on u.id=co.buyer_user_id where co.id=?',[$id])??H::abort(404);if($side==='seller'&&($userId!==(int)$row['seller_user_id']||!in_array($row['payment_status'],self::HISTORICALLY_PAID,true))||$side==='buyer'&&$userId!==(int)$row['buyer_user_id'])H::abort(404);return$row;}
    public function file(int $id,int $userId):array
    {$f=DB::row('select f.*,co.buyer_user_id,co.status,d.user_id seller_user_id,o.payment_status from custom_order_files f join custom_orders co on co.id=f.custom_order_id join orders o on o.id=co.order_id join designers d on d.id=co.designer_id where f.id=?',[$id])??H::abort(404);$buyer=$userId===(int)$f['buyer_user_id'];$seller=$userId===(int)$f['seller_user_id']&&in_array($f['payment_status'],self::HISTORICALLY_PAID,true);if(!$seller&&!$buyer||$buyer&&$f['file_kind']==='final'&&!self::buyerFinalEligible($f['status'],$f['payment_status']))H::abort(404);return$f;}

    private function validateUploads(array $files,string $mode):array
    {
        if(!$files||empty($files['name']))return[];foreach(['name','error','tmp_name','size'] as $key)if(!is_array($files[$key]??null)||array_keys($files[$key])!==array_keys($files['name']))throw new \InvalidArgumentException('Malformed upload.');if(count($files['name'])>self::MAX_FILES)throw new \InvalidArgumentException('Upload no more than '.self::MAX_FILES.' files at once.');$out=[];$finfo=new \finfo(FILEINFO_MIME_TYPE);
        foreach(array_keys($files['name']) as $i){$name=$files['name'][$i];$error=$files['error'][$i];if($error===UPLOAD_ERR_NO_FILE)continue;$tmp=$files['tmp_name'][$i];$size=(int)$files['size'][$i];if($error!==UPLOAD_ERR_OK||!is_string($tmp)||!is_uploaded_file($tmp)||@filesize($tmp)!==$size||$size<1||$size>self::MAX_SIZE)throw new \InvalidArgumentException('Uploads must be genuine files no larger than 25MB.');$ext=strtolower(pathinfo((string)$name,PATHINFO_EXTENSION));$mime=$finfo->file($tmp);if($mode==='delivery'){if($ext===''||!preg_match('/^[a-z0-9]{1,12}$/',$ext))throw new \InvalidArgumentException('Final delivery requires a safe filename extension.');}else{$allowed=self::IMAGE_MIMES;if($mode==='image_or_pdf')$allowed['application/pdf']='pdf';if(!isset($allowed[$mime])||$ext!==$allowed[$mime]&&!(($ext==='jpeg')&&$mime==='image/jpeg'))throw new \InvalidArgumentException('Upload a genuine JPG, PNG, WEBP'.($mode==='image_or_pdf'?' or PDF':'').' file.');if($mime!=='application/pdf'){$bytes=file_get_contents($tmp);$image=@getimagesizefromstring($bytes);if(!$image||!hash_equals($mime,(string)$image['mime'])||!SellerReceiptService::sourceDimensionsAllowed((int)$image[0],(int)$image[1])||!SellerReceiptService::hasExactImageContainer($bytes,$mime))throw new \InvalidArgumentException('Image validation failed.');}}
            $out[]=['tmp'=>$tmp,'original_name'=>mb_substr(basename((string)$name),0,190),'size'=>$size,'mime'=>$mime,'ext'=>$ext];}return$out;
    }
    private function store(array $file,string $folder,bool $protected):string{$relative='custom_designs/'.$folder.'/'.bin2hex(random_bytes(24)).'.'.$file['ext'];$base=$protected?app_path('storage/protected_uploads'):public_path('uploads');$path=$base.'/'.$relative;if(!is_dir(dirname($path))&&!mkdir(dirname($path),$protected?0750:0755,true)&&!is_dir(dirname($path)))throw new \RuntimeException('Upload storage is unavailable.');if(!move_uploaded_file($file['tmp'],$path))throw new \RuntimeException('Could not securely store upload.');return($protected?'':'/uploads/').$relative;}
    private function unlinkPublic(string $path):void{$base=realpath(public_path('uploads/custom_designs'));$real=realpath(public_path(ltrim($path,'/')));if($base&&$real&&str_starts_with($real,$base.DIRECTORY_SEPARATOR))@unlink($real);}
}
