<?php
namespace App\Services;
use App\Core\Database as DB;
use App\Core\Helpers as H;

final class EmailCampaignService
{
    public const AUDIENCES=['waitlist_all','waitlist_buyer','waitlist_seller','waitlist_tester','users_opted_in'];
    public static function audienceLabel(string $audience):string{return ['waitlist_all'=>'All consented waitlist subscribers','waitlist_buyer'=>'Waitlist buyers','waitlist_seller'=>'Waitlist sellers','waitlist_tester'=>'Waitlist testers','users_opted_in'=>'Opted-in registered users'][$audience]??'Unknown audience';}
    public static function safeCta(?string $url): ?string { $original=(string)$url;if(str_contains($original,'\\')||preg_match('/[\x00-\x1F\x7F]/',$original))return null;$url=trim($original);if($url==='')return null;if($url[0]==='/')return NotificationService::safeActionUrl($url);$p=parse_url($url);$app=parse_url(H::baseUrl());if($p===false||$app===false||($p['scheme']??'')!=='https'||($app['scheme']??'')!=='https'||isset($p['user'])||isset($p['pass']))return null;$host=strtolower($p['host']??'');$appHost=strtolower($app['host']??'');$port=(int)($p['port']??443);$appPort=(int)($app['port']??443);return $host!==''&&hash_equals($appHost,$host)&&$port===$appPort?mb_substr($url,0,500):null; }
    public static function validate(array $in): array { $e=[]; $subject=trim($in['subject']??'');$body=trim($in['body']??'');$aud=$in['audience']??'';$label=trim($in['cta_label']??'');$originalUrl=(string)($in['cta_url']??'');$urlIsEmpty=trim($originalUrl)===''; if($subject===''||mb_strlen($subject)>190||preg_match('/[\r\n]/',$subject))$e[]='Enter a valid one-line subject (190 characters maximum).'; if($body===''||mb_strlen($body)>10000)$e[]='Enter campaign copy (10,000 characters maximum).'; if(!in_array($aud,self::AUDIENCES,true))$e[]='Select a valid audience.'; if(mb_strlen($label)>80)$e[]='CTA label is too long.'; if(($label==='' xor $urlIsEmpty)||(!$urlIsEmpty&&self::safeCta($originalUrl)===null))$e[]='CTA label and a safe Asset Moth URL are required together.'; return $e; }
    public static function create(array $in,int $adminId): int { $errors=self::validate($in);if($errors)throw new \InvalidArgumentException(implode(' ',$errors)); DB::exec('insert into email_campaigns (campaign_type,audience,subject,body,cta_label,cta_url,created_by) values ("promotional",?,?,?,?,?,?)',[$in['audience'],trim($in['subject']),trim($in['body']),trim($in['cta_label']??'')?:null,self::safeCta($in['cta_url']??null),$adminId]);return (int)DB::id(); }
    public static function queue(int $id): int { $c=DB::row('select * from email_campaigns where id=? and status="draft"',[$id]);if(!$c)return 0; DB::begin(); try { $rows=self::audience($c['audience']); if(!$rows){DB::exec('update email_campaigns set status="completed",completed_at=now() where id=?',[$id]);DB::commit();return 0;} $queuedCount=0; foreach($rows as $r) DB::exec('insert ignore into email_campaign_recipients (campaign_id,waitlist_entry_id,user_id,email,name,status) values (?,?,?,?,?,"pending")',[$id,$r['waitlist_entry_id']??null,$r['user_id']??null,$r['email'],$r['name']??null]); foreach(DB::rows('select * from email_campaign_recipients where campaign_id=? and status="pending"',[$id]) as $r){ $data=['name'=>$r['name'],'body'=>$c['body'],'cta_label'=>$c['cta_label'],'cta_url'=>$c['cta_url'],'user_id'=>$r['user_id']]; $queued=EmailQueueService::queue('marketing',$r['email'],$c['subject'],'campaign',$data,"campaign:$id:recipient:".$r['id'],['campaign_id'=>$id,'campaign_recipient_id'=>$r['id'],'waitlist_entry_id'=>$r['waitlist_entry_id']]);if($queued)$queuedCount++; DB::exec('update email_campaign_recipients set status=?,last_error=? where id=?',[$queued?'queued':'suppressed',$queued?null:'Consent or unsubscribe authorization unavailable',$r['id']]); } DB::exec('update email_campaigns set status="queued",queued_at=now() where id=?',[$id]);DB::commit();if($queuedCount===0)self::recalculate($id); }catch(\Throwable $e){DB::rollBack();throw $e;} return count($rows); }
    private static function audience(string $aud): array { if($aud==='users_opted_in')return DB::rows('select u.id user_id,null waitlist_entry_id,u.email,u.name from users u join email_preferences ep on ep.user_id=u.id where u.status="active" and ep.marketing_opt_in=1 and ep.marketing_opted_out_at is null and length(ep.unsubscribe_nonce)=64'); $where='status in ("subscribed","invited") and unsubscribed_at is null and length(unsubscribe_nonce)=64';$p=[];if($aud!=='waitlist_all'){$interest=str_replace('waitlist_','',$aud);$where.=' and (interest_type=? or interest_type="both")';$p[]=$interest;}return DB::rows('select id waitlist_entry_id,null user_id,email,name from waitlist_entries where '.$where,$p); }
    public static function cancel(int $id): void { DB::exec('update email_campaigns set status="cancelled",cancelled_at=now() where id=? and status in ("draft","queued","sending")',[$id]); DB::exec('update email_messages set status="cancelled" where campaign_id=? and status="pending"',[$id]); DB::exec('update email_campaign_recipients set status="cancelled" where campaign_id=? and status in ("pending","queued")',[$id]); }
    public static function statusForCounts(array $n): string { $total=(int)($n['total']??0);$sent=(int)($n['sent']??0);$failed=(int)($n['failed']??0);$active=(int)($n['active']??0);if($active>0)return 'sending';if($failed>0&&$sent>0)return 'partially_failed';if($failed>0)return 'failed';if($sent>0)return 'sent';return 'completed'; }
    public static function recalculate(int $id): void { $c=DB::row('select status from email_campaigns where id=?',[$id]);if(!$c||$c['status']==='cancelled')return;$n=DB::row('select count(*) total,sum(status="sent") sent,sum(status="failed") failed,sum(status in ("pending","queued")) active from email_campaign_recipients where campaign_id=?',[$id]);$status=self::statusForCounts($n?:[]);DB::exec('update email_campaigns set status=?,sent_at=if(? in ("sent","partially_failed"),coalesce(sent_at,now()),sent_at),completed_at=if(? in ("sent","completed","partially_failed","failed"),coalesce(completed_at,now()),completed_at) where id=?',[$status,$status,$status,$id]); }
}
