<?php
namespace App\Services;
use App\Core\Database as DB;

final class MarketplaceRefundService
{
    public static function sellerEntitlements(array $items,array $refundedByItem,int $basisPoints=900,int $fixedCents=30):array{$remaining=[];foreach($items as $item){$id=(int)$item['id'];$remaining[]=['id'=>$id,'seller_id'=>(int)$item['seller_id'],'gross_cents'=>max(0,(int)$item['gross_cents']-(int)($refundedByItem[$id]??0))];}return(new MarketplaceFeeService($basisPoints,$fixedCents))->calculate($remaining);}
    public static function outstandingDelta(int $cumulativeCents,int $previousObservedCents):int{return max(0,$cumulativeCents-$previousObservedCents);}
    public static function allocationIsExact(int $deltaCents,array $itemCents,int $taxCents):bool{return $deltaCents>0&&$taxCents>=0&&array_sum(array_map('intval',$itemCents))+$taxCents===$deltaCents;}
    public static function recoveryGrowth(int $cumulativeRequiredCents,int $previouslyAccountedCents):int{return max(0,$cumulativeRequiredCents-$previouslyAccountedCents);}
    public static function recoveryPlan(int $payoutCents,int $openRecoveryCents):array{$p=max(0,$payoutCents);$r=max(0,$openRecoveryCents);$a=min($p,$r);return['original_payout_cents'=>$p,'applied_cents'=>$a,'transfer_cents'=>$p-$a,'remaining_recovery_cents'=>$r-$a];}
    public static function recoveryCanClose(int $reservedCents):bool{return $reservedCents===0;}

    public function observe(int $orderId,string $eventId,int $cumulativeCents):array
    {
        $owns=!DB::pdo()->inTransaction();if($owns)DB::begin();try{
            $existing=DB::row('select * from marketplace_refund_observations where stripe_event_id=?',[$eventId]);if($existing){if($owns)DB::commit();return $existing+['replay'=>true];}
            DB::row('select id from orders where id=? for update',[$orderId]);
            $existing=DB::row('select * from marketplace_refund_observations where stripe_event_id=?',[$eventId]);if($existing){if($owns)DB::commit();return $existing+['replay'=>true];}
            $previous=(int)(DB::row('select coalesce(max(cumulative_refund_cents),0) cents from marketplace_refund_observations where order_id=?',[$orderId])['cents']??0);
            $delta=self::outstandingDelta($cumulativeCents,$previous);$status=$delta>0?'needs_allocation':'reconciled';
            DB::exec('insert into marketplace_refund_observations(order_id,stripe_event_id,cumulative_refund_cents,refund_delta_cents,allocation_status) values (?,?,?,?,?)',[$orderId,$eventId,$cumulativeCents,$delta,$status]);$id=(int)DB::id();$row=DB::row('select * from marketplace_refund_observations where id=?',[$id]);if($owns)DB::commit();return$row+['replay'=>false];
        }catch(\Throwable $e){if($owns&&DB::pdo()->inTransaction())DB::rollBack();throw$e;}
    }

    public function completeAllocation(int $observationId,array $itemCents,int $taxCents,string $source='admin'):array
    {
        $owns=!DB::pdo()->inTransaction();if($owns)DB::begin();try{
            $lookup=DB::row('select order_id from marketplace_refund_observations where id=?',[$observationId]);if(!$lookup)throw new \DomainException('Refund observation was not found.');DB::row('select id from orders where id=? for update',[$lookup['order_id']]);DB::rows('select id from seller_payouts where order_id=? order by id for update',[$lookup['order_id']]);$ob=DB::row('select * from marketplace_refund_observations where id=? for update',[$observationId]);if($ob['allocation_status']==='reconciled'){if($owns)DB::commit();return$ob+['replay'=>true];}if($ob['allocation_status']==='allocated')throw new \DomainException('Refund allocation already exists; resume reconciliation instead of allocating again.');
            $normalized=[];foreach($itemCents as $id=>$cents){$c=(int)$cents;if($c<0)throw new \DomainException('Refund allocations cannot be negative.');if($c>0)$normalized[(int)$id]=$c;}
            if(!self::allocationIsExact((int)$ob['refund_delta_cents'],$normalized,$taxCents))throw new \DomainException('Merchandise and tax allocations must exactly equal the outstanding refund.');
            $items=[];foreach(DB::rows('select id,total_price from order_items where order_id=? for update',[$ob['order_id']]) as $item)$items[(int)$item['id']]=$item;
            foreach($normalized as $id=>$cents){if(!isset($items[$id]))throw new \DomainException('Refund item does not belong to this order.');$used=(int)(DB::row('select coalesce(sum(merchandise_refund_cents),0) cents from marketplace_refund_allocations where order_item_id=?',[$id])['cents']??0);if($cents>StripeService::cents($items[$id]['total_price'])-$used)throw new \DomainException('Refund exceeds remaining item merchandise.');}
            $order=DB::row('select tax_amount from orders where id=? for update',[$ob['order_id']]);DB::rows('select id from marketplace_refund_observations where order_id=? order by id for update',[$ob['order_id']]);$usedTax=(int)(DB::row('select coalesce(sum(tax_refund_cents),0) cents from marketplace_refund_observations where order_id=? and allocation_status in ("allocated","reconciled")',[$ob['order_id']])['cents']??0);if($taxCents>StripeService::cents($order['tax_amount']??0)-$usedTax)throw new \DomainException('Refund exceeds remaining refundable tax.');
            foreach($normalized as $id=>$cents)DB::exec('insert into marketplace_refund_allocations(refund_observation_id,order_id,order_item_id,merchandise_refund_cents,event_key,allocation_source) values (?,?,?,?,?,?)',[$observationId,$ob['order_id'],$id,$cents,'refund-observation:'.$observationId.':item:'.$id,$source]);
            DB::exec('update marketplace_refund_observations set merchandise_refund_cents=?,tax_refund_cents=?,allocated_cents=?,allocation_status="allocated",allocated_at=now() where id=?',[array_sum($normalized),$taxCents,array_sum($normalized)+$taxCents,$observationId]);
            if($owns)DB::commit();return DB::row('select * from marketplace_refund_observations where id=?',[$observationId])+['replay'=>false];
        }catch(\Throwable $e){if($owns&&DB::pdo()->inTransaction())DB::rollBack();throw$e;}
    }
    public function markReconciled(int $observationId):void{DB::exec('update marketplace_refund_observations set allocation_status="reconciled",reconciled_at=now() where id=? and allocation_status="allocated"',[$observationId]);DB::exec('update seller_financial_adjustments set status="resolved",balance_cents=0,resolved_at=coalesce(resolved_at,now()),note=concat_ws(" | ",note,"Stored refund allocation reconciled.") where adjustment_type="refund_allocation_review" and event_key like ? and status="open"',['refund-allocation-review:observation:'.$observationId.':seller:%']);}
    public function clearReviewWhenFullyReconciled(int $orderId):void
    {
        $owns=!DB::pdo()->inTransaction();if($owns)DB::begin();try{DB::row('select id from orders where id=? for update',[$orderId]);$observations=DB::rows('select allocation_status from marketplace_refund_observations where order_id=? order by id for update',[$orderId]);$unresolved=count(array_filter($observations,static fn(array $row):bool=>$row['allocation_status']!=='reconciled'));if($unresolved===0)DB::exec('update orders set manual_review_required=0,manual_review_reason=null where id=? and manual_review_reason like "Stripe refund observation%"',[$orderId]);if($owns)DB::commit();}catch(\Throwable $e){if($owns&&DB::pdo()->inTransaction())DB::rollBack();throw$e;}
    }
    public function ensureAllocationReview(array $observation):void
    {
        if(($observation['allocation_status']??'')!=='needs_allocation')return;$orderId=(int)$observation['order_id'];$id=(int)$observation['id'];DB::exec('update orders set manual_review_required=1,manual_review_reason="Stripe refund observation requires exact merchandise/tax allocation before financial reconciliation." where id=? and (manual_review_required=0 or manual_review_reason like "Stripe refund observation%")',[$orderId]);foreach(DB::rows('select distinct designer_id from order_items where order_id=?',[$orderId]) as $seller)DB::exec('insert ignore into seller_financial_adjustments(order_id,designer_id,adjustment_type,event_key,note) values (?,? ,"refund_allocation_review",?,?)',[$orderId,$seller['designer_id'],'refund-allocation-review:observation:'.$id.':seller:'.$seller['designer_id'],'Refund observation #'.$id.' requires exact item and tax allocation; seller snapshots are unchanged.']);
    }
    public function allocations(int $orderId):array{return DB::rows('select oi.id,oi.designer_id,oi.total_price,coalesce(sum(a.merchandise_refund_cents),0) refunded_cents from order_items oi left join marketplace_refund_allocations a on a.order_item_id=oi.id where oi.order_id=? group by oi.id,oi.designer_id,oi.total_price order by oi.id',[$orderId]);}

    public function recordRecovery(int $orderId,int $designerId,int $cumulativeRequiredCents):void
    {
        $owns=!DB::pdo()->inTransaction();if($owns)DB::begin();try{DB::row('select id from seller_payouts where order_id=? and designer_id=? for update',[$orderId,$designerId]);
        $accounted=(int)(DB::row('select coalesce(sum(original_amount_cents),0) cents from seller_financial_adjustments where order_id=? and designer_id=? and adjustment_type="refund_recovery"',[$orderId,$designerId])['cents']??0);$delta=self::recoveryGrowth($cumulativeRequiredCents,$accounted);if(!$delta){if($owns)DB::commit();return;}
        $sequence=(int)(DB::row('select count(*) c from seller_financial_adjustments where order_id=? and designer_id=? and adjustment_type="refund_recovery"',[$orderId,$designerId])['c']??0)+1;
        DB::exec('insert ignore into seller_financial_adjustments(order_id,designer_id,adjustment_type,amount_cents,original_amount_cents,balance_cents,event_key,note) values (?,? ,"refund_recovery",?,?,?,?,?)',[$orderId,$designerId,$delta,$delta,$delta,'refund-recovery:order:'.$orderId.':seller:'.$designerId.':tranche:'.$sequence,'Incremental post-transfer recovery obligation; applied to future earnings.']);
        if($owns)DB::commit();}catch(\Throwable $e){if($owns&&DB::pdo()->inTransaction())DB::rollBack();throw$e;}
    }

    public function claimPayout(int $sellerPayoutId):array
    {
        $owns=!DB::pdo()->inTransaction();if($owns)DB::begin();try{$base=DB::row('select order_id from seller_payouts where id=?',[$sellerPayoutId]);if(!$base)throw new \DomainException('Seller payout not found.');$order=DB::row('select * from orders where id=? for update',[$base['order_id']]);$p=DB::row('select * from seller_payouts where id=? for update',[$sellerPayoutId]);$designer=DB::row('select stripe_connect_account_id,stripe_details_submitted,stripe_payouts_enabled,status from designers where id=? for update',[$p['designer_id']]);$unresolved=(int)(DB::row('select count(*) c from marketplace_refund_observations where order_id=? and allocation_status<>"reconciled"',[$p['order_id']])['c']??0);if(!in_array($order['payment_status'],['paid','partially_refunded'],true)||in_array($order['status'],['failed','cancelled','refunded'],true)||!empty($order['manual_review_required'])||$unresolved>0||StripeService::cents($p['seller_payout_amount'])<=0||!$designer||$designer['status']!=='approved'||empty($designer['stripe_connect_account_id'])||empty($designer['stripe_details_submitted'])||empty($designer['stripe_payouts_enabled']))throw new \DomainException('Seller payout is not currently eligible.');if($p['recovery_claim_status']!=='unclaimed'){$claimed=$p['recovery_claim_status']==='applied'?$p['recovery_applied_amount']:$p['recovery_reserved_amount'];if($owns)DB::commit();return['applied_cents'=>StripeService::cents($claimed),'transfer_cents'=>StripeService::cents($p['transfer_amount_after_recovery']),'replay'=>true,'zero_transfer'=>$p['recovery_claim_status']==='applied'&&StripeService::cents($p['transfer_amount_after_recovery'])===0];}
            $rows=DB::rows('select * from seller_financial_adjustments where designer_id=? and adjustment_type="refund_recovery" and status="open" and balance_cents>0 order by id for update',[$p['designer_id']]);$left=StripeService::cents($p['seller_payout_amount']);$reserved=0;foreach($rows as $row){if($left<=0)break;$take=min($left,(int)$row['balance_cents']);DB::exec('update seller_financial_adjustments set balance_cents=balance_cents-?,reserved_cents=reserved_cents+? where id=?',[$take,$take,$row['id']]);DB::exec('insert into seller_recovery_applications(seller_financial_adjustment_id,seller_payout_id,order_id,designer_id,amount_cents,event_key,application_status) values (?,?,?,?,?,?,"reserved")',[$row['id'],$p['id'],$p['order_id'],$p['designer_id'],$take,'recovery-application:payout:'.$p['id'].':adjustment:'.$row['id']]);$reserved+=$take;$left-=$take;}
            DB::exec('update seller_payouts set recovery_reserved_amount=?,transfer_amount_after_recovery=?,recovery_claim_status="reserved",payout_execution_status="reserved" where id=?',[CreditService::formatCents($reserved),CreditService::formatCents($left),$p['id']]);if($owns)DB::commit();return['applied_cents'=>$reserved,'transfer_cents'=>$left,'replay'=>false,'zero_transfer'=>$left===0];
        }catch(\Throwable $e){if($owns&&DB::pdo()->inTransaction())DB::rollBack();throw$e;}
    }
    public function beginPayoutExecution(int $sellerPayoutId,string $key):array
    {
        DB::begin();try{$base=DB::row('select order_id from seller_payouts where id=?',[$sellerPayoutId]);if(!$base)throw new \DomainException('Seller payout not found.');$order=DB::row('select * from orders where id=? for update',[$base['order_id']]);$p=DB::row('select * from seller_payouts where id=? for update',[$sellerPayoutId]);$unresolved=(int)(DB::row('select count(*) c from marketplace_refund_observations where order_id=? and allocation_status<>"reconciled"',[$p['order_id']])['c']??0);if($p['payout_execution_status']!=='completed'&&(!in_array($order['payment_status'],['paid','partially_refunded'],true)||in_array($order['status'],['failed','cancelled','refunded'],true)||!empty($order['manual_review_required'])||$unresolved>0||$p['recovery_claim_status']!=='reserved'))throw new \DomainException('Payout execution is not currently eligible.');if($p['payout_execution_status']==='completed'){DB::commit();return['execute'=>false,'completed'=>true,'transfer_cents'=>StripeService::cents($p['transfer_amount_after_recovery'])];}$fresh=$p['payout_execution_status']!=='attempting'||empty($p['payout_execution_claimed_at'])||strtotime($p['payout_execution_claimed_at'])<time()-300;if(!$fresh){DB::commit();return['execute'=>false,'completed'=>false,'transfer_cents'=>StripeService::cents($p['transfer_amount_after_recovery'])];}if(!empty($p['payout_execution_key'])&&$p['payout_execution_key']!==$key)throw new \DomainException('Payout execution key conflict.');DB::exec('update seller_payouts set payout_execution_status="attempting",payout_execution_key=coalesce(payout_execution_key,?),payout_execution_claimed_at=now() where id=?',[$key,$sellerPayoutId]);DB::commit();return['execute'=>true,'completed'=>false,'transfer_cents'=>StripeService::cents($p['transfer_amount_after_recovery'])];}catch(\Throwable $e){if(DB::pdo()->inTransaction())DB::rollBack();throw$e;}
    }
    public function failPayoutExecution(int $sellerPayoutId):void{DB::exec('update seller_payouts set payout_execution_status="failed",payout_execution_claimed_at=null where id=? and payout_execution_status="attempting"',[$sellerPayoutId]);}
    public function resetUnattemptedPayoutPlan(int $sellerPayoutId):bool
    {
        $p=DB::row('select * from seller_payouts where id=? for update',[$sellerPayoutId]);if(!$p||$p['payout_execution_status']!=='reserved')return false;foreach(DB::rows('select * from seller_recovery_applications where seller_payout_id=? and application_status="reserved" for update',[$sellerPayoutId]) as $a){DB::exec('update seller_financial_adjustments set reserved_cents=reserved_cents-?,balance_cents=balance_cents+? where id=?',[$a['amount_cents'],$a['amount_cents'],$a['seller_financial_adjustment_id']]);DB::exec('delete from seller_recovery_applications where id=?',[$a['id']]);}DB::exec('update seller_payouts set recovery_reserved_amount=0,transfer_amount_after_recovery=null,recovery_claim_status="unclaimed",payout_execution_status="unplanned" where id=?',[$sellerPayoutId]);return true;
    }
    public function finalizePayoutClaim(int $sellerPayoutId):bool
    {
        $owns=!DB::pdo()->inTransaction();if($owns)DB::begin();try{$p=DB::row('select * from seller_payouts where id=? for update',[$sellerPayoutId]);if(!$p||$p['recovery_claim_status']==='applied'){if($owns)DB::commit();return false;}foreach(DB::rows('select * from seller_recovery_applications where seller_payout_id=? and application_status="reserved" for update',[$sellerPayoutId]) as $a){DB::exec('update seller_financial_adjustments set reserved_cents=reserved_cents-?,applied_cents=applied_cents+?,status=case when balance_cents=0 and reserved_cents-?=0 then "applied" else "open" end where id=?',[$a['amount_cents'],$a['amount_cents'],$a['amount_cents'],$a['seller_financial_adjustment_id']]);DB::exec('update seller_recovery_applications set application_status="applied",applied_at=now() where id=?',[$a['id']]);}DB::exec('update seller_payouts set completed_economic_value_amount=coalesce(transfer_amount_after_recovery,0)+recovery_reserved_amount,recovery_applied_amount=recovery_reserved_amount,recovery_reserved_amount=0,recovery_claim_status="applied",payout_execution_status="completed",payout_execution_claimed_at=null where id=?',[$sellerPayoutId]);$completed=StripeService::cents($p['transfer_amount_after_recovery'])+StripeService::cents($p['recovery_reserved_amount']);$current=StripeService::cents($p['seller_payout_amount']);if($completed>$current)$this->recordRecovery((int)$p['order_id'],(int)$p['designer_id'],$completed-$current);if($owns)DB::commit();return true;}catch(\Throwable $e){if($owns&&DB::pdo()->inTransaction())DB::rollBack();throw$e;}
    }
    public function repairStoredTransfer(int $sellerPayoutId):bool
    {
        $p=DB::row('select order_id,designer_id,stripe_transfer_id from seller_payouts where id=?',[$sellerPayoutId]);if(!$p||trim((string)$p['stripe_transfer_id'])==='')return false;$this->finalizePayoutClaim($sellerPayoutId);DB::exec('update seller_payouts set payout_status="transferred",stripe_transfer_error=null,payout_execution_status="completed",payout_execution_claimed_at=null,updated_at=now() where id=?',[$sellerPayoutId]);DB::exec('update order_items set seller_payout_status="transferred",stripe_transfer_id=?,stripe_transfer_error=null where order_id=? and designer_id=?',[$p['stripe_transfer_id'],$p['order_id'],$p['designer_id']]);return true;
    }
}
