<?php use App\Core\Helpers as H; ?>
<header class="dashboard-heading"><div><h1>Download history</h1><p class="muted">Files are served only through Creative Moth's protected download route.</p></div><a class="btn alt" href="/browse">Browse products</a></header>
<?php if(!$items&&!$customFinals&&!$collabs):?><section class="card empty-state"><h2>No downloads yet</h2><p>Your eligible purchases will appear here after Stripe confirms payment.</p><a class="btn" href="/browse">Browse marketplace</a></section><?php endif;?>
<div class="responsive-table"><table><thead><tr><th>Product</th><th>Seller</th><th>Purchased</th><th>Order</th><th>Status</th></tr></thead><tbody>
<?php foreach($items as $i): $paid=($i['payment_status']??'')==='paid';$expired=!empty($i['download_expires_at'])&&strtotime($i['download_expires_at'])<time();$downloadable=($i['fulfillment_type']??'downloadable')==='downloadable';$available=$paid&&!$expired&&$downloadable&&!empty($i['file_id'])&&!empty($i['file_available']); ?>
<tr><td><div class="media-row"><?php if($i['preview_image']??null):?><img class="product-thumb" src="<?=H::assetUrl($i['preview_image'])?>" alt=""><?php endif;?><span><a href="/product/<?=H::e($i['slug'])?>"><?=H::e($i['title'])?></a><?php if($i['file_name']??null):?><br><small><?=H::e($i['file_name'])?></small><?php endif;?></span></div></td><td><?php if($i['store_slug']??null):?><a href="/store/<?=H::e($i['store_slug'])?>"><?=H::e($i['seller_name'])?></a><?php else:?><?=H::e($i['seller_name'])?><?php endif;?></td><td><?=H::e($i['purchase_date'])?></td><td><a href="/dashboard/order/<?=(int)$i['order_id']?>">#<?=(int)$i['order_id']?></a></td><td><?php if(($i['payment_status']??'')==='refunded'):?><span class="status-badge danger">Refunded</span><?php elseif($available):?><a class="btn" href="/download/<?=(int)$i['file_id']?>">Download</a><?php elseif(!$downloadable):?><span class="status-badge neutral">Manual delivery</span><?php elseif($expired):?><span class="status-badge danger">Expired</span><?php elseif(!$paid):?><span class="status-badge warning">Unpaid / unavailable</span><?php else:?><span class="status-badge neutral">File unavailable</span><?php endif;?> <?php if(!empty($i['review_id'])):?><a href="/dashboard/reviews/<?=(int)$i['review_id']?>">View/Edit Review</a><?php elseif(!empty($i['review_eligible_at'])):?><a href="/dashboard/reviews/new/<?=(int)$i['id']?>">Leave a Review</a><?php endif;?></td></tr>
<?php endforeach;?></tbody></table></div>

<?php if(!empty($collabs)):?><section><h2>Collab Bundles</h2><?php foreach($collabs as $collab):?><article class="card"><strong><?=H::e($collab['title'])?></strong> · Order <a href="/dashboard/order/<?=(int)$collab['order_id']?>">#<?=(int)$collab['order_id']?></a> · <?php if($collab['download_eligible']):?><a class="btn" href="/collab-download/<?=(int)$collab['order_item_id']?>">Download ZIP</a><?php else:?><span class="status-badge danger">Fully refunded</span><?php endif;?></article><?php endforeach;?></section><?php endif;?>
<?php if(!empty($customFinals)):?><section><h2>Custom-design deliveries</h2><?php foreach($customFinals as $file):$snapshot=json_decode($file['service_snapshot'],true)?:[];?><article class="card"><strong><?=H::e($snapshot['title']??'Custom design')?></strong> by <?=H::e($file['seller_name'])?> — <a href="/custom-order-files/<?=$file['id']?>">Download <?=H::e($file['original_name'])?></a><?php if(!empty($file['review_id'])):?> · <a href="/dashboard/reviews/<?=(int)$file['review_id']?>">View/Edit Review</a><?php elseif(!empty($file['review_eligible_at'])):?> · <a href="/dashboard/reviews/new/<?=(int)$file['order_item_id']?>">Leave a Review</a><?php endif;?></article><?php endforeach?></section><?php endif?>
