<?php
require dirname(__DIR__).'/app/bootstrap.php';
use App\Core\Database as DB;use App\Services\ProductImportReviewService;use App\Services\ProductSubmissionService;
if(($_ENV['RUN_DISPOSABLE_DB_TESTS']??getenv('RUN_DISPOSABLE_DB_TESTS')?:'')!=='1'){echo "SKIP: set RUN_DISPOSABLE_DB_TESTS=1 with disposable DB credentials; this test may create and delete fixture rows.\n";exit(0);}
$fail=0;$check=function(bool $ok,string $name)use(&$fail){echo($ok?'PASS':'FAIL').": $name\n";if(!$ok)$fail++;};
try{$pdo=DB::pdo();}catch(Throwable $e){echo "SKIP: disposable MariaDB unavailable: {$e->getMessage()}\n";exit(0);}
$original=(string)$pdo->query('select database()')->fetchColumn();$fixture='phase124_fixture_'.bin2hex(random_bytes(4));
try{
 $pdo->exec("create database `$fixture` character set utf8mb4 collate utf8mb4_unicode_ci");$pdo->exec("use `$fixture`");
 $pdo->exec("create table users(id bigint primary key,name varchar(120),email varchar(190),role varchar(20));
 create table designers(id bigint primary key,user_id bigint not null,display_name varchar(120),store_slug varchar(140),bio text,status varchar(30),stripe_connect_account_id varchar(190),stripe_details_submitted tinyint,stripe_payouts_enabled tinyint);
 create table categories(id bigint primary key,name varchar(120),slug varchar(140),is_active tinyint);
 create table products(id bigint primary key auto_increment,designer_id bigint not null,category_id bigint null,title varchar(190),slug varchar(210) unique,short_description text,description text,price decimal(10,2) null,fulfillment_type enum('downloadable','google_drive') not null default 'downloadable',manual_delivery_instructions text,commercial_license_enabled tinyint default 0,commercial_license_price decimal(10,2) default 0,pod_allowed tinyint default 0,digital_resale_prohibited tinyint default 1,ai_disclosure enum('No AI Used','AI Assisted','AI Generated') not null,is_hand_drawn tinyint default 0,seo_title varchar(70),seo_description varchar(170),status varchar(40) default 'draft',rejection_reason text,created_at timestamp default current_timestamp,updated_at timestamp default current_timestamp on update current_timestamp);
 create table product_batches(id bigint primary key auto_increment,designer_id bigint not null,name varchar(190),created_at timestamp default current_timestamp,updated_at timestamp default current_timestamp on update current_timestamp);
 create table product_batch_items(id bigint primary key auto_increment,batch_id bigint not null,product_id bigint not null,sort_order int,validation_errors json,submitted_at timestamp null,created_at timestamp default current_timestamp,unique(product_id),foreign key(batch_id) references product_batches(id) on delete cascade,foreign key(product_id) references products(id) on delete cascade);
 create table tags(id bigint primary key auto_increment,name varchar(80),slug varchar(100) unique);create table product_tags(product_id bigint,tag_id bigint,primary key(product_id,tag_id));
 create table product_images(id bigint primary key auto_increment,product_id bigint,image_path varchar(255),original_image_path varchar(255),watermark_status varchar(40),watermark_error varchar(255),alt_text varchar(255),sort_order int);
 create table product_files(id bigint primary key auto_increment,product_id bigint,storage_path varchar(255),original_name varchar(255));create table license_types(id bigint primary key,license_key varchar(80),name varchar(120),description text,sort_order int,is_active tinyint);create table product_license_types(id bigint primary key auto_increment,product_id bigint,license_type_id bigint,is_enabled tinyint,is_default tinyint default 0,price decimal(10,2),custom_name varchar(120),description text,sort_order int default 0);
 create table ip_risk_terms(id bigint primary key auto_increment,term varchar(190),normalized_term varchar(190),category varchar(80),is_enabled tinyint default 1);create table ip_risk_term_aliases(id bigint primary key auto_increment,ip_risk_term_id bigint,alias varchar(190),normalized_alias varchar(190),is_enabled tinyint default 1);
 create table product_ip_risk_scans(id bigint primary key auto_increment,product_id bigint,seller_id bigint,content_fingerprint char(64),match_fingerprint char(64),active_match_count int,scanned_at timestamp);create table product_ip_risk_detections(id bigint primary key auto_increment,product_id bigint,scan_id bigint,ip_risk_term_id bigint,matched_term varchar(190),matched_alias varchar(190),matched_value_key varchar(190),category varchar(80),source_field varchar(80),is_active tinyint,first_detected_at timestamp null,last_detected_at timestamp null,created_at timestamp default current_timestamp,updated_at timestamp default current_timestamp);
 create table product_ip_risk_states(product_id bigint primary key,latest_scan_id bigint,review_status varchar(40),latest_match_fingerprint char(64),created_at timestamp,updated_at timestamp);create table product_ip_rights_confirmations(id bigint primary key auto_increment,product_id bigint,scan_id bigint,seller_id bigint,confirmation_text text,confirmed_at timestamp);");
 $pdo->exec(file_get_contents(dirname(__DIR__).'/database/migrations/2026_08_21_phase_12_4_csv_product_import.sql'));
 $pdo->exec("insert into users values(1,'One','one@test','designer'),(2,'Two','two@test','designer');insert into designers values(1,1,'One','one','complete seller biography','approved','acct',1,1),(2,2,'Two','two','complete seller biography','approved','acct',1,1);insert into categories values(1,'Art','art',1);insert into license_types values(1,'personal','Personal','Personal use',10,1);");
 $pdo->exec("create trigger fail_import before insert on products for each row begin if new.title='FAIL' then signal sqlstate '45000' set message_text='fixture failure'; end if; end");
 $record=function(string $title,string $fingerprint):string{return json_encode(['source_id'=>'id:'.$fingerprint,'source_fingerprint'=>hash('sha256',$fingerprint),'sku'=>null,'title'=>$title,'short_description'=>'','description'=>'Description','price'=>'5.00','price_requires_review'=>false,'tags'=>[],'categories'=>['Art'],'product_type'=>'digital','source_type_requires_review'=>false,'seo_title'=>null,'seo_description'=>null,'images'=>[],'warnings'=>[]]);};
 $makeRun=function(array $titles,int $designer=1)use($pdo,$record):int{$pdo->prepare('insert into product_import_runs(designer_id,source_platform,display_filename,total_detected,status) values(?,"shopify","fixture.csv",?,"preview")')->execute([$designer,count($titles)]);$run=(int)$pdo->lastInsertId();foreach($titles as $i=>$title){$fp=hash('sha256',$run.'-'.$i);$pdo->prepare('insert into product_import_items(import_run_id,source_key,source_fingerprint,source_title,normalized_data,result_status,warnings) values(?,?,?,?,?,"ready","[]")')->execute([$run,'id:'.$fp,$fp,substr($title,0,190),$record($title,$fp)]);}return $run;};
 $worker=dirname(__DIR__).'/tests/helpers/Phase124ImportControllerProbe.php';$env=array_merge($_ENV,['PHASE124_FIXTURE_DB'=>$fixture]);$runController=function(int $seller,int $run,array $post,string $action='confirm')use($worker,$env){$pipes=[];$p=proc_open([PHP_BINARY,$worker,(string)$seller,(string)$run,base64_encode(json_encode($post)),$action],[1=>['pipe','w'],2=>['pipe','w']],$pipes,dirname(__DIR__),$env);$out=stream_get_contents($pipes[1]).stream_get_contents($pipes[2]);fclose($pipes[1]);fclose($pipes[2]);return [proc_close($p),$out];};
 $zero=$makeRun(['Not selected']);$runController(1,$zero,[]);$z=$pdo->query("select * from product_import_runs where id=$zero")->fetch();$check((int)$z['selected_count']===0&&(int)$z['skipped_count']===1&&$z['batch_id']===null,'zero selection creates no batch and finalizes ready item as skipped');
 $first=$makeRun(['FAIL','Second succeeds']);$runController(1,$first,['select_all'=>1]);$r=$pdo->query("select * from product_import_runs where id=$first")->fetch();$check((int)$r['failed_count']===1&&(int)$r['imported_count']===1&&$r['batch_id']!==null,'first product failure does not prevent second product success');$check((int)$pdo->query("select count(*) from product_batch_items where batch_id=".(int)$r['batch_id'])->fetchColumn()===1,'partial import batch retains only successful product');$beforeProducts=(int)$pdo->query('select count(*) from products')->fetchColumn();$runController(1,$first,['select_all'=>1]);$check((int)$pdo->query('select count(*) from products')->fetchColumn()===$beforeProducts,'a repeated confirmation cannot create duplicate products or batches');
 $middle=$makeRun(['First','FAIL','Third']);$runController(1,$middle,['select_all'=>1]);$m=$pdo->query("select * from product_import_runs where id=$middle")->fetch();$check((int)$m['imported_count']===2&&(int)$m['failed_count']===1,'middle product failure preserves surrounding successes');
 $all=$makeRun(['FAIL','FAIL']);$runController(1,$all,['select_all'=>1]);$a=$pdo->query("select * from product_import_runs where id=$all")->fetch();$check((int)$a['failed_count']===2&&$a['batch_id']===null,'all failures remove empty import batch');
 $product=(int)$pdo->query("select product_id from product_import_items where import_run_id=$first and result_status='imported'")->fetchColumn();$reviewService=new ProductImportReviewService();$reviewService->add($product,['price']);$errors=$reviewService->errors($product);$blocked=(new ProductSubmissionService())->submit($product,1,1);$check(count($errors)>=3&&!$blocked['ok'],'durable and current import requirements block normal submission');$reviewService->clearAfterExplicitSave($product,['ai','bogus']);$open=$reviewService->openKeys($product);$check(!in_array('ai',$open,true)&&in_array('licenses',$open,true)&&in_array('price',$open,true),'requirements clear selectively and unknown keys are rejected');$reviewService->clearAfterExplicitSave($product,['licenses','fulfillment','price','source_type']);$remaining=$reviewService->errors($product);$check(!str_contains(implode(' ',$remaining),'licenses')&&str_contains(implode(' ',$remaining),'preview image'),'explicit review clears only selected choices while current missing assets remain enforced');
 $reviewService->add($product,['ai','licenses','fulfillment','price']);$pdo->exec("update products set price=null,ai_disclosure=null where id=$product");$titleBefore=$pdo->query("select title from products where id=$product")->fetchColumn();$runController(1,$product,['title'=>$titleBefore.' edited','description'=>'Description','action'=>'draft'],'edit');$saved=$pdo->query("select title,price,ai_disclosure,status from products where id=$product")->fetch();$open=$reviewService->openKeys($product);$check(str_ends_with($saved['title'],' edited')&&$saved['price']===null&&$saved['ai_disclosure']===null&&$saved['status']==='draft'&&in_array('ai',$open,true)&&in_array('licenses',$open,true),'title-only controller save preserves NULL values and clears no gates');
 $runController(1,$product,['title'=>$saved['title'],'description'=>'Description','price'=>'0.00','ai_disclosure'=>'AI Assisted','confirm_import_licenses'=>1,'action'=>'draft'],'edit');$saved=$pdo->query("select price,ai_disclosure from products where id=$product")->fetch();$open=$reviewService->openKeys($product);$check($saved['price']==='0.00'&&$saved['ai_disclosure']==='AI Assisted'&&!in_array('price',$open,true)&&!in_array('ai',$open,true)&&!in_array('licenses',$open,true)&&in_array('fulfillment',$open,true),'edit controller clears only explicitly completed gates and accepts intentional zero price');
 $reviewService->add($product,['source_type']);$productCount=(int)$pdo->query('select count(*) from products')->fetchColumn();[, $duplicateOutput]=$runController(1,$product,[],'duplicate');$check((int)$pdo->query('select count(*) from products')->fetchColumn()===$productCount&&str_contains($duplicateOutput,'source product type'),'unresolved source type behaviorally blocks duplication without losing context');
 [, $submitOutput]=$runController(1,$product,[],'submit');$check(str_contains($submitOutput,'Review and explicitly choose Asset Moth fulfillment'),'direct submit propagates the actual unresolved requirement error');
 $batch=(int)$pdo->query("select batch_id from product_batch_items where product_id=$product")->fetchColumn();$pdo->exec("update product_batch_items set submission_errors='[\\\"Fresh submission failure\\\"]' where product_id=$product");[, $batchOutput]=$runController(1,$batch,[],'view_batch');$check(str_contains($batchOutput,'Fresh submission failure'),'batch submission error survives redirect and displays with current validation');$runController(1,$product,['title'=>$saved['ai_disclosure'].' corrected','description'=>'Description','price'=>'0.00','ai_disclosure'=>'AI Assisted','action'=>'draft'],'edit');$check($pdo->query("select submission_errors is null from product_batch_items where product_id=$product")->fetchColumn()==1,'successful correction clears stale batch submission error');
 $countRun=$makeRun(['Skip']);$pdo->exec("update product_import_items set result_status='invalid',error_message='invalid' where import_run_id=$countRun");$fpCount=hash('sha256','count-duplicate');$pdo->prepare('insert into product_import_items(import_run_id,source_key,source_fingerprint,source_title,normalized_data,result_status,warnings,duplicate_product_id) values(?,?,?,?,?,\"duplicate\",\"[]\",?)')->execute([$countRun,'duplicate',$fpCount,'Duplicate',$record('Duplicate','count-duplicate'),$product]);$pdo->prepare('insert into product_import_items(import_run_id,source_key,source_fingerprint,source_title,normalized_data,result_status,warnings) values(?,?,?,?,?,\"ready\",\"[]\")')->execute([$countRun,'skip',hash('sha256','count-skip'),'Skip',$record('Skip','count-skip')]);$pdo->exec("update product_import_runs set total_detected=3 where id=$countRun");$runController(1,$countRun,[]);$counted=$pdo->query("select * from product_import_runs where id=$countRun")->fetch();$check((int)$counted['invalid_count']===1&&(int)$counted['duplicate_count']===1&&(int)$counted['skipped_count']===1,'confirmation persists accurate invalid, duplicate, and skipped counts');
 $failureRun=$makeRun(['Committed before failure','Unattempted']);$pdo->exec("create trigger fail_warning_update before update on product_import_items for each row begin if old.result_status='imported' and new.warnings is not null then signal sqlstate '45000' set message_text='after claim failure'; end if; end");$runController(1,$failureRun,['select_all'=>1]);$pdo->exec('drop trigger fail_warning_update');$recovered=$pdo->query("select * from product_import_runs where id=$failureRun")->fetch();$check($recovered['status']==='partial'&&(int)$recovered['imported_count']===1&&(int)$recovered['failed_count']===1&&$recovered['batch_id']!==null,'unexpected failure after claim preserves committed draft and finalizes processing run as partial');
 $fingerprint=$pdo->query("select source_fingerprint from product_import_sources where product_id=$product")->fetchColumn();$item=(int)$pdo->query("select id from product_import_items where product_id=$product")->fetchColumn();$duplicateRun=$makeRun(['Repeated source']);$duplicateItem=(int)$pdo->query("select id from product_import_items where import_run_id=$duplicateRun")->fetchColumn();try{$pdo->prepare('insert into product_import_sources(designer_id,source_platform,source_key,source_fingerprint,product_id,import_item_id) values(1,\"shopify\",\"repeat\",?,?,?)')->execute([$fingerprint,$product,$duplicateItem]);$sameSellerBlocked=false;}catch(PDOException $e){$sameSellerBlocked=$e->getCode()==='23000';}$check($sameSellerBlocked,'same seller, platform, and source fingerprint is rejected as a duplicate');$pdo->prepare('insert into product_import_runs(designer_id,source_platform,display_filename,total_detected,status) values(2,"shopify","other.csv",1,"preview")')->execute();$otherRun=(int)$pdo->lastInsertId();$pdo->prepare('insert into product_import_items(import_run_id,source_key,source_fingerprint,source_title,normalized_data,result_status,warnings) values(?,?,?,?,?,"ready","[]")')->execute([$otherRun,'same',$fingerprint,'Same',$record('Same','other')]);$check((int)$pdo->query("select count(*) from product_import_items where source_fingerprint=".$pdo->quote($fingerprint))->fetchColumn()===2,'same source identity remains isolated between sellers/runs');
 [, $foreign]=$runController(2,$first,['select_all'=>1]);$check(str_contains($foreign,'404'),'cross-seller import run access is denied');
 echo "PASS: disposable Phase 12.4 relationships and behavioral persistence completed.\n";
}catch(Throwable $e){echo 'FAIL: integration exception: '.$e->getMessage()."\n";$fail++;}finally{try{$pdo->exec("use `$original`");$pdo->exec("drop database if exists `$fixture`");}catch(Throwable){}}exit($fail?1:0);
