<?php
require dirname(__DIR__).'/app/bootstrap.php';
use App\Core\Database as DB; use App\Services\ProductBatchService; use App\Services\ProductSubmissionService;
$fail=0;$check=function(bool $ok,string $name)use(&$fail){echo($ok?'PASS':'FAIL').": $name\n";if(!$ok)$fail++;};
try{$pdo=DB::pdo();}catch(Throwable $e){echo "SKIP: disposable MariaDB unavailable: {$e->getMessage()}\n";exit(77);}
if((getenv('PHASE122_ALLOW_FIXTURE')?:'')!=='1'){echo "SKIP: set PHASE122_ALLOW_FIXTURE=1 with disposable-database privileges.\n";exit(77);}
$original=(string)$pdo->query('select database()')->fetchColumn();$fixture='phase122_fixture_'.bin2hex(random_bytes(4));
try{$pdo->exec("create database `$fixture` character set utf8mb4 collate utf8mb4_unicode_ci");$pdo->exec("use `$fixture`");
$pdo->exec("create table users(id bigint primary key,name varchar(120),email varchar(190),role varchar(20));
create table designers(id bigint primary key,user_id bigint not null,display_name varchar(120),store_slug varchar(140),bio text,status varchar(30),stripe_connect_account_id varchar(190),stripe_details_submitted tinyint,stripe_payouts_enabled tinyint);
create table categories(id bigint primary key,name varchar(120));
create table products(id bigint primary key auto_increment,designer_id bigint not null,category_id bigint,title varchar(190),slug varchar(210) unique,short_description text,description text,price decimal(10,2),fulfillment_type varchar(40) default 'downloadable',manual_delivery_instructions text,commercial_license_enabled tinyint default 0,commercial_license_price decimal(10,2) default 0,pod_allowed tinyint default 0,digital_resale_prohibited tinyint default 1,ai_disclosure varchar(80),is_hand_drawn tinyint default 0,seo_title varchar(70),seo_description varchar(170),status varchar(40) default 'draft',rejection_reason text,created_at timestamp default current_timestamp,updated_at timestamp default current_timestamp on update current_timestamp);
create table tags(id bigint primary key auto_increment,name varchar(120),slug varchar(140) unique);create table product_tags(product_id bigint,tag_id bigint,primary key(product_id,tag_id));
create table license_types(id bigint primary key auto_increment,license_key varchar(80) unique,name varchar(120),description text,sort_order int,is_active tinyint);
create table product_license_types(id bigint primary key auto_increment,product_id bigint,license_type_id bigint,is_enabled tinyint,is_default tinyint,price decimal(10,2),custom_name varchar(120),description text,sort_order int,unique(product_id,license_type_id));
create table product_images(id bigint primary key auto_increment,product_id bigint,image_path varchar(255),original_image_path varchar(255),sort_order int default 0);create table product_files(id bigint primary key auto_increment,product_id bigint,storage_path varchar(255),original_name varchar(255));create table orders(id bigint primary key,payment_status varchar(40));create table order_items(id bigint primary key auto_increment,order_id bigint,product_id bigint);create table cart_items(id bigint primary key auto_increment,product_id bigint);create table wishlists(id bigint primary key auto_increment,product_id bigint);create table notifications(id bigint primary key auto_increment,user_id bigint,type varchar(80),audience varchar(40),title varchar(190),message text,event_key varchar(190) unique,action_url varchar(255),created_at timestamp default current_timestamp);create table email_messages(id bigint primary key auto_increment,classification varchar(40),recipient_email varchar(190),recipient_name varchar(120),subject varchar(190),template varchar(80),template_data json,campaign_id bigint,campaign_recipient_id bigint,waitlist_entry_id bigint,deduplication_key varchar(190) unique,status varchar(40),attempt_count int,next_attempt_at timestamp null,last_error varchar(500),created_at timestamp default current_timestamp,claimed_at timestamp null,sent_at timestamp null,updated_at timestamp default current_timestamp);");
$pdo->exec(file_get_contents(dirname(__DIR__).'/database/migrations/2026_07_13_phase_10_4_ip_risk_compliance.sql'));
$migration=file_get_contents(dirname(__DIR__).'/database/migrations/2026_08_12_phase_12_2_product_batches.sql');$pdo->exec($migration);$pdo->exec($migration);
$check((int)$pdo->query("select count(*) from information_schema.tables where table_schema='$fixture' and table_name in ('product_batches','product_batch_items')")->fetchColumn()===2,'real Phase 12.2 migration is repeatable');
$pdo->exec("insert into users values(1,'Seller One','one@test','designer'),(2,'Seller Two','two@test','designer');insert into designers values(1,1,'One','one','Ready seller bio','approved','acct1',1,1),(2,2,'Two','two','Ready seller bio','approved','acct2',1,1);insert into categories values(1,'Art');insert into tags values(1,'summer','summer'),(2,'bright','bright');insert into license_types(license_key,name,description,sort_order,is_active) values('personal','Personal','Included',10,1),('pod','POD','POD',20,1),('digital-product','Digital Product License','Digital resale permission',30,1);
insert into product_batches(designer_id,name) values(1,'Persisted batch');insert into products(designer_id,category_id,title,slug,short_description,description,price,ai_disclosure,status) values(1,1,'Template','template','Short','Complete description',12.50,'AI Assisted','draft'),(1,1,'Second','second','','Other',5,'No AI Used','draft'),(1,1,'Third','third','','Other',5,'No AI Used','draft');insert into product_batch_items(batch_id,product_id,sort_order) values(1,1,1),(1,2,2),(1,3,3);insert into product_tags values(1,1),(1,2);insert into product_license_types(product_id,license_type_id,is_enabled,is_default,price,description,sort_order) select 1,id,1,license_key='personal',case license_key when 'digital-product' then 9.75 when 'pod' then 4.25 else 0 end,description,sort_order from license_types;");
$service=new ProductBatchService();$check(count($service->products(1,1))===3,'seller-owned batch reopens with three independent drafts');
$worker=dirname(__DIR__).'/tests/helpers/Phase122BatchControllerProbe.php';$env=array_merge($_ENV,['PHASE122_FIXTURE_DB'=>$fixture]);$run=function(int $seller,int $batch,array $post,string $csrf='valid')use($worker,$env){$pipes=[];$process=proc_open([PHP_BINARY,$worker,(string)$seller,(string)$batch,$csrf,base64_encode(json_encode($post))],[1=>['pipe','w'],2=>['pipe','w']],$pipes,dirname(__DIR__),$env);$out=stream_get_contents($pipes[1]).stream_get_contents($pipes[2]);fclose($pipes[1]);fclose($pipes[2]);return [proc_close($process),$out];};
$run(1,1,['action'=>'copy','copy_fields'=>['short_description','description','price','category_id','ai_disclosure','tags','licenses']]);$copied=$pdo->query('select * from products where id=2')->fetch();$check($copied['short_description']==='Short'&&(float)$copied['price']===12.5&&$copied['ai_disclosure']==='AI Assisted','controller copy persists shared fields from Product 1');$check((int)$pdo->query('select count(*) from product_tags where product_id=2')->fetchColumn()===2,'controller copy persists complete tag set');$licenses=$pdo->query("select l.license_key,p.price from product_license_types p join license_types l on l.id=p.license_type_id where p.product_id=2 order by l.license_key")->fetchAll();$prices=array_column($licenses,'price','license_key');$check(count($licenses)===3&&(float)$prices['digital-product']===9.75&&(float)$prices['pod']===4.25,'controller copy persists paid POD and Digital Product License settings');
$pdo->exec('update products set price=99 where id=2');$check((float)$pdo->query('select price from products where id=1')->fetchColumn()===12.5&&(float)$pdo->query('select price from products where id=3')->fetchColumn()===12.5,'copied products remain independently editable');
$run(1,1,['action'=>'add']);$afterAdd=$service->products(1,1);$added=(int)end($afterAdd)['id'];$check(count($afterAdd)===4,'controller add mutates persisted batch membership');$run(1,1,['action'=>'remove','product_id'=>$added]);$check(count($service->products(1,1))===3&&!$pdo->query("select id from products where id=$added")->fetchColumn(),'controller remove deletes eligible draft membership and product');
$duplicateIsolated=false;try{$pdo->exec("insert into products(designer_id,title,slug,description,price,ai_disclosure,status) values(1,'Duplicate','second','Valid',1,'No AI Used','draft')");}catch(Throwable){$duplicateIsolated=true;}$check($duplicateIsolated&&(int)$pdo->query('select count(*) from products')->fetchColumn()===3,'duplicate slug fails only affected product');
$pdo->exec("update products set description='' where id=3;insert into product_images(product_id,image_path) values(1,'a.jpg'),(2,'b.jpg');insert into product_files(product_id,storage_path,original_name) values(1,'products/a.zip','a.zip'),(2,'products/b.zip','b.zip')");$run(1,1,['action'=>'submit_selected','products'=>[1]]);$check($pdo->query('select status from products where id=1')->fetchColumn()==='approved'&&$pdo->query('select status from products where id=2')->fetchColumn()==='draft','controller Submit Selected approves only selected clean draft');
$run(1,1,['action'=>'submit_all']);$errors=json_decode((string)$pdo->query('select validation_errors from product_batch_items where product_id=3')->fetchColumn(),true);$check($pdo->query('select status from products where id=2')->fetchColumn()==='approved'&&$pdo->query('select status from products where id=3')->fetchColumn()==='draft'&&in_array('Full Description is required.',$errors?:[],true),'controller Submit All approves every valid draft and retains invalid draft with product-specific error');
$pdo->exec("update products set title='Disney design',description='Valid',status='draft' where id=3;insert into product_images(product_id,image_path) values(3,'c.jpg');insert into product_files(product_id,storage_path,original_name) values(3,'products/c.zip','c.zip')");$run(1,1,['action'=>'submit_all']);$blockedErrors=json_decode((string)$pdo->query('select validation_errors from product_batch_items where product_id=3')->fetchColumn(),true);$check($pdo->query('select status from products where id=3')->fetchColumn()==='draft'&&str_contains(implode(' ',$blockedErrors?:[]),'confirm'),'controller flagged draft requires rights confirmation');$run(1,1,['action'=>'submit_all','ip_rights_confirmation'=>[3]]);$check($pdo->query('select status from products where id=3')->fetchColumn()==='pending_review','controller confirmed flagged draft enters pending review');
[, $foreign]=$run(2,1,['action'=>'add']);[, $csrf]=$run(1,1,['action'=>'add'],'invalid');$check(str_contains($foreign,'404')&&str_contains($csrf,'419')&&count($service->products(1,1))===3,'controller rejects cross-seller mutation and invalid CSRF without membership changes');$ids=array_column($service->products(1,1),'id');sort($ids);$check($ids===[1,2,3],'membership survives controller copy, edits, and submissions');
}catch(Throwable $e){echo 'FAIL: integration exception: '.$e->getMessage()."\n";$fail++;}finally{try{$pdo->exec("use `$original`");$pdo->exec("drop database if exists `$fixture`");}catch(Throwable){}}exit($fail?1:0);
