<?php
require dirname(__DIR__).'/app/bootstrap.php';
use App\Controllers\CustomDesignController;use App\Services\CustomDesignService;use App\Services\EmailQueueService;
$fail=0;$check=function(bool $ok,string $name)use(&$fail){echo($ok?'PASS':'FAIL').": $name\n";if(!$ok)$fail++;};$root=dirname(__DIR__);$source=fn($f)=>file_get_contents($root.'/'.$f);$service=$source('app/Services/CustomDesignService.php');$controller=$source('app/Controllers/CustomDesignController.php');$routes=$source('public/index.php');$buyer=$source('app/Controllers/BuyerController.php');$email=$source('app/Services/EmailQueueService.php');
$messaging=$source('app/Services/MessagingService.php');
$valid=['new:start:seller'=>'in_progress','revision_requested:start_revision:seller'=>'in_progress','in_progress:proof:seller'=>'proof_review','proof_review:revision:buyer'=>'revision_requested','proof_review:approve:buyer'=>'in_progress','in_progress:final:seller'=>'completed'];foreach($valid as $case=>$expected){[$state,$action,$side]=explode(':',$case);$check(CustomDesignService::transitionFor($state,$action,$side)===$expected,"EXECUTABLE transition $case");}foreach([['new','final','seller'],['completed','start','seller'],['refunded','start','seller'],['cancelled','start','seller'],['proof_review','revision','seller'],['in_progress','proof','buyer']] as $case)$check(CustomDesignService::transitionFor(...$case)===null,'EXECUTABLE invalid/terminal transition '.implode(':',$case));
foreach(['buyerOrder','sellerOrder'] as $action){$method=new ReflectionMethod(CustomDesignController::class,$action);$check($method->getNumberOfRequiredParameters()===1,"EXECUTABLE route action $action accepts its one captured parameter");}$check(str_contains($routes,"[CustomDesignController::class, 'buyerOrder']")&&str_contains($routes,"[CustomDesignController::class, 'sellerOrder']"),'SOURCE CONTRACT explicit buyer/seller routes use compatible wrappers');
$check(CustomDesignService::buyerFinalEligible('completed','paid'),'EXECUTABLE paid final delivery is eligible');$check(CustomDesignService::buyerFinalEligible('completed','partially_refunded'),'EXECUTABLE partially-refunded final delivery is eligible');$check(!CustomDesignService::buyerFinalEligible('completed','refunded')&&!CustomDesignService::buyerFinalEligible('in_progress','paid'),'EXECUTABLE refunded or incomplete final delivery is denied');
$reported=0;$fallback=0;$result=CustomDesignService::containCommunicationFailure(static fn()=>throw new RuntimeException('notify'),function()use(&$reported){$reported++;throw new RuntimeException('report');},function()use(&$fallback){$fallback++;});$check(!$result&&$reported===1&&$fallback===1,'EXECUTABLE notification and reporter failures are fully contained with fallback');
$check(EmailQueueService::shouldQueueDownloadReady(false)&&!EmailQueueService::shouldQueueDownloadReady(true),'EXECUTABLE normal payment keeps download-ready email while custom payment suppresses it');
$check(str_contains($email,'customFinalAvailable')&&str_contains($service,'EmailQueueService::customFinalAvailable')&&str_contains($service,'custom_order_final_email_'),'SOURCE CONTRACT committed custom final delivery queues final-availability email');
$check(str_contains($service,'for update')&&str_contains($service,'where id=? and status=?')&&str_contains($service,'revisions_used=revisions_used+?'),'SOURCE CONTRACT transition persistence locks state and increments an accepted revision once');
$check(str_contains($controller,'o.payment_status in ("paid","partially_refunded","refunded")')&&str_contains($service,"\$side==='seller'"),'SOURCE CONTRACT seller history excludes unpaid briefs while retaining refunded history');
$check(str_contains($buyer,'left join products p on p.id=oi.product_id')&&str_contains($source('app/Views/buyer/order.php'),"!empty(\$i['product_id'])")&&str_contains($source('app/Views/buyer/purchases.php'),'product_titles'),'SOURCE CONTRACT custom-only and normal purchases use snapshot labels without false product links');
$check(str_contains($buyer,'o.payment_status in ("paid","partially_refunded")')&&!str_contains($buyer,'o.payment_status in ("paid","partially_refunded","refunded")'),'SOURCE CONTRACT normal buyer downloads exclude fully refunded custom finals');
$check(str_contains($service,'CreditService::checkoutBreakdown')&&str_contains($service,'credit:reserve')&&str_contains($service,'internal-credit-order:'),'SOURCE CONTRACT custom checkout uses existing credit reservation and internal finalization lifecycle');
$check(str_contains($source('app/Views/public/custom_service.php'),'25MB each')&&str_contains($service,'MAX_SIZE=26214400'),'SOURCE CONTRACT reference upload UI and server agree on 25MB');

$check(!CustomDesignService::retryEligible('cancelled')&&CustomDesignService::retryEligible('new')&&CustomDesignService::retryEligible(null),'EXECUTABLE cancelled custom retry is denied while failed/new custom and ordinary retry remain eligible');
$check(!CustomDesignService::workflowPaymentEligible('refunded')&&CustomDesignService::workflowPaymentEligible('paid')&&CustomDesignService::workflowPaymentEligible('partially_refunded'),'EXECUTABLE fully refunded payment cannot mutate workflow while active payments can');
$attempts=[];CustomDesignService::containCommunicationFailure(function()use(&$attempts){$attempts[]='notification';throw new RuntimeException;},static function(){});CustomDesignService::containCommunicationFailure(function()use(&$attempts){$attempts[]='email';throw new RuntimeException;},static function(){});$check($attempts===['notification','email'],'EXECUTABLE independent communication failures do not suppress later attempts');
$check(str_contains($source('app/Views/emails/custom_final_available.php'),'custom design is complete')&&!str_contains($source('app/Views/emails/custom_final_available.php'),'webhook-confirmed'),'SOURCE CONTRACT custom-final template uses delivery-event copy');
$check(str_contains($controller,"protected_uploads/custom_designs")&&!str_contains($service,'DELIVERY_EXTENSIONS'),'SOURCE CONTRACT custom route is subtree-confined and final formats have no Phase 12.6 allowlist');
$check(str_contains($source('app/Views/buyer/downloads.php'),'!$items&&!$customFinals')&&str_contains($buyer,"\$summary['available_downloads']")&&str_contains($buyer,'co.status="completed"'),'SOURCE CONTRACT custom-only downloads suppress empty state and eligible finals contribute to dashboard count');
$check(str_contains($source('app/Views/buyer/custom_order.php'),"in_array(\$order['payment_status'],['paid','partially_refunded']")&&str_contains($source('app/Views/buyer/custom_order.php'),'Open retained order conversation'),'SOURCE CONTRACT messaging start is active-payment-only while retained conversations remain linkable');
$check(str_contains($source('app/Views/seller/sales.php'),'Custom Design')&&str_contains($source('app/Views/seller/sales.php'),"'/seller/custom-orders/'")&&str_contains($source('app/Views/seller/order_item.php'),'Open custom-order workflow'),'SOURCE CONTRACT seller sales labels and routes custom-design fulfillment');
$check(str_contains($source('app/Controllers/StripeController.php'),'CustomDesignService::retryEligible')&&str_contains($source('app/Views/buyer/payment_cancel.php'),'Submit a new request'),'SOURCE CONTRACT generic retry and cancel UI enforce terminal custom cancellation');

$finalizer=$source('app/Services/OrderFinalizationService.php');$stripe=$source('app/Controllers/StripeController.php');
$check(str_contains($stripe,'DB::begin();try')&&str_contains($stripe,"elseif(\$status==='refunded')")&&str_contains($service,'$owns=!DB::pdo()->inTransaction()')&&str_contains($service,'system_event_key'),'SOURCE CONTRACT payment/custom terminal transitions are atomic, transaction-aware, replay-repairable, and idempotent');
$check(str_contains($finalizer,'product_id<=>?')&&str_contains($finalizer,'custom_service_id<=>?'),'SOURCE CONTRACT commission recovery uses NULL-safe product and custom-service identity');
$check(str_contains($source('app/Views/seller/order_item.php'),"'/messages/start/custom-order/'")&&!str_contains($source('app/Views/seller/order_item.php'),'action="/messages/start/seller-order-item/'),'SOURCE CONTRACT custom seller items cannot expose a second generic conversation action');
$check(substr_count($messaging,"select id from custom_orders where order_item_id=?")===2&&substr_count($messaging,"return \$this->startCustomOrder((int)\$custom['id']")===2,'SOURCE CONTRACT both generic order-item starts delegate custom items to the authoritative custom-order flow');
if($fail)exit(1);echo "PASS: Phase 12.6 executable checks and explicitly labeled source contracts completed. Database/live behavior remains separate.\n";
