<?php
require dirname(__DIR__).'/app/bootstrap.php';
use App\Core\Database as DB;use App\Services\AdminPermissionService;use App\Services\SellerReviewService;
if(($_ENV['RUN_DISPOSABLE_DB_TESTS']??getenv('RUN_DISPOSABLE_DB_TESTS')?:'')!=='1'){echo "SKIP/UNEXECUTED: set RUN_DISPOSABLE_DB_TESTS=1 with disposable MariaDB credentials; this suite creates and drops an isolated database.\n";exit(0);}try{$pdo=DB::pdo();}catch(Throwable $e){echo 'SKIP/UNEXECUTED: disposable MariaDB unavailable: '.$e->getMessage()."\n";exit(0);}
$base=(string)$pdo->query('select database()')->fetchColumn();$db='phase132_'.bin2hex(random_bytes(5));$fail=[];$check=function(bool $ok,string $m)use(&$fail){echo($ok?'PASS: ':'FAIL: ').$m."\n";if(!$ok)$fail[]=$m;};$throws=function(callable $fn,string $class,string $contains='')use($check){try{$fn();$check(false,'expected rejection: '.$contains);}catch(Throwable $e){$check($e instanceof $class&&($contains===''||str_contains($e->getMessage(),$contains)),'rejection: '.$contains);}};
$pdo->exec("create database `$db` character set utf8mb4 collate utf8mb4_unicode_ci");$pdo->exec("use `$db`");
try{
$pdo->exec(<<<'SQL'
create table users(id bigint primary key,name varchar(120),email varchar(190),role enum('buyer','designer','admin'),status enum('active','disabled') default 'active');
create table designers(id bigint primary key,user_id bigint not null,display_name varchar(120),store_slug varchar(140),status enum('approved','disabled') default 'approved',average_rating decimal(3,2) default 0,foreign key(user_id) references users(id));
create table products(id bigint primary key,designer_id bigint not null,title varchar(190),status varchar(30) default 'approved',foreign key(designer_id) references designers(id));
create table orders(id bigint primary key,user_id bigint not null,payment_status varchar(30),created_at timestamp default current_timestamp,foreign key(user_id) references users(id));
create table order_items(id bigint primary key,order_id bigint not null,product_id bigint not null,designer_id bigint not null,product_title varchar(190),seller_name varchar(120),updated_at timestamp default current_timestamp on update current_timestamp,foreign key(order_id) references orders(id),foreign key(product_id) references products(id),foreign key(designer_id) references designers(id));
create table downloads(id bigint primary key auto_increment,user_id bigint,order_id bigint,order_item_id bigint,product_id bigint,product_file_id bigint,status enum('served','denied'),created_at timestamp default current_timestamp);
create table notifications(id bigint primary key auto_increment,user_id bigint,notification_type varchar(80),audience varchar(20),title varchar(190),message text,action_url varchar(500),event_key varchar(190),read_at timestamp null,created_at timestamp default current_timestamp,unique key notification_event(user_id,event_key));
create table admin_access_profiles(user_id bigint primary key,full_access tinyint not null default 0,granted_by bigint);
create table admin_permission_grants(user_id bigint,permission_key varchar(100),granted_by bigint,primary key(user_id,permission_key));
create table admin_permission_audits(id bigint primary key auto_increment,admin_user_id bigint,permission_key varchar(100),action varchar(80),acting_admin_user_id bigint,metadata json,created_at timestamp default current_timestamp);
insert into users values(1,'Buyer One','b1@test','buyer','active'),(2,'Seller One','s1@test','designer','active'),(3,'Buyer Two','b2@test','buyer','active'),(4,'Seller Two','s2@test','designer','active'),(5,'Admin Manage','a1@test','admin','active'),(6,'Admin View','a2@test','admin','active');
insert into designers(id,user_id,display_name,store_slug,status) values(10,2,'Original Store','original','approved'),(20,4,'Other Store','other','approved');
insert into products values(100,10,'Product A','approved'),(200,20,'Product B','approved');
insert into orders(id,user_id,payment_status) values(1000,1,'paid'),(1001,1,'paid'),(1002,3,'paid'),(1003,1,'pending'),(1004,2,'paid');
insert into order_items(id,order_id,product_id,designer_id,product_title,seller_name) values(5000,1000,100,10,'Snapshot A','Original Store'),(5001,1001,100,10,'Snapshot B','Original Store'),(5002,1002,100,10,'Snapshot C','Original Store'),(5003,1003,100,10,'Unpaid','Original Store'),(5004,1004,100,10,'Self Item','Original Store'),(5005,1000,100,10,'Historical served','Original Store'),(5006,1000,100,10,'Historical denied','Original Store'),(5007,1000,100,10,'Snapshot D','Original Store');
insert into downloads(user_id,order_id,order_item_id,product_id,product_file_id,status) values(1,1000,5005,100,1,'served'),(1,1000,5006,100,1,'denied');
insert into admin_access_profiles values(5,0,5),(6,0,5);insert into admin_permission_grants values(5,'reviews.view',5),(5,'reviews.manage',5),(6,'reviews.view',5);
SQL);
$pdo->exec(file_get_contents(dirname(__DIR__).'/database/migrations/2026_09_18_phase_13_2_seller_reviews.sql'));$service=new SellerReviewService();
$throws(fn()=>$service->create(1,5000,'5','not downloaded'),DomainException::class,'successful authorized download');
$check($service->markDownloaded(5000,1),'first successful activation');$check(!$service->markDownloaded(5000,1),'repeat activation is idempotent');$check((int)DB::row('select count(*) c from notifications where event_key="review-available:5000"')['c']===1,'first eligibility notification only once');
$throws(fn()=>$service->markDownloaded(5000,3),DomainException::class,'not review eligible');$service->markDownloaded(5004,2);$throws(fn()=>$service->create(2,5004,'5','self'),DomainException::class,'own store');
$check(DB::row('select review_eligible_at from order_items where id=5005')['review_eligible_at']!==null,'historical served evidence backfilled');$check(DB::row('select review_eligible_at from order_items where id=5006')['review_eligible_at']===null,'denied evidence not backfilled');
foreach([5001,5002,5007] as $item)$service->markDownloaded($item,$item===5002?3:1);
$r1=$service->create(1,5000,'5','Excellent');$r2=$service->create(1,5001,'5','Also excellent');$r3=$service->create(3,5002,'4','Good');$r4=$service->create(1,5007,'3','');
$check((int)DB::row('select rating from seller_reviews where id=?',[$r1])['rating']===5,'5-star review with text');$check(DB::row('select review_text from seller_reviews where id=?',[$r4])['review_text']===null,'stars-only review');
$service->edit(1,$r4,'1','Changed to one');$check((int)DB::row('select rating from seller_reviews where id=?',[$r4])['rating']===1,'1-star review and edit preserve record');$service->edit(1,$r4,'3','');
foreach([['',''],['0',''],['6',''],['2.5',''],['5',str_repeat('x',2001)]] as [$rating,$text])$throws(fn()=>$service->create(1,5005,$rating,$text),InvalidArgumentException::class);
$throws(fn()=>$service->create(1,5000,'5','duplicate'),DomainException::class,'already has');$throws(fn()=>DB::exec('insert into seller_reviews(buyer_id,designer_id,product_id,order_id,order_item_id,buyer_name_snapshot,seller_name_snapshot,product_title_snapshot,rating,review_text,verified_purchase,reviewed_at) select buyer_id,designer_id,product_id,order_id,order_item_id,buyer_name_snapshot,seller_name_snapshot,product_title_snapshot,rating,review_text,verified_purchase,reviewed_at from seller_reviews where id=?',[$r1]),PDOException::class);$throws(fn()=>$service->edit(3,$r1,'1','hijack'),DomainException::class,'not found');
$d=DB::row('select * from designers where id=10');$check((int)$d['review_count']===4&&(int)$d['rating_5_count']===2&&(int)$d['rating_4_count']===1&&(int)$d['rating_3_count']===1&&abs((float)$d['average_rating']-4.25)<.001,'5,5,4,3 aggregate and distribution');
$service->reply(2,$r1,'Seller response');$check((bool)DB::row('select id from seller_review_replies where review_id=?',[$r1]),'own seller reply allowed');$throws(fn()=>$service->reply(4,$r1,'wrong'),DomainException::class,'does not belong');$check((int)DB::row('select count(*) c from notifications where event_key=?',["review-reply:$r1"])['c']===1,'reply notification idempotency key created');$service->reply(2,$r1,'Edited response');$check((int)DB::row('select count(*) c from notifications where event_key=?',["review-reply:$r1"])['c']===1,'reply edits do not duplicate notification');
$service->report(2,$r1,'spam','details');$throws(fn()=>$service->report(2,$r1,'spam','again'),PDOException::class);$check(DB::row('select moderation_status from seller_reviews where id=?',[$r1])['moderation_status']==='published','reporting does not hide review');
$permissions=new AdminPermissionService();$check($permissions->can(6,'reviews.view')&&!$permissions->can(6,'reviews.manage')&&$permissions->can(5,'reviews.manage'),'view-only Admin cannot mutate capability; managing Admin can');
$throws(fn()=>$service->moderate(5,$r1,'removed','','note'),InvalidArgumentException::class);$throws(fn()=>$service->moderate(5,$r1,'removed','reason',''),InvalidArgumentException::class);
$original=DB::row('select review_text from seller_reviews where id=?',[$r1])['review_text'];$service->moderate(5,$r1,'removed','policy','internal');$check(DB::row('select review_text,moderation_status from seller_reviews where id=?',[$r1])===['review_text'=>$original,'moderation_status'=>'removed']&&(int)DB::row('select count(*) c from seller_review_moderation_audits where review_id=?',[$r1])['c']===1,'removal preserves review and audit');$check((int)DB::row('select review_count from designers where id=10')['review_count']===3,'removal recalculates aggregate');$service->moderate(5,$r1,'restored','appeal','restored after review');$check(DB::row('select moderation_status from seller_reviews where id=?',[$r1])['moderation_status']==='published'&&(int)DB::row('select review_count from designers where id=10')['review_count']===4,'restore republishes and recalculates');
$report=(int)DB::row('select id from review_reports where review_id=?',[$r1])['id'];$service->resolveReport(5,$report,'resolved','resolved note');$rp=DB::row('select * from review_reports where id=?',[$report]);$check((int)$rp['admin_user_id']===5&&$rp['status']==='resolved'&&$rp['admin_note']==='resolved note'&&$rp['reviewed_at']&&$rp['resolved_at'],'report resolution persists Admin, outcome, note, and time');
$reply=(int)DB::row('select id from seller_review_replies where review_id=?',[$r1])['id'];$service->moderateReply(5,$reply,'removed','policy','internal reply note');$check(DB::row('select moderation_status,reply_text from seller_review_replies where id=?',[$reply])===['moderation_status'=>'removed','reply_text'=>'Edited response']&&(int)DB::row('select count(*) c from seller_review_reply_moderation_audits where reply_id=?',[$reply])['c']===1,'reply removal preserves content and audit');$throws(fn()=>$service->reply(2,$r1,'republish'),DomainException::class,'cannot be edited');$service->moderateReply(5,$reply,'restored','appeal','restore reply');$check(DB::row('select moderation_status from seller_review_replies where id=?',[$reply])['moderation_status']==='published','reply restoration republishes response');
DB::exec('update products set status="archived",title="Changed title" where id=100');DB::exec('update designers set display_name="Changed Store" where id=10');$snapshot=DB::row('select product_title_snapshot,seller_name_snapshot from seller_reviews where id=?',[$r1]);$check($snapshot===['product_title_snapshot'=>'Snapshot A','seller_name_snapshot'=>'Original Store'],'archival and name changes preserve snapshots');
$check((int)DB::row('select count(*) c from notifications where event_key=?',["seller-review:$r1"])['c']===1,'new-review notification created once');$check(!preg_match('/seller\/reviews.*(delete|hide|rating)/',file_get_contents(dirname(__DIR__).'/public/index.php')),'seller has no destructive review route');
}finally{$pdo->exec("use `$base`");$pdo->exec("drop database if exists `$db`");}
exit($fail?1:0);
