<?php
require dirname(__DIR__).'/app/bootstrap.php';
use App\Controllers\StripeController;use App\Services\CreatorRecognitionService as R;
$fail=0;$check=function(bool $ok,string $name)use(&$fail){echo($ok?'PASS':'FAIL').": $name\n";if(!$ok)$fail++;};
foreach([[0,'Bronze'],[24,'Bronze'],[25,'Silver'],[99,'Silver'],[100,'Gold'],[499,'Gold'],[500,'Platinum'],[1499,'Platinum'],[1500,'Diamond']] as [$sales,$rank])$check(R::rankForSales($sales)===$rank,"$rank at $sales qualifying sales");
$check(R::progress(1500)===['rank'=>'Diamond','next'=>null,'needed'=>0,'percent'=>100],'Diamond has no fake next level');
$items=[['id'=>1,'designer_id'=>1,'total_price'=>'10.00','commission_rate'=>.2],['id'=>2,'designer_id'=>1,'total_price'=>'5.00','commission_rate'=>.2],['id'=>3,'designer_id'=>2,'total_price'=>'15.00','commission_rate'=>.2]];
$a=StripeController::allocateSellerRefund($items,1500,0);$seller1=1500-$a[1]['gross_refund_cents']-$a[2]['gross_refund_cents'];$seller2=1500-$a[3]['gross_refund_cents'];$check($seller1>0&&$seller2>0,'partial refund preserves seller-specific positive merchandise participation');
$a=StripeController::allocateSellerRefund($items,3000,0);$check(1500-$a[1]['gross_refund_cents']-$a[2]['gross_refund_cents']===0&&1500-$a[3]['gross_refund_cents']===0,'full refund removes both seller participations');
$check(R::founderActive('2026-06-07 12:00:00','automatic','2026-08-06 12:00:00'),'Founder active at exactly 60 days');
$check(!R::founderActive('2026-06-07 11:59:59','automatic','2026-08-06 12:00:00'),'Founder inactive after more than 60 days');
$originalTimezone=date_default_timezone_get();date_default_timezone_set('Pacific/Honolulu');$utcResult=R::founderActive('2026-06-07 12:00:00','automatic','2026-08-06 12:00:00');date_default_timezone_set('Asia/Tokyo');$check($utcResult===R::founderActive('2026-06-07 12:00:00','automatic','2026-08-06 12:00:00'),'Founder boundary is independent of PHP default timezone');date_default_timezone_set($originalTimezone);
$check(R::founderActive(null,'force_active','2026-08-06 12:00:00')&&!R::founderActive('2026-08-06 12:00:00','force_inactive','2026-08-06 12:00:00'),'Founder force modes are distinct');
$eligible=[];for($i=51;$i>=1;$i--)$eligible[]=['designer_id'=>$i,'tenth_at'=>$i<=2?'2026-01-01 00:00:00':sprintf('2026-01-%02d 00:00:00',min(28,$i)),'tenth_order_id'=>$i<=2?100+$i:$i];$plan=R::planFounderPositions($eligible,[]);$check(count($plan)===50&&!isset($plan[51]),'first 50 deterministic Founder positions and seller 51 rejected');$check(count(array_unique($plan))===count($plan),'dry-run plan never duplicates positions');$check($plan[1]===1&&$plan[2]===2,'tenth order ID breaks equal timestamp ties');$reservedPlan=R::planFounderPositions($eligible,[1,3]);$check(!in_array(1,$reservedPlan,true)&&!in_array(3,$reservedPlan,true),'reserved positions are never recycled');
$d=['creator_rank'=>'Gold','founder_position'=>7,'founder_active'=>1];$render=function($path,$vars){extract($vars);ob_start();include $path;return ob_get_clean();};$store=$render(dirname(__DIR__).'/app/Views/public/store.php',['d'=>$d+['display_name'=>'Seller','banner_path'=>null,'avatar_path'=>null,'id'=>1,'bio'=>''],'isOwner'=>true,'followers'=>0,'productCount'=>0,'salesCount'=>0,'products'=>[],'socialLinks'=>[]]);$check(str_contains($store,'Gold')&&str_contains($store,'Founder #7'),'storefront renders effective rank and active Founder');$d['founder_active']=0;$store=$render(dirname(__DIR__).'/app/Views/public/store.php',['d'=>$d+['display_name'=>'Seller','banner_path'=>null,'avatar_path'=>null,'id'=>1,'bio'=>''],'isOwner'=>true,'followers'=>0,'productCount'=>0,'salesCount'=>0,'products'=>[],'socialLinks'=>[]]);$check(!str_contains($store,'Founder #7'),'storefront hides inactive Founder');
$p=['id'=>1,'title'=>'Product','store_slug'=>'seller','display_name'=>'Seller','creator_rank'=>'Gold','founder_position'=>7,'founder_active'=>1,'category_slug'=>null,'category_name'=>null,'price'=>'10.00','ai_disclosure'=>'No AI Used','is_hand_drawn'=>0,'pod_allowed'=>0,'fulfillment_type'=>'downloadable','description'=>'Description','short_description'=>'Description'];$productVars=['p'=>$p,'images'=>[],'owned'=>true,'files'=>[],'tags'=>[],'licenses'=>[],'more'=>[],'related'=>[],'shareUrl'=>'https://example.test/product/product','shareText'=>'Product'];$product=$render(dirname(__DIR__).'/app/Views/public/product.php',$productVars);$check(str_contains($product,'Gold')&&str_contains($product,'Founder #7'),'product page renders effective rank and active Founder');$productVars['p']['founder_active']=0;$product=$render(dirname(__DIR__).'/app/Views/public/product.php',$productVars);$check(!str_contains($product,'Founder #7'),'product page hides inactive Founder');foreach(['home.php','product_grid.php'] as $cardView)$check(!str_contains(file_get_contents(dirname(__DIR__).'/app/Views/public/'.$cardView),'creator_rank')&&!str_contains(file_get_contents(dirname(__DIR__).'/app/Views/public/'.$cardView),'founder_active'),"no recognition badge in public $cardView cards");
exit($fail?1:0);
