<?php
require dirname(__DIR__).'/app/bootstrap.php';
use App\Core\Database as DB;use App\Services\MessagingService;use App\Services\NotificationService;use App\Services\EmailQueueService;
if(($_ENV['RUN_DISPOSABLE_DB_TESTS']??getenv('RUN_DISPOSABLE_DB_TESTS')?:'')!=='1'){fwrite(STDERR,"SKIP/UNEXECUTED: set RUN_DISPOSABLE_DB_TESTS=1 with disposable MySQL credentials; this suite creates and drops an isolated database.\n");exit(0);}
$fail=0;$check=function(bool $ok,string $name)use(&$fail){echo($ok?'PASS':'FAIL').": $name\n";if(!$ok)$fail++;};
try{$pdo=DB::pdo();}catch(Throwable $e){fwrite(STDERR,"SKIP/UNEXECUTED: disposable MySQL server unavailable: {$e->getMessage()}\n");exit(0);}
$original=(string)$pdo->query('select database()')->fetchColumn();$fixture='phase125_fixture_'.bin2hex(random_bytes(4));
try{$pdo->exec("create database `$fixture` character set utf8mb4 collate utf8mb4_unicode_ci");$pdo->exec("use `$fixture`");
$pdo->exec("create table users(id bigint primary key,name varchar(120),email varchar(190),password_hash varchar(255) default '',role varchar(20),status varchar(20) default 'active');
create table designers(id bigint primary key,user_id bigint not null unique,display_name varchar(120),store_slug varchar(140),status varchar(30));
create table products(id bigint primary key,designer_id bigint not null,title varchar(190),status varchar(40));
create table orders(id bigint primary key,user_id bigint not null,payment_status varchar(40));
create table order_items(id bigint primary key,order_id bigint not null,product_id bigint not null,designer_id bigint not null,product_title varchar(190));
create table notifications(id bigint primary key auto_increment,user_id bigint,notification_type varchar(80),audience varchar(20),title varchar(190),message text,action_url varchar(500),event_key varchar(190) unique,read_at timestamp null,created_at timestamp default current_timestamp);
create table email_messages(id bigint primary key auto_increment,classification varchar(20),recipient_email varchar(190),recipient_name varchar(120),subject varchar(190),template varchar(80),template_data json,campaign_id bigint null,campaign_recipient_id bigint null,waitlist_entry_id bigint null,deduplication_key varchar(190) unique,next_attempt_at timestamp null,status varchar(20) default 'pending',created_at timestamp default current_timestamp);");
$pdo->exec(file_get_contents(dirname(__DIR__).'/database/migrations/2026_09_04_phase_12_5_internal_messaging.sql'));
$pdo->exec("insert into users(id,name,email,role) values(1,'Buyer','buyer@example.test','designer'),(2,'Seller','seller@example.test','designer'),(3,'Other','other@example.test','buyer'),(4,'Admin','admin@example.test','admin');insert into designers values(10,2,'Seller Shop','seller','approved'),(11,1,'Buyer Shop','buyer-shop','approved');insert into products values(20,10,'Original Product','approved'),(21,11,'Self Product','approved'),(22,11,'Other Seller Product','approved');insert into orders values(30,1,'paid'),(31,3,'paid'),(32,1,'failed');insert into order_items values(40,30,20,10,'Purchased Snapshot'),(41,31,20,10,'Other Buyer Snapshot'),(42,32,20,10,'Failed Snapshot'),(43,31,22,11,'Other Seller Snapshot');");
$s=new MessagingService();$selfProduct=['seller_user_id'=>1];$check(!$s->canStartProduct($selfProduct,1),'buyer cannot start a product conversation with self');$check(!$s->buyerOrderItemEligible(41,1),'buyer cannot start against another buyer order item');$check(!$s->sellerOrderItemEligible(43,2),'seller cannot start against another seller order item');$check(!$s->buyerOrderItemEligible(42,1)&&!$s->sellerOrderItemEligible(42,2),'failed order is ineligible from buyer and seller entry paths');$product=$s->startProduct(20,1);$store=$s->startStore(10,1);$check($product!==$store&&count($s->inbox(2,'seller',false))===0,'abandoned product/store compose rows stay out of recipient inbox');
$c=$s->conversation($product,1);$message=$s->send($c,1,'Question',[]);$check(count($s->inbox(2,'seller',false))===1&&(int)$s->inbox(2,'seller',false)[0]['unread_count']===1,'buyer message exposes the same unread thread to seller');$check($pdo->query("select audience from notifications where event_key='internal-message:$message:recipient:2'")->fetchColumn()==='designer','seller recipient notification uses designer audience');
$sellerConversation=$s->conversation($product,2);$s->markRead($sellerConversation,2);$check((int)$s->inbox(2,'seller',false)[0]['unread_count']===0&&$pdo->query("select read_at is not null from notifications where event_key='internal-message:$message:recipient:2'")->fetchColumn()==1,'opening thread clears matching unread count and messaging notification');$pdo->exec("insert into notifications(user_id,notification_type,audience,title,message,event_key) values(2,'other','designer','Other','Other','unrelated')");$check($pdo->query("select read_at is null from notifications where event_key='unrelated'")->fetchColumn()==1,'unrelated notification remains unread');
$reply=$s->send($sellerConversation,2,'Answer',[]);$check((int)$s->inbox(1,'buyer',false)[0]['unread_count']===1&&$pdo->query("select audience from notifications where event_key='internal-message:$reply:recipient:1'")->fetchColumn()==='buyer','seller reply reaches seller-account purchaser on buyer side');
$pdo->exec("update products set title='Renamed Product' where id=20");$check($s->conversation($product,1)['context_label']==='Product: Original Product','product context snapshot survives rename');$order=$s->startSellerOrderItem(40,2);$check($s->conversation($order,2)['context_label']==='Purchased product: Purchased Snapshot'&&$s->startBuyerOrderItem(40,1)===$order,'seller and buyer resolve the same eligible order thread with purchase snapshot');
$s->archive($c,1,true);$check(count($s->inbox(1,'buyer',false))===0&&count($s->inbox(1,'buyer',true))===1&&count($s->messages($c))===2,'archive is participant-only and retains history');$s->archive($c,1,false);$s->block($c,1,true);$check($s->blocked(1,2)&&!$s->canMessagePair(1,2),'active block denies the production predicate used by both new starts and replies');$s->block($c,2,false);$check($s->blocked(1,2),'non-blocker cannot remove another participant block');$s->block($c,1,false);$check(!$s->blocked(1,2)&&$s->canMessagePair(1,2),'block creator can unblock and messaging becomes eligible again');$afterUnblock=$s->send($c,1,'Works again',[]);$check($afterUnblock>0,'reply succeeds after blocker removes block');
$pdo->exec('alter table message_reports auto_increment=50');$s->report($c,1,'spam','first');$report=(int)$pdo->lastInsertId();$pdo->exec("update message_reports set status='resolved',moderator_user_id=4,moderator_notes='done',reviewed_at=now() where id=$report");$s->report($c,1,'abuse','reopened');$r=$pdo->query("select * from message_reports where id=$report")->fetch();$check($r['status']==='open'&&$r['moderator_user_id']===null&&$r['moderator_notes']===null&&$r['reviewed_at']===null,'report reopening clears stale moderation state');$dummy=$s->startStore(10,3);$s->report($s->conversation($dummy,3),3,'other','dummy');$pdo->exec("insert into message_attachments(message_id,original_name,stored_name,mime_type,byte_size,width,height) values($message,'x.png','x.png','image/png',1,1,1)");$scoped=$pdo->query("select a.id from message_attachments a join conversation_messages m on m.id=a.message_id join message_reports r on r.conversation_id=m.conversation_id where r.id=$report")->fetchColumn();$wrong=$pdo->query("select a.id from message_attachments a join conversation_messages m on m.id=a.message_id join message_reports r on r.conversation_id=m.conversation_id where r.id=51")->fetchColumn();$participantAttachment=$s->attachmentForUser((int)$scoped,2);$otherAttachment=$s->attachmentForUser((int)$scoped,3);$adminAttachment=$s->attachmentForReportedConversation($report,(int)$scoped);$wrongAdminAttachment=$s->attachmentForReportedConversation(51,(int)$scoped);$check($report!==$product&&(int)$r['conversation_id']===$product&&$scoped!==false&&$wrong===false,'distinct report ID targets only its conversation for moderation and attachment scope');$check($participantAttachment!==null&&$otherAttachment===null,'production attachment authorization permits participants and denies unrelated users');$check($adminAttachment!==null&&$wrongAdminAttachment===null,'admin attachment authorization is scoped to the supplied reported conversation');
NotificationService::internalMessage(2,'seller',$message,'Buyer','/seller/messages/'.$product);EmailQueueService::queue('transactional','seller@example.test','You have a new Asset Moth message','internal_message',['name'=>'Seller'],"internal-message:$message:recipient:2");$check((int)$pdo->query("select count(*) from notifications where event_key='internal-message:$message:recipient:2'")->fetchColumn()===1&&(int)$pdo->query("select count(*) from email_messages where deduplication_key='internal-message:$message:recipient:2'")->fetchColumn()===1,'notification and transactional email keys deduplicate');
$check(!$s->canAccessConversation($c,3)&&$s->canAccessConversation($c,2),'production conversation authorization denies unrelated ID access and permits participants');$check((bool)$pdo->query('select id from message_conversations where buyer_user_id=1 or seller_user_id=1 limit 1')->fetchColumn(),'messaging history exists for account-deletion retention guard');
echo "PASS: disposable Phase 12.5 service/database behavior completed.\n";
}catch(Throwable $e){echo 'FAIL: integration exception: '.$e->getMessage()."\n";$fail++;}finally{try{$pdo->exec("use `$original`");$pdo->exec("drop database if exists `$fixture`");}catch(Throwable){}}exit($fail?1:0);
