<?php
require dirname(__DIR__).'/app/bootstrap.php';
use App\Services\SocialPublishingService;
use App\Services\ProductPublicationTransitionService;
use App\Services\CustomDesignPublicationTransitionService;

$failures=[];$check=function(bool $ok,string $message)use(&$failures){echo($ok?'PASS: ':'FAIL: ').$message."\n";if(!$ok)$failures[]=$message;};
$_ENV['META_APP_ID']='meta-client';$_ENV['META_APP_SECRET']='super-secret';$_ENV['META_GRAPH_API_VERSION']='v23.0';$_ENV['FACEBOOK_OAUTH_REDIRECT_URI']='https://market.test/seller/social/facebook/callback';$_ENV['INSTAGRAM_OAUTH_REDIRECT_URI']='https://market.test/seller/social/instagram/callback';
$calls=[];$transport=function($method,$url,$headers,$data,$form,$json)use(&$calls){$calls[]=compact('method','url','headers','data','form','json');if(str_ends_with($url,'/oauth/access_token'))return['access_token'=>'user-token','expires_in'=>3600];if(str_ends_with($url,'/me/accounts'))return isset($data['after'])?['data'=>[['id'=>'page-2','name'=>'Chosen Page','access_token'=>'page-token-2','instagram_business_account'=>['id'=>'ig-2']]]]:['data'=>[['id'=>'page-1','name'=>'First Page','access_token'=>'page-token-1','instagram_business_account'=>['id'=>'ig-1']]],'paging'=>['cursors'=>['after'=>'cursor-2'],'next'=>'https://graph.facebook.com/me/accounts?access_token=must-not-follow']];if(str_ends_with($url,'/ig-1'))return['id'=>'ig-1','username'=>'first_ig'];if(str_ends_with($url,'/ig-2'))return['id'=>'ig-2','username'=>'chosen_ig'];if(str_ends_with($url,'/boards'))return isset($data['bookmark'])?['items'=>[['id'=>'board-2','name'=>'Second board']]]:['items'=>[['id'=>'board-1','name'=>'First board']],'bookmark'=>'bookmark-2'];if(str_ends_with($url,'/media'))return['id'=>'container-1'];if(str_ends_with($url,'/media_publish'))return['id'=>'ig-post'];if(str_ends_with($url,'/photos'))return['post_id'=>'fb-post'];if(str_ends_with($url,'/pins'))return['id'=>'pin-1'];throw new RuntimeException('Unexpected fake request '.$url);};
$service=new SocialPublishingService($transport,fn()=>true);
$transitions=[['draft','approved',true],['pending_review','approved',true],['rejected','approved',true],['disabled','approved',true],['approved','approved',false],['published','published',false],['approved','published',false],['published','approved',false]];foreach($transitions as [$before,$after,$expected])$check(ProductPublicationTransitionService::shouldDispatch($before,$after)===$expected,"central transition decision $before -> $after");$dispatches=[];ProductPublicationTransitionService::dispatchAfterCommit(41,'approved','approved',function()use(&$dispatches){$dispatches[]='edit';});$check($dispatches===[],'ordinary approved-product edits do not dispatch.');
$check(CustomDesignPublicationTransitionService::shouldDispatch(false,true)&&!CustomDesignPublicationTransitionService::shouldDispatch(true,true)&&!CustomDesignPublicationTransitionService::shouldDispatch(true,false),'Custom Designs auto-post only on activation.');
$previewDispatches=[];$failedPreviewDispatch=CustomDesignPublicationTransitionService::dispatchAfterPreviewProcessing(51,false,true,1,function(int $id)use(&$previewDispatches){$previewDispatches[]=$id;});$successfulPreviewDispatch=CustomDesignPublicationTransitionService::dispatchAfterPreviewProcessing(52,false,true,0,function(int $id)use(&$previewDispatches){$previewDispatches[]=$id;});$activeEditDispatch=CustomDesignPublicationTransitionService::dispatchAfterPreviewProcessing(53,true,true,0,function(int $id)use(&$previewDispatches){$previewDispatches[]=$id;});$check(!$failedPreviewDispatch&&$successfulPreviewDispatch&&!$activeEditDispatch&&$previewDispatches===[52],'Custom Design preview regeneration failure suppresses activation auto-post while successful activation dispatches exactly once and active edits do not dispatch.');
$auth=$service->metaDestinations('facebook','oauth-code');
$check(count($auth['destinations'])===2&&$auth['destinations'][1]['id']==='page-2','Meta authorization returns every permitted Page for intentional selection.');
$check($service->selectedMetaDestination($auth,'page-2')['name']==='Chosen Page','The explicitly selected authorized Page is used instead of the first Page.');try{$service->selectedMetaDestination($auth,'attacker-page');$rejected=false;}catch(DomainException $e){$rejected=true;}$check($rejected,'A destination absent from provider-authorized results is rejected.');
$check($calls[0]['method']==='POST'&&!str_contains($calls[0]['url'],'super-secret')&&!str_contains($calls[0]['url'],'oauth-code'),'Meta app secret and authorization code are sent in the token POST body, not its URL.');
$accountsCall=array_values(array_filter($calls,fn($call)=>str_ends_with($call['url'],'/me/accounts')))[0]??null;$check($accountsCall&&!str_contains($accountsCall['url'],'user-token')&&in_array('Authorization: Bearer user-token',$accountsCall['headers'],true),'Meta user token is sent in an Authorization header, not a URL.');
$calls=[];$ig=$service->metaDestinations('instagram','oauth-code');$check(array_column($ig['destinations'],'id')===['ig-1','ig-2'],'Instagram discovery returns all eligible professional accounts.');
$check(!array_filter($calls,fn($c)=>str_contains($c['url'],'user-token')||str_contains($c['url'],'page-token')),'No Meta access token is placed in any generated request URL.');
$accountPages=array_values(array_filter($calls,fn($c)=>str_ends_with($c['url'],'/me/accounts')));$check(count($accountPages)===2&&($accountPages[1]['data']['after']??null)==='cursor-2'&&!array_filter($accountPages,fn($c)=>str_contains($c['url'],'access_token')),'Meta pagination uses the returned cursor through the safe request builder and never follows credential-bearing next URLs.');
$calls=[];$boards=$service->pinterestBoardsWithAccessToken('pinterest-token');$check(array_column($boards,'id')===['board-1','board-2']&&count($calls)===2&&($calls[1]['data']['bookmark']??null)==='bookmark-2'&&!array_filter($calls,fn($c)=>str_contains($c['url'],'pinterest-token')),'Pinterest pagination collects every board using bookmarks with the token only in Authorization headers.');
$authorizedBoards=[['id'=>'board-1','name'=>'First board']];try{$service->authorizedPinterestBoard($authorizedBoards,null,true);$missingBoard=false;}catch(DomainException $e){$missingBoard=true;}try{$service->authorizedPinterestBoard($authorizedBoards,'not-authorized',true);$badBoard=false;}catch(DomainException $e){$badBoard=true;}$validBoard=$service->authorizedPinterestBoard($authorizedBoards,'board-1',true);$check($missingBoard&&$badBoard&&($validBoard['id']??'')==='board-1','Pinterest auto-posting rejects missing/unauthorized boards and accepts an authorized board.');
$check(SocialPublishingService::validOAuthState(['state'=>'abc','expires'=>100],'abc',100)&&!SocialPublishingService::validOAuthState(['state'=>'abc','expires'=>99],'abc',100)&&!SocialPublishingService::validOAuthState(['state'=>'abc','expires'=>101],'wrong',100),'OAuth state accepts only a matching, unexpired value.');
$stale=[];foreach([[['status'=>'archived'],['id'=>1],'approved or published'],[['status'=>'approved'],null,'preview image']] as [$productState,$imageState,$expected]){try{$service->validatePostingEligibility($productState,$imageState);$clean=false;}catch(DomainException $e){$clean=str_contains($e->getMessage(),$expected);}$stale[]=$clean;}$check(!in_array(false,$stale,true),'Stale retries fail cleanly for an ineligible product and a removed original image.');
$disabled=new SocialPublishingService($transport,fn()=>false);try{$disabled->metaDestinations('facebook','code');$blocked=false;}catch(RuntimeException $e){$blocked=str_contains($e->getMessage(),'temporarily disabled');}$check($blocked,'An administratively disabled integration fails safely before a provider request.');
$check(!SocialPublishingService::shouldRevokeMeta(1),'Disconnecting Facebook while Instagram remains, or Instagram while Facebook remains, retains shared Meta permissions.');
$check(SocialPublishingService::shouldRevokeMeta(0),'The last remaining Meta connection may revoke provider-level permissions.');
$url='https://market.test/product/art';
foreach(['facebook'=>63206,'instagram'=>2200,'pinterest'=>500] as $platform=>$limit){$caption=$service->platformCaption($platform,str_repeat('x',70000)."\n$url\n$url",$url);$check(mb_strlen($caption)<=$limit,"$platform caption respects its payload limit");$check(substr_count($caption,$url)===($platform==='pinterest'?0:1),"$platform content does not duplicate the product URL");}
$send=new ReflectionMethod($service,'send');$send->setAccessible(true);$product=['title'=>'Artwork'];$connection=['external_account_id'=>'destination','pinterest_board_id'=>'board-7'];$credentials=['access_token'=>'provider-token'];
$calls=[];$send->invoke($service,'facebook',$connection,$credentials,$product,'https://market.test/image.jpg',$url,"Manual caption $url");$check($calls[0]['method']==='POST'&&str_ends_with($calls[0]['url'],'/photos')&&substr_count($calls[0]['data']['caption'],$url)===1&&!str_contains($calls[0]['url'],'provider-token'),'Facebook builds a token-safe photo request with one product URL.');
$calls=[];$send->invoke($service,'instagram',$connection,$credentials,$product,'https://market.test/image.jpg',$url,"Manual caption $url");$check(count($calls)===2&&str_ends_with($calls[0]['url'],'/media')&&str_ends_with($calls[1]['url'],'/media_publish')&&$calls[1]['data']['creation_id']==='container-1'&&substr_count($calls[0]['data']['caption'],$url)===1,'Instagram builds the media creation and publish requests with one product reference.');
$calls=[];$send->invoke($service,'pinterest',$connection,$credentials,$product,'https://market.test/image.jpg',$url,"Manual caption $url");$check($calls[0]['data']['board_id']==='board-7'&&$calls[0]['data']['link']===$url&&!str_contains($calls[0]['data']['description'],$url)&&mb_strlen($calls[0]['data']['description'])<=500,'Pinterest builds a board-scoped Pin with link separate from its bounded description.');
$missingIdCases=[
 ['facebook',fn()=>[], 'Facebook'],
 ['instagram',function($method,$requestUrl){return str_ends_with($requestUrl,'/media')?[]:['id'=>'unused'];},'Instagram container'],
 ['instagram',function($method,$requestUrl){return str_ends_with($requestUrl,'/media')?['id'=>'container']:[];},'Instagram publish'],
 ['pinterest',fn()=>[],'Pinterest'],
];
foreach($missingIdCases as [$platform,$fake,$label]){$missingService=new SocialPublishingService($fake,fn()=>true);$missingSend=new ReflectionMethod($missingService,'send');$missingSend->setAccessible(true);try{$missingSend->invoke($missingService,$platform,$connection,$credentials,$product,'https://market.test/image.jpg',$url,'Caption');$rejectedMissingId=false;}catch(ReflectionException $e){throw $e;}catch(Throwable $e){$rejectedMissingId=str_contains($e->getMessage(),'ID');}$check($rejectedMissingId,"$label response without its required provider ID fails safely");}
$controller=file_get_contents(dirname(__DIR__).'/app/Controllers/SocialPublishingController.php');$historyView=file_get_contents(dirname(__DIR__).'/app/Views/seller/social_publishing.php');$check(str_contains($controller,'left join products')&&str_contains($controller,'left join custom_design_services')&&str_contains($controller,'Deleted product #')&&str_contains($controller,'where l.designer_id=?')&&str_contains($historyView,'current_product_id')&&str_contains($historyView,'current_custom_service_id')&&str_contains($historyView,'Retry unavailable'),'Seller-scoped posting history retains both listing types and does not offer stale retries.');
$publishing=file_get_contents(dirname(__DIR__).'/app/Services/SocialPublishingService.php');$check(str_contains($publishing,"\$listingType.':'.\$listingId"),'Automatic idempotency keys include the listing type.');
$customService=file_get_contents(dirname(__DIR__).'/app/Services/CustomDesignService.php');$dispatchPosition=strpos($customService,'CustomDesignPublicationTransitionService::dispatchAfterPreviewProcessing');$check($dispatchPosition>strpos($customService,'WatermarkService::regenerateCustomDesignPreview')&&$dispatchPosition>strpos($customService,'foreach($remove as $old)')&&str_contains($customService,'$protectionFailures);'),'Custom Design automatic social dispatch receives the regeneration result only after preview regeneration and removal work finishes.');
$migration=file_get_contents(dirname(__DIR__).'/database/migrations/2026_09_23_phase_13_6_custom_design_social_posting.sql');$schema=file_get_contents(dirname(__DIR__).'/database/schema.sql');$identityCheck='social_post_listing_identity_chk';$check(str_contains($migration,$identityCheck)&&str_contains($schema,$identityCheck),'Migration and canonical schema enforce exactly one social-post listing identity.');
if($failures){fwrite(STDERR,implode("\n",$failures)."\n");exit(1);}echo "Phase 13.6 local request-building tests passed; no external delivery was attempted.\n";
