<?php
require dirname(__DIR__).'/app/bootstrap.php';
use App\Core\Database as DB;use App\Services\LicenseService;
$fail=0;$check=function(bool $ok,string $name)use(&$fail){echo($ok?'PASS':'FAIL').": $name\n";if(!$ok)$fail++;};
try{$pdo=DB::pdo();}catch(Throwable $e){echo "SKIP: disposable MariaDB unavailable: {$e->getMessage()}\n";exit(77);}if((getenv('PHASE121_ALLOW_FIXTURE')?:'')!=='1'){echo "SKIP: set PHASE121_ALLOW_FIXTURE=1 with disposable-database privileges.\n";exit(77);}
$original=(string)$pdo->query('select database()')->fetchColumn();$fixture='phase121_fixture_'.bin2hex(random_bytes(4));$pdo->exec("create database `$fixture` character set utf8mb4 collate utf8mb4_unicode_ci");$pdo->exec("use `$fixture`");
try{
$pdo->exec("create table users(id bigint primary key auto_increment,name varchar(120),email varchar(190),password_hash varchar(255),role varchar(20),status varchar(20) default 'active');
create table designers(id bigint primary key auto_increment,user_id bigint unique,display_name varchar(120),store_slug varchar(140),bio text,status varchar(30) default 'approved',stripe_connect_account_id varchar(190),stripe_details_submitted tinyint default 0,stripe_payouts_enabled tinyint default 0,receipt_note varchar(500),receipt_image_path varchar(255));
create table products(id bigint primary key auto_increment,designer_id bigint,category_id bigint,title varchar(190),slug varchar(210),short_description text,description text,price decimal(10,2),fulfillment_type varchar(40) default 'downloadable',manual_delivery_instructions text,file_types varchar(255),commercial_license_enabled tinyint default 0,commercial_license_price decimal(10,2) default 0,pod_allowed tinyint default 0,digital_resale_prohibited tinyint default 1,ai_disclosure varchar(80),is_hand_drawn tinyint default 0,seo_title varchar(70),seo_description varchar(170),status varchar(40),rejection_reason text,created_at timestamp default current_timestamp,updated_at timestamp default current_timestamp on update current_timestamp);
create table product_images(id bigint primary key auto_increment,product_id bigint,image_path varchar(255),sort_order int default 0);
create table license_types(id bigint primary key auto_increment,license_key varchar(80) not null unique,name varchar(120),description text,sort_order int,is_active tinyint default 1,created_at timestamp default current_timestamp,updated_at timestamp default current_timestamp on update current_timestamp);
create table product_license_types(id bigint primary key auto_increment,product_id bigint,license_type_id bigint,is_enabled tinyint,is_default tinyint,price decimal(10,2),custom_name varchar(120),description text,sort_order int,updated_at timestamp default current_timestamp on update current_timestamp,unique(product_id,license_type_id));
create table cart_items(id bigint primary key auto_increment,user_id bigint,product_id bigint,license_type varchar(80),quantity int default 1,price_snapshot decimal(10,2),license_price_snapshot decimal(10,2),total_snapshot decimal(10,2),fulfillment_type_snapshot varchar(40),created_at timestamp default current_timestamp,unique(user_id,product_id,license_type));
create table orders(id bigint primary key auto_increment,user_id bigint,status varchar(40),payment_processor varchar(40),payment_mode varchar(40),payment_provider varchar(40),payment_status varchar(40),subtotal decimal(10,2),tax_amount decimal(10,2),tax_provider varchar(40),tax_status varchar(40),tax_liability_owner varchar(40),tax_snapshot json,tax_calculation_id varchar(190),tax_transaction_status varchar(40),billing_address_snapshot json,credits_applied decimal(10,2),credit_reserved decimal(10,2) default 0,credit_payment_status varchar(40) default 'none',coupon_discount decimal(10,2),coupon_id bigint,coupon_code varchar(80),coupon_snapshot json,total decimal(10,2),fulfillment_status varchar(40),phase9_foundation_order tinyint,stripe_currency varchar(10),stripe_amount_total bigint,stripe_paid_amount decimal(10,2),platform_commission_total decimal(10,2),stripe_checkout_session_id varchar(190),stripe_payment_status varchar(40),created_at timestamp default current_timestamp);
create table order_items(id bigint primary key auto_increment,order_id bigint,product_id bigint,product_title varchar(190),product_slug varchar(210),product_image varchar(255),designer_id bigint,seller_name varchar(120),license_type varchar(80),license_name varchar(120),license_price decimal(10,2),license_description text,license_snapshot json,fulfillment_type varchar(40),delivery_instructions_snapshot text,buyer_google_drive_email varchar(190),manual_delivery_status varchar(40),unit_price decimal(10,2),commercial_license_price decimal(10,2),total_price decimal(10,2),commission_rate decimal(5,4),purchased_file_version bigint,seller_receipt_note_snapshot varchar(500),seller_receipt_image_path_snapshot varchar(255),coupon_id bigint,coupon_code varchar(80),coupon_discount decimal(10,2) default 0,created_at timestamp default current_timestamp);
create table seller_earnings(id bigint primary key auto_increment,order_id bigint,product_id bigint,designer_id bigint,buyer_id bigint,gross_sale decimal(10,2),marketplace_commission decimal(10,2),seller_earning decimal(10,2),status varchar(40));
create table marketplace_credits(user_id bigint primary key,total_balance decimal(12,2) default 0,reserved_balance decimal(12,2) default 0);");
$pdo->exec("insert into license_types(license_key,name,description,sort_order,is_active) values('personal','Personal','Personal use.',10,1),('pod','POD','POD use.',40,1)");$migration=file_get_contents(dirname(__DIR__).'/database/migrations/2026_08_10_phase_12_1_digital_product_license.sql');$pdo->exec($migration);$pdo->exec($migration);$check((int)$pdo->query("select count(*) from license_types where license_key='digital-product'")->fetchColumn()===1,'actual migration is repeatable');
$pdo->exec("insert into users values(1,'Seller One','seller1@test','x','designer','active'),(2,'Seller Two','seller2@test','x','designer','active'),(3,'Buyer','buyer@test','x','buyer','active'),(4,'Admin','admin@test','x','admin','active');insert into designers(id,user_id,display_name,store_slug,bio,status,stripe_connect_account_id,stripe_details_submitted,stripe_payouts_enabled) values(1,1,'Seller One','seller-one','Ready','approved','acct_1',1,1),(2,2,'Seller Two','seller-two','Ready','approved','acct_2',1,1);insert into products(id,designer_id,title,slug,price,status,ai_disclosure) values(1,1,'Free Asset','free-asset',20,'approved','No AI Used'),(2,2,'Paid Asset','paid-asset',30,'approved','No AI Used');insert into marketplace_credits values(3,0,0)");
$configure=function(int $productId,string $price,bool $enabled=true)use($check){$post=['license_enabled'=>['personal'=>1],'license_price'=>[]];if($enabled){$post['license_enabled']['digital-product']=1;$post['license_price']['digital-product']=$price;}[$rows,$errors]=LicenseService::normalizePosted([], $post);$check(!$errors,"seller configuration validates Digital Product price $price");LicenseService::syncProductLicenses($productId,$rows);};
$configure(1,'0.00');$free=LicenseService::productLicenses(['id'=>1]);$check(array_column($free,'license_key')===['personal','digital-product']&&LicenseService::priceTotal($free)===0.0,'seller service enables owned product at zero');$configure(1,'12.50');$check(LicenseService::priceTotal(LicenseService::productLicenses(['id'=>1]))===12.5,'seller service updates paid price');$configure(1,'0.00');$configure(2,'7.25');
$pdo->exec("insert into product_license_types(product_id,license_type_id,is_enabled,is_default,price,description,sort_order) select 1,id,1,0,4.25,description,sort_order from license_types where license_key='pod'");
$worker=dirname(__DIR__).'/tests/helpers/Phase121WorkflowProbe.php';$env=array_merge($_ENV,['DB_NAME'=>$fixture,'STRIPE_SECRET_KEY'=>'sk_test_phase121']);$run=function(array $args)use($worker,$env){$pipes=[];$p=proc_open(array_merge([PHP_BINARY,$worker],$args),[1=>['pipe','w'],2=>['pipe','w']],$pipes,dirname(__DIR__),$env);$out=stream_get_contents($pipes[1]).stream_get_contents($pipes[2]);fclose($pipes[1]);fclose($pipes[2]);return [proc_close($p),$out];};
$run(['add','3','1','personal','digital-product']);$cart=$pdo->query('select * from cart_items where user_id=3 and product_id=1')->fetch();$check($cart&&$cart['license_type']==='personal,digital-product'&&(float)$cart['license_price_snapshot']===0.0,'CartController add persists normalized free Digital Product selection');[, $resolvedOut]=$run(['resolve-cart','3','0']);$resolved=json_decode($resolvedOut,true);$check(($resolved['items'][0]['license_key']??'')==='personal,digital-product'&&(float)($resolved['items'][0]['license_price']??-1)===0.0,'CartController resolves stored free selection at zero');
$run(['checkout','3','0','9999.99']);$freeItem=$pdo->query('select * from order_items where product_id=1 order by id desc limit 1')->fetch();$freeSnapshot=json_decode($freeItem['license_snapshot']??'[]',true);$check($freeItem&&$freeItem['license_type']==='personal,digital-product'&&(float)$freeItem['license_price']===0.0&&array_column($freeSnapshot,'key')===['personal','digital-product'],'CartController checkout stores free normalized key, name, description, zero price, and full snapshot');
$run(['add','3','2','personal','digital-product']);$run(['checkout','3','0','0.01']);$paidItem=$pdo->query('select * from order_items where product_id=2 order by id desc limit 1')->fetch();$check($paidItem&&(float)$paidItem['license_price']===7.25&&(float)$paidItem['total_price']===37.25,'paid checkout ignores manipulated client price and snapshots seller price');
$run(['add','3','1','personal','digital-product','pod']);$run(['add','3','2','personal','digital-product']);$run(['checkout','3','0']);$multiOrder=(int)$pdo->query('select max(id) from orders')->fetchColumn();$multiItems=$pdo->query("select product_id,license_type,license_price,license_snapshot from order_items where order_id=$multiOrder order by product_id")->fetchAll();$check(count($multiItems)===2&&$multiItems[0]['license_type']==='personal,digital-product,pod'&&(float)$multiItems[0]['license_price']===4.25&&$multiItems[1]['license_type']==='personal,digital-product'&&(float)$multiItems[1]['license_price']===7.25,'multi-item CartController checkout keeps independent license collections and aggregate prices attached to each item');
$run(['add','3','1','personal','digital-product']);$configure(1,'0.00',false);[, $staleOut]=$run(['resolve-cart','3','0']);$stale=json_decode($staleOut,true);$check(!empty($stale['items'][0]['license_invalid'])&&$pdo->query('select license_type from cart_items where user_id=3 and product_id=1')->fetchColumn()==='personal,digital-product','real stored cart becomes invalid after seller disables Digital Product');
[, $foreignOut]=$run(['seller-other-product','1','2']);$check(str_contains($foreignOut,'<h1>404</h1>'),'SellerController rejects a POST mutation attempt against another seller product');$configure(2,'0.00',false);$check(LicenseService::purchasableLicenses(2,['digital-product'])===[]&&(float)$paidItem['license_price']===7.25,'completed paid snapshot remains unchanged after seller disables current license');
$order=['id'=>$paidItem['order_id'],'subtotal'=>37.25,'total'=>37.25,'status'=>'paid','payment_status'=>'paid','created_at'=>'2026-08-10','credit_payment_status'=>'none'];$item=$paidItem+['title'=>'Paid Asset','slug'=>'paid-asset','designer_name'=>'Seller Two','designer_email'=>'seller2@test','buyer_name'=>'Buyer','buyer_email'=>'buyer@test','order_status'=>'paid','order_created'=>'2026-08-10','file_id'=>null,'preview_image'=>null,'file_available'=>false,'download_expires_at'=>null,'download_count'=>0,'seller_earning'=>30,'commission_amount'=>7.25,'ledger_payout_status'=>'pending','fulfillment_type'=>'downloadable'];$render=function($file,$vars){extract($vars);ob_start();include $file;return ob_get_clean();};$buyer=$render(dirname(__DIR__).'/app/Views/buyer/order.php',['order'=>$order,'items'=>[$item],'sellerGroups'=>[['seller_name'=>'Seller Two','receipt_image_path'=>null,'receipt_note'=>null,'items'=>[$item]]]]);$seller=$render(dirname(__DIR__).'/app/Views/seller/order_item.php',['item'=>$item]);$admin=$render(dirname(__DIR__).'/app/Views/admin/order_detail.php',['order'=>$order+['buyer_name'=>'Buyer','buyer_email'=>'buyer@test'],'items'=>[$item],'transactions'=>[],'events'=>[]]);foreach(['buyer'=>$buyer,'seller'=>$seller,'admin'=>$admin] as $role=>$html)$check(str_contains($html,'Digital Product License')&&str_contains($html,'original purchased file'),"$role order view renders saved order-item license name and description");$check(str_contains($seller,'$7.25'),'seller order view renders saved license add-on price');
}catch(Throwable $e){echo 'FAIL: integration exception: '.$e->getMessage()."\n";$fail++;}finally{try{$pdo->exec("use `$original`");$pdo->exec("drop database if exists `$fixture`");}catch(Throwable){}}exit($fail?1:0);
