<?php
require dirname(__DIR__).'/app/bootstrap.php';
use App\Services\SellerReceiptService;
$fail=0;$check=function(bool $ok,string $name)use(&$fail){echo($ok?'PASS':'FAIL').": $name\n";if(!$ok)$fail++;};$root=dirname(__DIR__);$source=fn($f)=>file_get_contents($root.'/'.$f);
$service=$source('app/Services/MessagingService.php');$controller=$source('app/Controllers/MessagingController.php');$admin=$source('app/Controllers/AdminController.php');$view=$source('app/Views/admin/message_reports.php');$schema=$source('database/migrations/2026_09_04_phase_12_5_internal_messaging.sql');
$check(str_contains($schema,'context_label VARCHAR(190) NOT NULL')&&str_contains($service,'oi.product_title')&&!str_contains($service,'p.title product_title'),'conversation context is snapshotted instead of rendered from mutable product data');
$thread=$source('app/Views/messages/thread.php');$email=$source('app/Views/emails/internal_message.php');$check(str_contains($service,"'Product: '")&&str_contains($service,"'Storefront: '")&&str_contains($service,"'Purchased product: '")&&str_contains($thread,'Context:')&&!str_contains($thread,'Product: <?=H::e(')&&str_contains($email,"['context']"),'product, storefront, and order snapshots render through generic type-aware context wording');
$check(str_contains($service,'c.last_message_at is not null')&&str_contains($source('app/Views/messages/index.php'),'No messages yet'),'empty compose rows are excluded and are not mislabeled as attachments');
$check(str_contains($controller,'r.id report_id,r.conversation_id')&&str_contains($controller,'$conversation[\'id\']=$detail[\'conversation_id\']')&&substr_count($view,'$detail[\'report_id\']')>=3,'admin report and conversation identifiers are explicit and correctly routed');
$check(str_contains($view,'$detail[\'status\']===$status?\'selected\'')&&str_contains($controller,'in_array($status,[\'open\',\'reviewing\',\'resolved\',\'dismissed\']'),'moderation preserves the deliberately selected current status');
$check(str_contains($service,'moderator_user_id=null,moderator_notes=null,reviewed_at=null'),'reopening a report clears stale moderation metadata');
foreach(['is_uploaded_file($tmp)','UPLOAD_ERR_OK','sourceDimensionsAllowed($width,$height)','hasExactImageContainer($bytes,$mime)','imagecreatefromstring($bytes)'] as $token)$check(str_contains($service,$token),"attachment production guard: $token");
$pngChunk=fn($type,$data)=>pack('N',strlen($data)).$type.$data.hash('crc32b',$type.$data,true);$png="\x89PNG\r\n\x1a\n".$pngChunk('IHDR',pack('NNCCCCC',1,1,8,6,0,0,0)).$pngChunk('IEND','');$webp='RIFF'.pack('V',4).'WEBP';$jpeg="\xFF\xD8\xFF\xD9";
$check(SellerReceiptService::hasExactImageContainer($png,'image/png')&&!SellerReceiptService::hasExactImageContainer($png.'payload','image/png'),'PNG IEND/CRC parser rejects trailing payloads');$check(SellerReceiptService::hasExactImageContainer($webp,'image/webp')&&!SellerReceiptService::hasExactImageContainer($webp.'x','image/webp'),'WEBP parser enforces RIFF length');$check(SellerReceiptService::hasExactImageContainer($jpeg,'image/jpeg')&&!SellerReceiptService::hasExactImageContainer($jpeg.'x','image/jpeg'),'JPEG parser requires parsed EOI at exact end');
$check(str_contains($service,'update notifications n join conversation_messages')&&str_contains($service,'m.conversation_id=?'),'thread reads synchronize only matching internal-message notifications');
$check(str_contains($source('app/Services/NotificationService.php'),'$recipientSide===\'seller\'?\'designer\':\'buyer\''),'notification audience follows authoritative conversation side');
$check(str_contains($admin,'private messaging history that must be retained')&&str_contains($admin,'message_conversations')&&str_contains($admin,'conversation_messages')&&str_contains($admin,'message_reports'),'permanent deletion blocks retained messaging history before deletion');
$buyer=$source('app/Views/buyer/order.php');$seller=$source('app/Views/seller/order_item.php');$check(str_contains($buyer,"['paid','partially_refunded']")&&str_contains($seller,"['paid','partially_refunded']"),'order messaging controls match backend payment eligibility');
if($fail)exit(1);echo "PASS: Phase 12.5 static security contracts and pure container validators completed (database behavior is a separate opt-in suite).\n";
