<?php
if(($_ENV['APP_ENV']??getenv('APP_ENV')?:'')!=='test'){fwrite(STDOUT,"SKIP: APP_ENV is not exactly test; no database connection was attempted.\n");exit(0);}
require dirname(__DIR__).'/app/bootstrap.php';
use App\Core\Database as DB;
use App\Services\ProductPublicationTransitionService;
use App\Services\SocialCredentialCipher;
use App\Services\SocialPublishingService;
try{$pdo=DB::pdo();}catch(Throwable $e){fwrite(STDOUT,"SKIP: APP_ENV=test, but the disposable migrated test database is unavailable.\n");exit(0);}
if(getenv('RUN_DISPOSABLE_DB_TESTS')!=='1'){fwrite(STDOUT,"SKIP: APP_ENV=test but RUN_DISPOSABLE_DB_TESTS is not 1; no fixtures were written.\n");exit(0);}
require __DIR__.'/Support/Phase136ApprovalWorkflowDatabaseScenarios.php';

$failures=[];$check=function(bool $ok,string $message)use(&$failures){echo($ok?'PASS: ':'FAIL: ').$message."\n";if(!$ok)$failures[]=$message;};
$token=bin2hex(random_bytes(6));$_ENV['APP_URL']='https://market.test';$_ENV['SOCIAL_CREDENTIAL_ENCRYPTION_KEY']=base64_encode(random_bytes(SODIUM_CRYPTO_SECRETBOX_KEYBYTES));
$providerFails=false;$calls=[];SocialPublishingService::setTestTransport(function($method,$url,$headers,$data)use(&$providerFails,&$calls){$calls[]=compact('method','url','headers','data');if($providerFails)throw new RuntimeException('Fake provider permission failure.');return['post_id'=>'fake-post-'.count($calls),'id'=>'fake-id-'.count($calls)];});
try{
 runPhase136ApprovalWorkflowScenarios($pdo,$check);
 $pdo->beginTransaction();
 foreach(['social_platform_integrations','seller_social_connections','social_post_logs'] as $table)$check((bool)DB::row('show tables like ?',[$table]),"migrated table $table exists");
 DB::exec('insert into users(name,email,password_hash,role,status) values(?,?,?,?,"active")',['Phase136 Seller','phase136-'.$token.'@example.test','x','designer']);$user1=(int)DB::id();
 DB::exec('insert into users(name,email,password_hash,role,status) values(?,?,?,?,"active")',['Other Seller','phase136-other-'.$token.'@example.test','x','designer']);$user2=(int)DB::id();
 DB::exec('insert into designers(user_id,display_name,store_slug,status) values(?,?,?,"approved")',[$user1,'Phase 136 Shop','phase136-'.$token]);$seller1=(int)DB::id();
 DB::exec('insert into designers(user_id,display_name,store_slug,status) values(?,?,?,"approved")',[$user2,'Other Shop','phase136-other-'.$token]);$seller2=(int)DB::id();
 $makeProduct=function(int $seller,string $status,string $suffix)use($token){DB::exec('insert into products(designer_id,title,slug,description,price,ai_disclosure,status) values(?,?,?,?,?,"No AI Used",?)',[$seller,'Product '.$suffix,'phase136-'.$token.'-'.$suffix,'Description',10,$status]);$id=(int)DB::id();DB::exec('insert into product_images(product_id,image_path,sort_order) values(?,?,0)',[$id,'/uploads/phase136-'.$suffix.'.jpg']);return[$id,(int)DB::id()];};
 [$product,$image]=$makeProduct($seller1,'approved','eligible');[$otherProduct,$otherImage]=$makeProduct($seller2,'approved','other');[$ineligible,$ineligibleImage]=$makeProduct($seller1,'draft','draft');
 $encrypted=SocialCredentialCipher::encrypt(['access_token'=>'fake-page-token','user_access_token'=>'fake-user-token']);DB::exec('insert into seller_social_connections(designer_id,platform,external_account_id,external_account_name,encrypted_credentials,connection_status,auto_post_enabled,connected_at) values(?,"facebook","page-fixture","Fixture Page",?,"connected",1,now())',[$seller1,$encrypted]);
 $pinterestCredentials=SocialCredentialCipher::encrypt(['access_token'=>'stale-token']);DB::exec('insert into seller_social_connections(designer_id,platform,external_account_id,external_account_name,encrypted_credentials,connection_status,auto_post_enabled,pinterest_board_id,pinterest_board_name,connected_at) values(?,"pinterest","old-account","Old Pinterest",?,"connected",1,"stale-board","Stale board",now())',[$seller1,$pinterestCredentials]);$_ENV['PINTEREST_APP_ID']='test-pinterest';$_ENV['PINTEREST_APP_SECRET']='test-secret';$_ENV['PINTEREST_OAUTH_REDIRECT_URI']='https://market.test/seller/social/pinterest/callback';$pinterestService=new SocialPublishingService(function($method,$url){if(str_ends_with($url,'/oauth/token'))return['access_token'=>'fresh-token'];if(str_ends_with($url,'/user_account'))return['id'=>'fresh-account','username'=>'fresh'];throw new RuntimeException('Unexpected Pinterest reconnect request.');},fn()=>true);$pinterestService->connectPinterestFromCode($seller1,'test-code');$reconnected=DB::row('select auto_post_enabled,pinterest_board_id from seller_social_connections where designer_id=? and platform="pinterest"',[$seller1]);$check((int)$reconnected['auto_post_enabled']===0&&$reconnected['pinterest_board_id']===null,'Pinterest reconnect clears stale board selection and disables automatic posting');
 DB::exec('update social_platform_integrations set is_enabled=1,disabled_reason=null where platform="facebook"');$service=new SocialPublishingService();
 $manual=$service->publish($seller1,$product,'facebook',$image,'Manual caption');$check($manual['status']==='succeeded'&&(int)(DB::row('select count(*) c from social_post_logs where designer_id=? and product_id=? and trigger_type="manual"',[$seller1,$product])['c']??0)===1,'owned eligible product and preview persist a successful fake-provider manual attempt');
 $missingId=(new SocialPublishingService(fn()=>[]))->publish($seller1,$product,'facebook',$image,'Missing ID');$missingIdRow=DB::row('select status,error_message from social_post_logs where id=?',[$missingId['id']]);$check(($missingIdRow['status']??'')==='failed'&&str_contains((string)($missingIdRow['error_message']??''),'post ID'),'a provider 2xx response missing its required ID persists as failed');
 try{$service->publish($seller1,$otherProduct,'facebook',$otherImage,'No');$blocked=false;}catch(DomainException $e){$blocked=true;}$check($blocked,'another seller product cannot be posted');
 $wrong=$service->publish($seller1,$product,'facebook',$ineligibleImage,'Wrong image');$check($wrong['status']==='failed','an image from another product is rejected and logged failed');
 $badStatus=$service->publish($seller1,$ineligible,'facebook',$ineligibleImage,'Draft');$check($badStatus['status']==='failed','an ineligible product status is rejected and logged failed');
 DB::exec('update products set status="draft" where id=?',[$product]);DB::exec('update products set status="approved" where id=?',[$product]);ProductPublicationTransitionService::dispatchAfterCommit($product,'draft','approved');ProductPublicationTransitionService::dispatchAfterCommit($product,'approved','approved');ProductPublicationTransitionService::dispatchAfterCommit($product,'pending_review','approved');$autoCount=(int)(DB::row('select count(*) c from social_post_logs where product_id=? and platform="facebook" and trigger_type="automatic"',[$product])['c']??0);$check($autoCount===1,'genuine approval dispatches once and repeated/ordinary dispatches do not duplicate the automatic attempt');
 $providerFails=true;$failed=$service->publish($seller1,$product,'facebook',$image,'Failure');$providerFails=false;$retry=$service->publish($seller1,$product,'facebook',$image,'Failure','retry',(int)$failed['id']);$retryRow=DB::row('select retry_of_id,status from social_post_logs where id=?',[$retry['id']]);$check($failed['status']==='failed'&&$retry['status']==='succeeded'&&(int)$retryRow['retry_of_id']===(int)$failed['id'],'failed attempts persist and retries create separately linked rows');
 [$failedAutoProduct,$failedAutoImage]=$makeProduct($seller1,'approved','auto-fail');$providerFails=true;ProductPublicationTransitionService::dispatchAfterCommit($failedAutoProduct,'pending_review','approved');$providerFails=false;$autoFailure=DB::row('select id,status from social_post_logs where product_id=? and trigger_type="automatic"',[$failedAutoProduct]);$notification=DB::row('select id from notifications where user_id=? and event_key=?',[$user1,'social-post-failed:'.($autoFailure['id']??0)]);$check(($autoFailure['status']??'')==='failed'&&$notification!==null,'failed automatic attempts persist and create a seller notification');
 DB::exec('update social_platform_integrations set is_enabled=0,disabled_reason="fixture outage" where platform="facebook"');$disabled=$service->publish($seller1,$product,'facebook',$image,'Disabled');$check($disabled['status']==='failed','persisted admin kill switch prevents provider publication');DB::exec('update social_platform_integrations set is_enabled=1,disabled_reason=null where platform="facebook"');
 DB::exec('delete from product_images where product_id=?',[$product]);DB::exec('delete from products where id=?',[$product]);$history=DB::row('select coalesce(p.title,concat("Deleted product #",l.product_id)) product_title,p.id current_product_id from social_post_logs l left join products p on p.id=l.product_id where l.designer_id=? and l.product_id=? order by l.id limit 1',[$seller1,$product]);$check(($history['product_title']??'')==='Deleted product #'.$product&&$history['current_product_id']===null,'seller-scoped history retains a deleted-product fallback label');try{$service->publish($seller1,$product,'facebook',$image,'Retry','retry',(int)$failed['id']);$deletedBlocked=false;}catch(DomainException $e){$deletedBlocked=true;}$check($deletedBlocked,'deleted products cannot be retried');$stale=$service->publish($seller1,$ineligible,'facebook',$ineligibleImage,'Retry','retry',(int)$badStatus['id']);$check($stale['status']==='failed','ineligible products cannot be retried and fail without an application error');
 if($failures)throw new RuntimeException(implode("\n",$failures));echo "Phase 13.6 disposable database behavioral checks passed with fake provider transport; no external delivery was attempted.\n";
}catch(Throwable $e){fwrite(STDERR,"Phase 13.6 database test failed: ".$e->getMessage()."\n");$exit=1;}finally{if($pdo->inTransaction())$pdo->rollBack();SocialPublishingService::setTestTransport(null);}
exit($exit??0);
