<?php
require dirname(__DIR__).'/app/bootstrap.php';
use App\Core\Database as DB;
use App\Services\PromoService;
use App\Services\EmailQueueService;

if(($_ENV['RUN_DISPOSABLE_DB_TESTS']??getenv('RUN_DISPOSABLE_DB_TESTS')?:'')!=='1'){echo "SKIP/UNEXECUTED: set RUN_DISPOSABLE_DB_TESTS=1 with disposable MariaDB credentials; this suite creates and drops an isolated database.\n";exit(0);}
try{$pdo=DB::pdo();}catch(Throwable $e){echo 'SKIP/UNEXECUTED: disposable MariaDB unavailable: '.$e->getMessage()."\n";exit(0);}
$base=(string)$pdo->query('select database()')->fetchColumn();$db='phase13_'.bin2hex(random_bytes(5));$failures=[];
$check=function(bool $ok,string $message)use(&$failures):void{echo($ok?'PASS: ':'FAIL: ').$message."\n";if(!$ok)$failures[]=$message;};
$pdo->exec("create database `$db` character set utf8mb4 collate utf8mb4_unicode_ci");$pdo->exec("use `$db`");
try{
    $pdo->exec("create table users(id bigint primary key,name varchar(120),email varchar(190),role varchar(30),status varchar(30));
      create table designers(id bigint primary key,user_id bigint,display_name varchar(120),store_slug varchar(120),banner_path varchar(255),avatar_path varchar(255),bio text null,average_rating decimal(3,2) null default 0.00,status varchar(30));
      create table categories(id bigint primary key auto_increment,name varchar(120),slug varchar(120),description text,is_active tinyint default 1,sort_order int default 0) engine=InnoDB;
      create table products(id bigint primary key auto_increment,designer_id bigint,category_id bigint,title varchar(190),slug varchar(190),price decimal(10,2),status varchar(40),created_at timestamp default current_timestamp) engine=InnoDB;
      create table product_images(id bigint primary key auto_increment,product_id bigint,image_path varchar(255),sort_order int default 0);
      create table notifications(id bigint primary key auto_increment,user_id bigint,notification_type varchar(80),audience varchar(30),title varchar(190),message text,action_url varchar(500),event_key varchar(190) unique,read_at timestamp null,created_at timestamp default current_timestamp);
      create table email_preferences(user_id bigint primary key,marketing_opt_in tinyint default 1,weekly_emails tinyint default 1,monthly_emails tinyint default 0,favorite_shop_emails tinyint default 0,marketing_opted_out_at timestamp null,unsubscribe_nonce char(64));
      create table email_messages(id bigint primary key auto_increment,classification enum('transactional','marketing') not null,recipient_email varchar(190) not null,recipient_name varchar(120),subject varchar(190) not null,template varchar(80) not null,template_data json not null,campaign_id bigint null,campaign_recipient_id bigint null,waitlist_entry_id bigint null,deduplication_key varchar(190) not null,status enum('pending','processing','sent','failed','cancelled') not null default 'pending',attempt_count tinyint unsigned not null default 0,next_attempt_at timestamp null,last_error varchar(500),created_at timestamp default current_timestamp,claimed_at timestamp null,sent_at timestamp null,updated_at timestamp default current_timestamp on update current_timestamp,unique key uq_email_dedupe(deduplication_key)) engine=InnoDB;
      create table email_digest_content_claims(id bigint primary key auto_increment,user_id bigint not null,product_id bigint not null,preference_category enum('favorite_shop','weekly','monthly') not null,period_start date not null,period_end date not null,email_message_id bigint not null,created_at timestamp default current_timestamp,unique key uq_digest_claim_message_product(email_message_id,product_id));
      create table ads(id bigint primary key auto_increment,product_id bigint null,designer_id bigint null,placement varchar(80) null,start_date date null,end_date date null,status enum('draft','active','paused','ended') default 'draft',impressions int default 0,clicks int default 0,created_at timestamp default current_timestamp,updated_at timestamp default current_timestamp on update current_timestamp) engine=InnoDB;
      insert into users values(1,'Seller One','one@example.test','designer','active'),(2,'Seller Two','two@example.test','designer','active');
      insert into email_preferences(user_id,unsubscribe_nonce) values(1,repeat('a',64));
      insert into designers values(10,1,'Seller One','seller-one','/banner-one.webp','/avatar-one.webp','Seller One bio',4.75,'approved'),(20,2,'Seller Two','seller-two',null,'/avatar-two.webp',null,0.00,'approved');
      insert into categories(id,name,slug,is_active,sort_order) values(1,'Graphics','graphics',1,1),(2,'Templates','templates',1,2),(3,'Disabled','disabled',0,3);
      insert into products(id,designer_id,category_id,title,slug,price,status) values(100,10,1,'One Product','one-product',9.50,'approved'),(101,10,1,'Published Product','published-product',8.00,'published'),(200,20,1,'Other Product','other-product',12.00,'approved'),(201,20,1,'Disabled Product','disabled-product',3.00,'disabled');
      insert into product_images(product_id,image_path,sort_order) values(100,'/one.webp',0),(101,'/published.webp',0),(200,'/other.webp',0);
      insert into ads(product_id,designer_id,placement,status,impressions) values(null,null,'unsupported-legacy-placement','active',999);");
    $pdo->exec(file_get_contents(dirname(__DIR__).'/database/migrations/2026_09_16_phase_13_sponsored_promos.sql'));
    $legacy=$pdo->query('select placement,status from ads where id=1')->fetch(PDO::FETCH_ASSOC);
    $check($legacy['placement']==='marketplace'&&$legacy['status']==='ended','migration preserves and safely normalizes unsupported legacy ads');
    $expected=['marketplace'=>[1=>300,3=>800,7=>1500,14=>2500],'homepage'=>[1=>500,3=>1200,7=>2500,14=>4000],'category'=>[1=>400,3=>1000,7=>2000,14=>3500],'weekly_email'=>[1=>800,2=>1500,4=>2500,6=>3500]];
    $actual=[];foreach(DB::rows('select placement,duration_value,price_cents from promo_packages') as $p)$actual[$p['placement']][(int)$p['duration_value']]=(int)$p['price_cents'];$check($actual==$expected,'migration seeds all 16 approved package prices');
    $precision=(int)$pdo->query("select datetime_precision from information_schema.columns where table_schema=database() and table_name='ads' and column_name='last_served_at'")->fetchColumn();$check($precision===6,'migration gives last_served_at microsecond precision');

    $seller=PromoService::seller(1);$market=(int)DB::row('select id from promo_packages where placement="marketplace" and duration_value=1')['id'];$sellerProducts=array_column(PromoService::products(10),'id');$check(in_array(100,$sellerProducts,true)&&!in_array(101,$sellerProducts,true),'seller promotion options include approved products and exclude published products');$categoryPackage=(int)DB::row('select id from promo_packages where placement="category" and duration_value=1')['id'];$categoryProduct=PromoService::createPending($seller,'product',100,$categoryPackage,2);$categoryShop=PromoService::createPending($seller,'shop',null,$categoryPackage,2);$check($categoryProduct&&$categoryShop,'category option allows eligible product or shop in any active category');try{PromoService::createPending($seller,'shop',null,$categoryPackage,3);$inactiveCategory=false;}catch(InvalidArgumentException $e){$inactiveCategory=true;}$check($inactiveCategory,'inactive category remains rejected');
    try{PromoService::createPending($seller,'product',200,$market);$owned=false;}catch(InvalidArgumentException $e){$owned=true;}$check($owned,'seller cannot promote another seller product');
    try{PromoService::createPending($seller,'product',101,$market);$published=false;}catch(InvalidArgumentException $e){$published=true;}$check($published,'same-seller published product is rejected at purchase');
    try{PromoService::createPending(['id'=>20,'status'=>'approved'],'product',201,$market);$disabled=false;}catch(InvalidArgumentException $e){$disabled=true;}$check($disabled,'disabled product is rejected at purchase');
    $first=PromoService::createPending($seller,'product',100,$market);$priceChanged=PromoService::updatePrice($market,999);$samePriceSaved=PromoService::updatePrice($market,999);$missingPriceRejected=!PromoService::updatePrice(999999,999);try{PromoService::updatePrice($market,0);$zeroPriceRejected=false;}catch(InvalidArgumentException $e){$zeroPriceRejected=true;}try{PromoService::updatePrice($market,-1);$negativePriceRejected=false;}catch(InvalidArgumentException $e){$negativePriceRejected=true;}$second=PromoService::createPending($seller,'shop',null,$market);
    $check($priceChanged&&$samePriceSaved&&$missingPriceRejected&&$zeroPriceRejected&&$negativePriceRejected&&(int)$first['price_cents']===300&&(int)$second['price_cents']===999,'package snapshots persist while valid same-price saves succeed and invalid package/price saves fail');
    try{PromoService::activate((int)$first['id'],301,'usd');$badAmount=false;}catch(RuntimeException $e){$badAmount=true;}
    try{PromoService::activate((int)$first['id'],300,'eur');$badCurrency=false;}catch(RuntimeException $e){$badCurrency=true;}
    $check($badAmount&&$badCurrency&&DB::row('select payment_status from ads where id=?',[$first['id']])['payment_status']==='pending','activation rejects incorrect amount and currency');
    PromoService::activate((int)$first['id'],300,'usd','cs_1','pi_1','2026-09-17 00:00:00');$activated=DB::row('select * from ads where id=?',[$first['id']]);
    PromoService::activate((int)$first['id'],300,'usd','cs_replay','pi_replay','2026-09-18 00:00:00');$replayed=DB::row('select * from ads where id=?',[$first['id']]);
    $check($activated['starts_at']===$replayed['starts_at']&&$activated['ends_at']===$replayed['ends_at']&&(int)$replayed['email_appearances_used']===0&&(int)DB::row('select count(*) n from notifications where event_key=?',['promo:'.$first['id'].':active'])['n']===1,'duplicate activation preserves counters/dates and one stable notification');
    PromoService::paymentFailed((int)$first['id'],null,'pi_late_failure');$check(DB::row('select payment_status from ads where id=?',[$first['id']])['payment_status']==='paid','late terminal Stripe event cannot overwrite paid activation');
    $stripeController=new \App\Controllers\StripeController();$dispatch=new ReflectionMethod($stripeController,'processEvent');$dispatch->setAccessible(true);
    $checkoutPromo=PromoService::createPending($seller,'shop',null,$market);$dispatch->invoke($stripeController,['data'=>['object'=>['id'=>'cs_phase13_supported','payment_intent'=>'pi_phase13_session','payment_status'=>'paid','amount_total'=>999,'currency'=>'usd','metadata'=>['payment_kind'=>'promo','promo_campaign_id'=>(string)$checkoutPromo['id']]]]],'evt_phase13_checkout','checkout.session.completed');$checkoutState=DB::row('select * from ads where id=?',[$checkoutPromo['id']]);$check($checkoutState['payment_status']==='paid'&&$checkoutState['stripe_checkout_session_id']==='cs_phase13_supported'&&$checkoutState['stripe_payment_intent_id']==='pi_phase13_session','supported paid Checkout Session maps session/intent IDs and activates promo');$unpaidCheckoutPromo=PromoService::createPending($seller,'shop',null,$market);$dispatch->invoke($stripeController,['data'=>['object'=>['id'=>'cs_phase13_unpaid','payment_intent'=>'pi_phase13_unpaid','payment_status'=>'unpaid','amount_total'=>999,'currency'=>'usd','metadata'=>['payment_kind'=>'promo','promo_campaign_id'=>(string)$unpaidCheckoutPromo['id']]]]],'evt_phase13_checkout_unpaid','checkout.session.completed');$unpaidCheckoutState=DB::row('select * from ads where id=?',[$unpaidCheckoutPromo['id']]);$check($unpaidCheckoutState['payment_status']==='pending'&&$unpaidCheckoutState['status']==='pending_payment'&&$unpaidCheckoutState['stripe_checkout_session_id']==='cs_phase13_unpaid'&&$unpaidCheckoutState['stripe_payment_intent_id']==='pi_phase13_unpaid','supported unpaid Checkout completion stores correctly typed IDs without activation');
    $intentPromo=PromoService::createPending($seller,'shop',null,$market);PromoService::storeCheckoutIds((int)$intentPromo['id'],'cs_phase13_existing');$dispatch->invoke($stripeController,['data'=>['object'=>['id'=>'pi_phase13_supported','amount_received'=>999,'currency'=>'usd','metadata'=>['payment_kind'=>'promo','promo_campaign_id'=>(string)$intentPromo['id']]]]],'evt_phase13_intent','payment_intent.succeeded');$intentState=DB::row('select * from ads where id=?',[$intentPromo['id']]);$check($intentState['payment_status']==='paid'&&$intentState['stripe_checkout_session_id']==='cs_phase13_existing'&&$intentState['stripe_payment_intent_id']==='pi_phase13_supported','supported PaymentIntent maps only intent ID and preserves Checkout Session ID');$failedIntentPromo=PromoService::createPending($seller,'shop',null,$market);PromoService::storeCheckoutIds((int)$failedIntentPromo['id'],'cs_phase13_failed_existing');$dispatch->invoke($stripeController,['data'=>['object'=>['id'=>'pi_phase13_failed','metadata'=>['payment_kind'=>'promo','promo_campaign_id'=>(string)$failedIntentPromo['id']]]]],'evt_phase13_intent_failed','payment_intent.payment_failed');$failedIntentState=DB::row('select * from ads where id=?',[$failedIntentPromo['id']]);$check($failedIntentState['payment_status']==='failed'&&$failedIntentState['status']==='payment_failed'&&$failedIntentState['stripe_checkout_session_id']==='cs_phase13_failed_existing'&&$failedIntentState['stripe_payment_intent_id']==='pi_phase13_failed','supported failed PaymentIntent maps only intent ID and applies failure transition');
    $unsupportedPromo=PromoService::createPending($seller,'shop',null,$market);PromoService::storeCheckoutIds((int)$unsupportedPromo['id'],'cs_phase13_unchanged','pi_phase13_unchanged');$beforeUnsupported=DB::row('select payment_status,status,stripe_checkout_session_id,stripe_payment_intent_id from ads where id=?',[$unsupportedPromo['id']]);$rejectsMetadata=function(string $type,array $metadata)use($dispatch,$stripeController):bool{try{$dispatch->invoke($stripeController,['data'=>['object'=>['id'=>'obj_bad_metadata','metadata'=>$metadata]]],'evt_phase13_bad_metadata',$type);return false;}catch(RuntimeException $e){return $e->getMessage()==='Promotion metadata is incomplete.';}};$missingSupported=$rejectsMetadata('payment_intent.succeeded',['payment_kind'=>'promo']);$zeroSupported=$rejectsMetadata('checkout.session.completed',['payment_kind'=>'promo','promo_campaign_id'=>'0']);$missingUnsupported=$rejectsMetadata('charge.succeeded',['payment_kind'=>'promo']);$positiveLookingMalformed=$rejectsMetadata('charge.succeeded',['payment_kind'=>'promo','promo_campaign_id'=>'1abc']);$check($missingSupported&&$zeroSupported&&$missingUnsupported&&$positiveLookingMalformed&&DB::row('select payment_status,status,stripe_checkout_session_id,stripe_payment_intent_id from ads where id=?',[$unsupportedPromo['id']])===$beforeUnsupported,'malformed promo metadata is rejected before supported or unsupported event dispatch without mutation');$dispatch->invoke($stripeController,['data'=>['object'=>['id'=>'ch_fake_phase13','metadata'=>['payment_kind'=>'promo','promo_campaign_id'=>(string)$unsupportedPromo['id']]]]],'evt_phase13_unsupported','charge.succeeded');$afterUnsupported=DB::row('select payment_status,status,stripe_checkout_session_id,stripe_payment_intent_id from ads where id=?',[$unsupportedPromo['id']]);$check($beforeUnsupported===$afterUnsupported,'unsupported promo-metadata event cannot mutate state or stored Stripe IDs');$dispatch->invoke($stripeController,['data'=>['object'=>['id'=>'obj_nonpromo','metadata'=>['promo_campaign_id'=>(string)$unsupportedPromo['id']]]]],'evt_phase13_nonpromo','customer.updated');$check(DB::row('select payment_status,status,stripe_checkout_session_id,stripe_payment_intent_id from ads where id=?',[$unsupportedPromo['id']])===$afterUnsupported,'non-promo event is not intercepted by promotion handling');DB::exec('update ads set status="ended" where id in (?,?)',[$checkoutPromo['id'],$intentPromo['id']]);

    DB::exec('update ads set starts_at=date_sub(now(),interval 1 hour),ends_at=date_add(now(),interval 1 day),status="active",payment_status="paid",impressions=1000,last_served_at=null where id=?',[$first['id']]);
    PromoService::activate((int)$second['id'],999,'usd');DB::exec('update ads set starts_at=date_sub(now(),interval 1 hour),ends_at=date_add(now(),interval 1 day),impressions=0,last_served_at=null where id=?',[$second['id']]);
    $served=[];for($i=0;$i<6;$i++)$served[]=PromoService::chooseWebsite('marketplace')['id'];$counts=array_count_values($served);
    $check(($counts[$first['id']]??0)===3&&($counts[$second['id']]??0)===3,'round-robin rotation ignores unequal historical impressions');
    PromoService::pause((int)$second['id']);DB::exec('update products set status="published" where id=100');$notServed=PromoService::chooseWebsite('marketplace')===null;DB::exec('update products set status="approved" where id=100');$approvedServed=PromoService::chooseWebsite('marketplace');PromoService::resume((int)$second['id']);$check($notServed&&($approvedServed['id']??null)===(int)$first['id'],'website serving accepts approved product and excludes published product');
    $oldEnd=DB::row('select ends_at from ads where id=?',[$first['id']])['ends_at'];$pauseOk=PromoService::pause((int)$first['id']);$pauseAgain=!PromoService::pause((int)$first['id']);DB::exec('update ads set paused_at=date_sub(now(),interval 2 hour) where id=?',[$first['id']]);$resumeOk=PromoService::resume((int)$first['id']);$resumeAgain=!PromoService::resume((int)$first['id']);$missingAction=!PromoService::pause(999999);$newEnd=DB::row('select ends_at from ads where id=?',[$first['id']])['ends_at'];
    $check($pauseOk&&$pauseAgain&&$resumeOk&&$resumeAgain&&$missingAction&&abs((strtotime($newEnd)-strtotime($oldEnd))-7200)<=2,'admin transition contracts reject repeats/missing campaigns and website resume extends paused duration');
    DB::exec('update ads set status="active",ends_at=date_sub(now(),interval 1 second) where id=?',[$first['id']]);PromoService::campaigns(10);PromoService::expireWebsite();
    $check(DB::row('select status from ads where id=?',[$first['id']])['status']==='ended'&&(int)DB::row('select count(*) n from notifications where event_key=?',['promo:'.$first['id'].':complete'])['n']===1,'expiration ends once and creates one stable completion notification');

    $weekly=(int)DB::row('select id from promo_packages where placement="weekly_email" and duration_value=2')['id'];
    $queueMessage=function(array $data,string $status='pending'):int{static $sequence=0;$sequence++;DB::exec('insert into email_messages(classification,recipient_email,recipient_name,subject,template,template_data,deduplication_key,status,next_attempt_at) values("marketing","one@example.test","Seller One","Weekly digest","marketplace_digest",?,?,?,now())',[json_encode($data),'phase13-delivery-'.$sequence,$status]);return (int)DB::id();};
    $email=PromoService::createPending($seller,'product',100,$weekly);PromoService::activate((int)$email['id'],1500,'usd',null,null,'2026-09-01 10:00:00');$card=PromoService::card((int)$email['id']);$weeklyEligible=array_column(PromoService::weekly('2026-09-15','2026-09-22'),'id');$check(in_array((int)$email['id'],$weeklyEligible,true),'approved product promotion is eligible for weekly selection');DB::exec('update products set status="published" where id=100');$check(!in_array((int)$email['id'],array_column(PromoService::weekly('2026-09-15','2026-09-22'),'id'),true),'published product promotion is excluded from weekly selection');DB::exec('update products set status="approved" where id=100');
    $periodData=fn(array $promos,string $start,string $end):array=>['user_id'=>1,'name'=>'Buyer','frequency'=>'weekly','marketing_preference'=>'weekly','period_start'=>$start,'period_end'=>$end,'paid_promos'=>$promos,'products'=>[],'manage_preferences_url'=>'/account','unsubscribe_url'=>'/unsubscribe'];
    $nonSent=[];foreach(['pending','processing','failed','cancelled'] as $state){$mid=$queueMessage($periodData([$card],'2026-09-01','2026-09-08'),$state);$nonSent[]=$mid;PromoService::recordWeeklyDelivery($mid);}$check(!DB::row('select id from promo_email_sends where ad_id=?',[$email['id']]),'non-sent message states cannot manufacture delivery accounting');DB::exec('update email_messages set status="cancelled" where id in ('.implode(',',array_map('intval',$nonSent)).')');
    $failedMessage=$queueMessage($periodData([$card],'2026-09-01','2026-09-08'));
    $check((int)DB::row('select email_appearances_used from ads where id=?',[$email['id']])['email_appearances_used']===0&&!DB::row('select id from promo_email_appearances where ad_id=?',[$email['id']])&&!DB::row('select id from promo_email_sends where ad_id=?',[$email['id']]),'queue preparation does not consume an appearance or send');
    $_ENV['MAIL_TRANSPORT']='unavailable';EmailQueueService::process(1);$check(!DB::row('select id from promo_email_appearances where ad_id=?',[$email['id']])&&!DB::row('select id from promo_email_sends where ad_id=?',[$email['id']]),'failed delivery does not consume an appearance or send');
    DB::exec('update email_messages set status="cancelled",next_attempt_at=null where id=? and status="pending"',[$failedMessage]);

    $paused=PromoService::createPending($seller,'shop',null,$weekly);PromoService::activate((int)$paused['id'],1500,'usd');$pausedCard=PromoService::card((int)$paused['id']);$suppressedMessage=$queueMessage($periodData([$pausedCard],'2026-09-15','2026-09-22'));$weeklyUsedBefore=(int)DB::row('select email_appearances_used from ads where id=?',[$paused['id']])['email_appearances_used'];PromoService::pause((int)$paused['id']);$_ENV['MAIL_TRANSPORT']='log';EmailQueueService::process(1);$check(DB::row('select status from email_messages where id=?',[$suppressedMessage])['status']==='cancelled'&&!DB::row('select id from promo_email_appearances where ad_id=?',[$paused['id']])&&!DB::row('select id from promo_email_sends where ad_id=?',[$paused['id']]),'paused promo is removed before delivery with zero accounting');$weeklyResume=PromoService::resume((int)$paused['id']);$weeklyAfter=DB::row('select email_appearances_used,ends_at from ads where id=?',[$paused['id']]);$check($weeklyResume&&(int)$weeklyAfter['email_appearances_used']===$weeklyUsedBefore&&$weeklyAfter['ends_at']===null&&in_array((int)$paused['id'],array_column(PromoService::weekly('2026-09-22','2026-09-29'),'id'),true),'weekly resume preserves appearances and restores future eligibility');

    $firstMessage=$queueMessage($periodData([$card],'2026-09-01','2026-09-08'));EmailQueueService::process(1);$afterFirst=DB::row('select * from ads where id=?',[$email['id']]);$check((int)$afterFirst['email_appearances_used']===1&&(int)DB::row('select count(*) n from promo_email_appearances where ad_id=?',[$email['id']])['n']===1&&(int)DB::row('select count(*) n from promo_email_sends where ad_id=?',[$email['id']])['n']===1,'first successful recipient delivery creates one appearance and one send');
    $secondMessage=$queueMessage($periodData([$card],'2026-09-01','2026-09-08'));EmailQueueService::process(1);$check((int)DB::row('select email_appearances_used from ads where id=?',[$email['id']])['email_appearances_used']===1&&(int)DB::row('select count(*) n from promo_email_sends where ad_id=?',[$email['id']])['n']===2,'second recipient in same week adds a send but no appearance');
    PromoService::recordWeeklyDelivery($secondMessage);$check((int)DB::row('select count(*) n from promo_email_sends where ad_id=?',[$email['id']])['n']===2&&(int)DB::row('select email_appearances_used from ads where id=?',[$email['id']])['email_appearances_used']===1,'same message accounting replay is idempotent');
    $finalMessage=$queueMessage($periodData([$card],'2026-09-08','2026-09-15'));$additionalFinalMessage=$queueMessage($periodData([$card],'2026-09-08','2026-09-15'));EmailQueueService::process(1);$ended=DB::row('select * from ads where id=?',[$email['id']]);$check((int)$ended['email_appearances_used']===2&&$ended['status']==='ended'&&PromoService::hasQueuedWeeklyRecipients((int)$email['id']),'first final-week delivery ends campaign and exposes emergency removal');$check(PromoService::remove((int)$email['id']),'emergency remove accepts ended final-week campaign with queued recipient');EmailQueueService::process(1);$check((int)DB::row('select count(*) n from promo_email_sends where ad_id=?',[$email['id']])['n']===3&&(int)DB::row('select email_appearances_used from ads where id=?',[$email['id']])['email_appearances_used']===2&&!PromoService::hasQueuedWeeklyRecipients((int)$email['id'])&&!PromoService::remove((int)$email['id']),'emergency removal suppresses later recipient and ordinary ended/removal path is unavailable');

    $cancelledEmail=PromoService::createPending($seller,'shop',null,$weekly);PromoService::activate((int)$cancelledEmail['id'],1500,'usd');$cancelledCard=PromoService::card((int)$cancelledEmail['id']);PromoService::cancel((int)$cancelledEmail['id']);$check(PromoService::revalidateQueuedWeekly([$cancelledCard],'2026-09-15','2026-09-22')===[],'cancelled queued promo is removed before delivery');
    $disabledEmail=PromoService::createPending($seller,'product',100,$weekly);PromoService::activate((int)$disabledEmail['id'],1500,'usd');$disabledCard=PromoService::card((int)$disabledEmail['id']);$publishedQueuedMessage=$queueMessage($periodData([$disabledCard],'2026-09-15','2026-09-22'));DB::exec('update products set status="published" where id=100');$check(PromoService::revalidateQueuedWeekly([$disabledCard],'2026-09-15','2026-09-22')===[],'published product promo is removed before delivery');EmailQueueService::process(1);$check(DB::row('select status from email_messages where id=?',[$publishedQueuedMessage])['status']==='cancelled'&&!DB::row('select id from promo_email_appearances where ad_id=?',[$disabledEmail['id']])&&!DB::row('select id from promo_email_sends where ad_id=?',[$disabledEmail['id']]),'published product revalidation suppresses delivery without appearance or send accounting');DB::exec('update products set status="approved" where id=100');
    $disabledQueuedPromo=PromoService::createPending($seller,'product',100,$weekly);PromoService::activate((int)$disabledQueuedPromo['id'],1500,'usd');$disabledQueuedCard=PromoService::card((int)$disabledQueuedPromo['id']);$disabledQueuedMessage=$queueMessage($periodData([$disabledQueuedCard],'2026-09-15','2026-09-22'));DB::exec('update products set status="disabled" where id=100');$check(PromoService::revalidateQueuedWeekly([$disabledQueuedCard],'2026-09-15','2026-09-22')===[],'disabled product promo is removed before delivery');EmailQueueService::process(1);$check(DB::row('select status from email_messages where id=?',[$disabledQueuedMessage])['status']==='cancelled'&&!DB::row('select id from promo_email_appearances where ad_id=?',[$disabledQueuedPromo['id']])&&!DB::row('select id from promo_email_sends where ad_id=?',[$disabledQueuedPromo['id']]),'disabled product revalidation independently suppresses delivery without appearance or send accounting');DB::exec('update products set status="approved" where id=100');
    $shopEmail=PromoService::createPending($seller,'shop',null,$weekly);PromoService::activate((int)$shopEmail['id'],1500,'usd');$shopCard=PromoService::card((int)$shopEmail['id']);DB::exec('update designers set status="disabled" where id=10');$check(PromoService::revalidateQueuedWeekly([$shopCard],'2026-09-15','2026-09-22')===[],'disabled store promo is removed before delivery');DB::exec('update designers set status="approved" where id=10');
    $backfill=PromoService::createPending($seller,'shop',null,$weekly);PromoService::activate((int)$backfill['id'],1500,'usd',null,null,'2026-09-17 10:00:00');$historical=array_column(PromoService::weekly('2026-09-01','2026-09-08'),'id');$sameDay=array_column(PromoService::weekly('2026-09-10','2026-09-17'),'id');$check(!in_array((int)$backfill['id'],$historical,true)&&in_array((int)$backfill['id'],$sameDay,true),'September 17 purchase is excluded from September 8 backfill but allowed for same-day send');
    $setupFailure=PromoService::createPending($seller,'shop',null,$weekly);PromoService::checkoutSetupFailed((int)$setupFailure['id']);$check(DB::row('select status from ads where id=?',[$setupFailure['id']])['status']==='payment_failed','checkout setup failure leaves no pending_payment campaign');PromoService::activate((int)$setupFailure['id'],1500,'usd');$check(DB::row('select status from ads where id=?',[$setupFailure['id']])['status']==='active','later verified successful payment can activate a failed unpaid campaign');

    $reconcilePromo=PromoService::createPending($seller,'shop',null,$weekly);PromoService::activate((int)$reconcilePromo['id'],1500,'usd');$reconcileCard=PromoService::card((int)$reconcilePromo['id']);$reconcileMessage=$queueMessage($periodData([$reconcileCard],'2026-09-22','2026-09-29'),'sent');DB::exec('update email_messages set last_error="Delivered; promotion accounting requires reconciliation: simulated" where id=?',[$reconcileMessage]);$reconciled=PromoService::reconcileWeeklyDeliveries();PromoService::reconcileWeeklyDeliveries();$check($reconciled['reconciled']===1&&(int)DB::row('select count(*) n from promo_email_sends where ad_id=?',[$reconcilePromo['id']])['n']===1&&DB::row('select last_error from email_messages where id=?',[$reconcileMessage])['last_error']===null,'sent-message reconciliation is authoritative, idempotent, and clears only its diagnostic');
    $oneWeek=(int)DB::row('select id from promo_packages where placement="weekly_email" and duration_value=1')['id'];$endingEmail=PromoService::createPending($seller,'shop',null,$oneWeek);PromoService::activate((int)$endingEmail['id'],800,'usd',null,null,'2026-09-20 10:00:00');$endingCard=PromoService::card((int)$endingEmail['id']);$check(!DB::row('select id from notifications where event_key=?',['promo:'.$endingEmail['id'].':ending']),'one-week promo is not warned at activation');DB::exec('update email_preferences set weekly_emails=0 where user_id=1');$check(\App\Services\EmailDigestService::queueDigest('weekly','2026-10-01')===0&&!DB::row('select id from notifications where event_key=?',['promo:'.$endingEmail['id'].':ending']),'zero successfully queued recipients create no ending warning');DB::exec('update email_preferences set weekly_emails=1 where user_id=1');$check(\App\Services\EmailDigestService::queueDigest('weekly','2026-10-01')===1&&(int)DB::row('select count(*) n from notifications where event_key=?',['promo:'.$endingEmail['id'].':ending'])['n']===1,'real weekly producer queue creates one final-issue warning');$check(\App\Services\EmailDigestService::queueDigest('weekly','2026-10-01')===0&&(int)DB::row('select count(*) n from notifications where event_key=?',['promo:'.$endingEmail['id'].':ending'])['n']===1,'repeated producer run dedupes message and ending warning');$queuedEnding=DB::row('select * from email_messages where deduplication_key=?',['digest:weekly:2026-09-24:1']);DB::exec('delete from notifications where event_key=?',['promo:'.$endingEmail['id'].':ending']);DB::exec('update email_messages set status="sent",sent_at=now() where id=?',[$queuedEnding['id']]);PromoService::recordWeeklyDelivery((int)$queuedEnding['id']);$check(DB::row('select status from ads where id=?',[$endingEmail['id']])['status']==='ended','race fixture delivers and ends one-week campaign');PromoService::notifyWeeklyEndingForQueuedIssue([$endingCard],'2026-09-24','2026-10-01');$check((int)DB::row('select count(*) n from notifications where event_key=?',['promo:'.$endingEmail['id'].':ending'])['n']===1,'exact-period ended fallback recreates ending warning');DB::exec('delete from notifications where event_key=?',['promo:'.$endingEmail['id'].':ending']);PromoService::notifyWeeklyEndingForQueuedIssue([$endingCard],'2026-10-01','2026-10-08');$check(!DB::row('select id from notifications where event_key=?',['promo:'.$endingEmail['id'].':ending']),'different period cannot use ended fallback');
    $bulkIds=[];for($i=0;$i<30;$i++){$bulk=PromoService::createPending($seller,'shop',null,$weekly);PromoService::activate((int)$bulk['id'],1500,'usd');$bulkIds[]=(int)$bulk['id'];}$eligible=PromoService::weekly('2026-09-22','2026-09-29');$eligibleIds=array_column($eligible,'id');$allBulk=count(array_intersect($bulkIds,$eligibleIds))===30;$organicMethod=new ReflectionMethod(\App\Services\EmailDigestService::class,'weeklyProducts');$organicMethod->setAccessible(true);$check($allBulk&&count($eligible)>=30&&$organicMethod->invoke(null,$eligible)===[],'all 30 paid promos remain included and organic fill is zero above 24');
    DB::exec('update ads set clicks=7 where id=?',[$email['id']]);$stats=PromoService::campaigns(10);$stat=null;foreach($stats as $campaign)if((int)$campaign['id']===(int)$email['id'])$stat=$campaign;$check($stat&&(int)$stat['email_appearances_used']===2&&max(0,(int)$stat['email_total_appearances']-(int)$stat['email_appearances_used'])===0&&(int)$stat['email_recipient_sends']===3&&(int)$stat['clicks']===7,'campaign stats report appearances, remaining, recipient sends, and clicks');$adminCampaigns=PromoService::campaigns();$adminPaidOnly=!array_filter($adminCampaigns,fn($campaign)=>($campaign['payment_status']??'')!=='paid');$check($adminPaidOnly,'admin campaign listing excludes unpaid and incomplete promotion attempts');
    $unpaid=PromoService::createPending($seller,'shop',null,$market);$check(PromoService::click($unpaid['click_token'])==='/browse','pending unpaid click is rejected');PromoService::checkoutExpired((int)$unpaid['id']);$check(PromoService::click($unpaid['click_token'])==='/browse','cancelled unpaid click is rejected');$failed=PromoService::createPending($seller,'shop',null,$market);PromoService::paymentFailed((int)$failed['id']);$check(PromoService::click($failed['click_token'])==='/browse','failed unpaid click is rejected');$check(PromoService::card((int)$unpaid['id'],true)===null&&PromoService::card((int)$failed['id'],true)===null,'cancelled and failed unpaid campaigns never serve');
    DB::exec('update ads set status="active",starts_at=date_sub(now(),interval 1 hour),ends_at=date_add(now(),interval 2 day) where id=?',[$first['id']]);$productToken=$first['click_token'];$productClicks=(int)DB::row('select clicks from ads where id=?',[$first['id']])['clicks'];$check(PromoService::click($productToken)==='/product/one-product'&&(int)DB::row('select clicks from ads where id=?',[$first['id']])['clicks']===$productClicks+1,'paid product click routes and increments while target is approved');DB::exec('update products set status="published" where id=100');$productClicks=(int)DB::row('select clicks from ads where id=?',[$first['id']])['clicks'];$check(PromoService::click($productToken)==='/browse'&&(int)DB::row('select clicks from ads where id=?',[$first['id']])['clicks']===$productClicks,'published product blocks historical paid click and click accounting');DB::exec('update products set status="approved" where id=100');
    $token=$second['click_token'];PromoService::pause((int)$second['id']);$pausedClicks=(int)DB::row('select clicks from ads where id=?',[$second['id']])['clicks'];$check(PromoService::click($token)==='/store/seller-one'&&(int)DB::row('select clicks from ads where id=?',[$second['id']])['clicks']===$pausedClicks+1,'paid paused historical shop click remains valid and increments');PromoService::resume((int)$second['id']);DB::exec('update ads set ends_at=date_sub(now(),interval 1 second) where id=?',[$second['id']]);PromoService::expireWebsite();$endedClicks=(int)DB::row('select clicks from ads where id=?',[$second['id']])['clicks'];$check(DB::row('select status from ads where id=?',[$second['id']])['status']==='ended'&&PromoService::click($token)==='/store/seller-one'&&(int)DB::row('select clicks from ads where id=?',[$second['id']])['clicks']===$endedClicks+1,'naturally ended paid shop click remains valid and increments');
    $removed=PromoService::createPending($seller,'shop',null,$market);PromoService::activate((int)$removed['id'],999,'usd');$removedToken=$removed['click_token'];$removedClicks=(int)DB::row('select clicks from ads where id=?',[$removed['id']])['clicks'];$removedOnce=PromoService::remove((int)$removed['id']);$removedTwice=!PromoService::remove((int)$removed['id']);$check($removedOnce&&$removedTwice&&PromoService::click($removedToken)==='/browse'&&(int)DB::row('select clicks from ads where id=?',[$removed['id']])['clicks']===$removedClicks,'admin Remove succeeds once, rejects replay, and permanently disables tracked click without incrementing');
    $warning=PromoService::createPending($seller,'shop',null,$market);PromoService::activate((int)$warning['id'],999,'usd');DB::exec('update ads set ends_at=date_add(now(),interval 12 hour) where id=?',[$warning['id']]);PromoService::notifyWebsiteEnding();PromoService::notifyWebsiteEnding();$check((int)DB::row('select count(*) n from notifications where event_key=?',['promo:'.$warning['id'].':ending'])['n']===1,'website ending warning is stable and idempotent');$far=PromoService::createPending($seller,'shop',null,$market);PromoService::activate((int)$far['id'],999,'usd');DB::exec('update ads set ends_at=date_add(now(),interval 2 day) where id=?',[$far['id']]);$pausedWarning=PromoService::createPending($seller,'shop',null,$market);PromoService::activate((int)$pausedWarning['id'],999,'usd');DB::exec('update ads set ends_at=date_add(now(),interval 12 hour) where id=?',[$pausedWarning['id']]);PromoService::pause((int)$pausedWarning['id']);PromoService::notifyWebsiteEnding();$check(!DB::row('select id from notifications where event_key in (?,?)',['promo:'.$far['id'].':ending','promo:'.$pausedWarning['id'].':ending']),'website warning excludes campaigns beyond 24 hours and paused campaigns');
    DB::exec('update designers set status="disabled" where id=10');$beforeClicks=(int)DB::row('select clicks from ads where id=?',[$second['id']])['clicks'];$check(PromoService::click($token)==='/browse'&&(int)DB::row('select clicks from ads where id=?',[$second['id']])['clicks']===$beforeClicks&&PromoService::chooseWebsite('marketplace')===null,'ineligible target blocks paid historical click and serving');
}finally{$pdo->exec("use `$base`");$pdo->exec("drop database if exists `$db`");}
exit($failures?1:0);
