<?php
if (($_ENV['APP_ENV'] ?? getenv('APP_ENV') ?: '') !== 'test') { echo "SKIP/UNEXECUTED: APP_ENV is not exactly test; no database was touched.\n"; exit(0); }
require dirname(__DIR__).'/app/bootstrap.php';

use App\Core\Database as DB;
use App\Services\CollabIpRiskWorkflow;
use App\Services\CollabPayoutService;
use App\Services\CollabService;

try { $pdo=DB::pdo(); } catch (Throwable) { echo "SKIP/UNEXECUTED: disposable MariaDB is unavailable.\n"; exit(0); }
if (getenv('RUN_DISPOSABLE_DB_TESTS') !== '1') { echo "SKIP/UNEXECUTED: RUN_DISPOSABLE_DB_TESTS is not 1.\n"; exit(0); }
$failures=[];
$check=function(bool $ok,string $message)use(&$failures){echo($ok?'PASS: ':'FAIL: ').$message."\n";if(!$ok)$failures[]=$message;};
$paths=[];
try {
    $pdo->beginTransaction();
    foreach (['collab_events','collab_participants','collab_invitations','collab_files','collab_ip_risk_detections','collab_ip_risk_reviews','collab_order_allocations'] as $table) $check((bool)DB::row('show tables like ?',[$table]),'migrated table '.$table.' exists');
    $token=bin2hex(random_bytes(5));
    foreach ([['Host','host','approved'],['Eligible','eligible','approved'],['Below minimum','below','approved'],['Missing terms','missing','approved'],['Pending','pending','pending']] as [$name,$suffix,$status]) {
        DB::exec('insert into users(name,email,password_hash,role,status) values(?,?,"x","designer","active")',[$name,'p14-'.$suffix.'-'.$token.'@test']);$user=(int)DB::id();
        DB::exec('insert into designers(user_id,display_name,store_slug,status) values(?,?,?,?)',[$user,$name,'p14-'.$suffix.'-'.$token,$status]);$designers[$suffix]=(int)DB::id();$users[$suffix]=$user;
    }
    $check((bool)DB::row('select id from designers where id=? and status="approved"',[$designers['host']]),'approved seller may host');
    $check(!DB::row('select id from designers where id=? and status="approved"',[$designers['pending']]),'non-approved seller is rejected');
    try{CollabService::validateDates('2026-01-02','2026-01-01','2026-01-03');$valid=false;}catch(DomainException){$valid=true;}$check($valid,'create/edit deadline sequence is validated');
    DB::exec('insert into collab_events(host_designer_id,title,slug,description,price_cents,participation_type,minimum_file_count,upload_deadline,sale_starts_at,sale_close_date,status,invite_token_hash,invite_expires_at) values(?,?,?,?,1000,"open",2,now()+interval 1 hour,now()+interval 2 hour,current_date+interval 1 day,"collecting",?,now()+interval 1 hour)',[$designers['host'],'Open Fixture','p14-open-'.$token,'Fixture',hash('sha256','share-'.$token)]);$open=(int)DB::id();
    DB::exec('insert into collab_events(host_designer_id,title,slug,description,price_cents,participation_type,minimum_file_count,upload_deadline,sale_starts_at,sale_close_date,status) values(?,?,?,?,1000,"closed",1,now()+interval 1 hour,now()+interval 2 hour,current_date+interval 1 day,"collecting")',[$designers['host'],'Closed Fixture','p14-closed-'.$token,'Fixture']);$closed=(int)DB::id();
    DB::exec('insert into collab_participants(collab_id,designer_id,membership_status) values(?,? ,"host"),(?,? ,"requested")',[$open,$designers['host'],$open,$designers['eligible']]);
    DB::exec('update collab_participants set membership_status="accepted" where collab_id=? and designer_id=?',[$open,$designers['eligible']]);$check(DB::row('select membership_status from collab_participants where collab_id=? and designer_id=?',[$open,$designers['eligible']])['membership_status']==='accepted','Open request accepts');
    DB::exec('update collab_participants set membership_status="denied" where collab_id=? and designer_id=?',[$open,$designers['eligible']]);$check(DB::row('select membership_status from collab_participants where collab_id=? and designer_id=?',[$open,$designers['eligible']])['membership_status']==='denied','Open request denies');
    DB::exec('insert into collab_invitations(collab_id,email,token_hash,invited_by_designer_id,expires_at) values(?,?,?,?,now()+interval 1 hour)',[$open,'p14-eligible-'.$token.'@test',hash('sha256','open-direct'),$designers['host']]);
    DB::exec('insert into collab_invitations(collab_id,email,token_hash,invited_by_designer_id,expires_at) values(?,?,?,?,now()+interval 1 hour)',[$closed,'p14-missing-'.$token.'@test',hash('sha256','closed-direct'),$designers['host']]);
    $check((int)DB::row('select count(*) c from collab_invitations where collab_id in (?,?)',[$open,$closed])['c']===2,'Open and Closed direct invitations persist');
    DB::exec('insert into collab_participants(collab_id,designer_id,membership_status) values(?,? ,"accepted") on duplicate key update membership_status="accepted"',[$closed,$designers['missing']]);DB::exec('update collab_invitations set accepted_at=now(),accepted_designer_id=? where collab_id=? and email=?',[$designers['missing'],$closed,'p14-missing-'.$token.'@test']);$check((bool)DB::row('select id from collab_invitations where collab_id=? and accepted_designer_id=? and accepted_at is not null',[$closed,$designers['missing']]),'direct email-token join persists membership and acceptance');
    DB::exec('insert into collab_participants(collab_id,designer_id,membership_status) values(?,? ,"accepted") on duplicate key update membership_status="accepted"',[$open,$designers['below']]);$check(DB::row('select membership_status from collab_participants where collab_id=? and designer_id=?',[$open,$designers['below']])['membership_status']==='accepted','secure share-link join persists accepted membership');
    $pdo->exec('savepoint invitation_atomicity');try{DB::exec('insert into collab_invitations(collab_id,email,token_hash,invited_by_designer_id,expires_at) values(?,?,?,?,now()+interval 1 hour)',[$open,'orphan@test',hash('sha256','orphan'),$designers['host']]);throw new RuntimeException('participant write failed');}catch(Throwable){$pdo->exec('rollback to savepoint invitation_atomicity');}$check(!DB::row('select id from collab_invitations where email="orphan@test"'),'invitation transaction rollback leaves no orphan');
    $duplicate=false;try{DB::exec('insert into collab_participants(collab_id,designer_id,membership_status) values(?,? ,"accepted"),(?,? ,"accepted")',[$open,$designers['missing'],$open,$designers['missing']]);}catch(Throwable){$duplicate=true;}$check($duplicate,'duplicate membership is rejected');
    DB::exec('update collab_events set upload_deadline=now()-interval 1 second where id=?',[$open]);$check(!DB::row('select id from collab_events where id=? and upload_deadline>now()',[$open]),'deadline blocks membership and file mutation guard');
    $fingerprint=hash('sha256','same');$check(CollabIpRiskWorkflow::stateAfterScan('approved',$fingerprint,$fingerprint,true)==='approved','same IP fingerprint preserves approval');$check(CollabIpRiskWorkflow::stateAfterScan('rejected',$fingerprint,hash('sha256','changed'),true)==='review_required','changed risky fingerprint returns to review');
    // Persisted IP detection, atomic review, unchanged approval, changed-content review, rejection, and stale-review protection.
    DB::exec('insert into users(name,email,password_hash,role,status) values(?,? ,"x","admin","active")',['Admin','p14-admin-'.$token.'@test']);$admin=(int)DB::id();
    DB::exec('insert into ip_risk_terms(term,normalized_term,category,is_enabled) values(?,?,"trademark",1)',['Risk '.$token,'risk '.$token]);
    DB::exec('update collab_events set title=? where id=?',['Risk '.$token.' bundle',$closed]);
    $ip=new CollabIpRiskWorkflow();$scan=$ip->scan($closed);$check($scan['state']==='review_required'&&DB::row('select id from collab_ip_risk_detections where collab_id=? and is_active=1',[$closed]),'persisted IP detection requires review');
    $ip->review($closed,$admin,'approved',$scan['fingerprint'],'fixture approval');$check(DB::row('select ip_risk_state from collab_events where id=?',[$closed])['ip_risk_state']==='approved','Admin approval is persisted atomically');
    $same=$ip->scan($closed);$check($same['state']==='approved','unchanged approved fingerprint remains approved');
    CollabIpRiskWorkflow::invalidate($closed);$invalidated=DB::row('select ip_risk_state,ip_content_fingerprint from collab_events where id=?',[$closed]);$check($invalidated['ip_risk_state']==='review_required'&&$invalidated['ip_content_fingerprint']===null,'material filename/title mutation remains blocked when its follow-up scan fails');
    $rescanned=$ip->scan($closed);$check($rescanned['state']==='review_required','a later successful risky rescan does not silently restore prior approval');
    $ip->review($closed,$admin,'approved',$rescanned['fingerprint'],'fixture reapproval');
    DB::exec('update collab_events set description=concat(description," changed") where id=?',[$closed]);$changed=$ip->scan($closed);$check($changed['state']==='review_required','changed risky content returns to review');
    try{$ip->review($closed,$admin,'approved',$scan['fingerprint'],'stale');$stale=false;}catch(DomainException){$stale=true;}$check($stale,'stale fingerprint review is rejected');
    $ip->review($closed,$admin,'rejected',$changed['fingerprint'],'fixture rejection');$check(DB::row('select ip_risk_state from collab_events where id=?',[$closed])['ip_risk_state']==='rejected','Admin rejection is persisted atomically');

    // Filesystem-backed eligibility snapshot and protected ZIP membership.
    DB::exec('insert into collab_events(host_designer_id,title,slug,description,price_cents,participation_type,minimum_file_count,upload_deadline,sale_starts_at,sale_close_date,status) values(?,?,?,?,1000,"closed",2,now()-interval 1 minute,now(),current_date+interval 1 day,"collecting")',[$designers['host'],'ZIP Fixture','p14-zip-'.$token,'ZIP fixture']);$zipCollab=(int)DB::id();
    foreach(['host'=>'host','eligible'=>'accepted','below'=>'accepted','missing'=>'accepted'] as$suffix=>$membership){DB::exec('insert into collab_participants(collab_id,designer_id,membership_status) values(?,?,?)',[$zipCollab,$designers[$suffix],$membership]);$participantIds[$suffix]=(int)DB::id();}
    $root=app_path('storage/protected_uploads/collabs/'.$zipCollab);@mkdir($root,0750,true);
    $addFile=function(string$suffix,string$kind,string$name,string$content)use($root,$zipCollab,$designers,$participantIds,&$paths){$dir=$root.'/'.$designers[$suffix];@mkdir($dir,0750,true);$stored=bin2hex(random_bytes(6)).'.dat';$path=$dir.'/'.$stored;file_put_contents($path,$content);$paths[]=$path;DB::exec('insert into collab_files(collab_id,participant_id,designer_id,file_kind,original_name,stored_name,storage_path,mime_type,byte_size,sha256) values(?,?,?,?,?,?,?,?,?,?)',[$zipCollab,$participantIds[$suffix],$designers[$suffix],$kind,$name,$stored,'collabs/'.$zipCollab.'/'.$designers[$suffix].'/'.$stored,'application/octet-stream',strlen($content),hash('sha256',$content)]);return(int)DB::id();};
    foreach(['host','eligible','missing']as$suffix){$addFile($suffix,'contribution',$suffix.'-one.svg',$suffix.' one');$addFile($suffix,'contribution',$suffix.'-two.zip',$suffix.' two');}
    $addFile('below','contribution','below-only.svg','below');foreach(['host','eligible','below']as$suffix)$addFile($suffix,'terms',$suffix.'-terms.pdf',$suffix.' terms');
    $collabService=new CollabService();$collabService->finalize($zipCollab);$snapshot=DB::row('select * from collab_events where id=?',[$zipCollab]);
    $check($snapshot['status']==='ready'&&(int)$snapshot['eligible_count']===2,'deadline creates one eligibility snapshot and ready ZIP');
    $check(DB::row('select eligibility from collab_participants where collab_id=? and designer_id=?',[$zipCollab,$designers['below']])['eligibility']==='excluded','minimum-file participant is excluded');
    $check(DB::row('select exclusion_reason from collab_participants where collab_id=? and designer_id=?',[$zipCollab,$designers['missing']])['exclusion_reason']==='missing_terms_file','missing-Terms participant is excluded');
    $zipPath=app_path('storage/protected_uploads/'.$snapshot['final_zip_path']);$paths[]=$zipPath;$archive=new ZipArchive();$archive->open($zipPath);$names=[];for($i=0;$i<$archive->numFiles;$i++)$names[]=$archive->getNameIndex($i);$archive->close();
    $check((bool)array_filter($names,fn($name)=>str_contains($name,'host-terms.pdf'))&&(bool)array_filter($names,fn($name)=>str_contains($name,'eligible-terms.pdf')),'ZIP includes each eligible Terms file');
    $check(!array_filter($names,fn($name)=>str_contains($name,'below-only.svg')||str_contains($name,'missing-one.svg')),'ZIP excludes every ineligible seller file');
    $beforeSnapshot=$snapshot['snapshot_at'];$collabService->finalize($zipCollab);$check(DB::row('select snapshot_at from collab_events where id=?',[$zipCollab])['snapshot_at']===$beforeSnapshot,'ZIP retry does not resnapshot eligibility');
    $eligibleSource=$paths[1];$saved=file_get_contents($eligibleSource);file_put_contents($eligibleSource,'tampered');DB::exec('update collab_events set status="failed",final_zip_path=null,final_zip_sha256=null where id=?',[$zipCollab]);try{$collabService->finalize($zipCollab);$hashRejected=false;}catch(DomainException){$hashRejected=true;}$check($hashRejected,'ZIP retry rejects a changed source hash');file_put_contents($eligibleSource,$saved);$collabService->finalize($zipCollab);$check(DB::row('select status from collab_events where id=?',[$zipCollab])['status']==='ready','failed ZIP succeeds on retry without resnapshot');
    DB::exec('insert into collab_events(host_designer_id,title,slug,description,price_cents,participation_type,minimum_file_count,upload_deadline,sale_starts_at,sale_close_date,status) values(?,?,?,?,1000,"closed",9,now()-interval 1 minute,now(),current_date+interval 1 day,"collecting")',[$designers['host'],'Empty Fixture','p14-empty-'.$token,'Empty']);$empty=(int)DB::id();DB::exec('insert into collab_participants(collab_id,designer_id,membership_status) values(?,? ,"host")',[$empty,$designers['host']]);try{$collabService->finalize($empty);}catch(\App\Services\CollabTerminalException){}$check(DB::row('select status from collab_events where id=?',[$empty])['status']==='ineligible','zero-eligible snapshot is terminal and not retryable');
    $visibleHost=(new \App\Repositories\CollabRepository())->publicForDesigner($designers['host']);$visibleExcluded=(new \App\Repositories\CollabRepository())->publicForDesigner($designers['below']);$check(in_array($zipCollab,array_map('intval',array_column($visibleHost,'id')),true),'active collab appears for each eligible storefront');$check(!in_array($zipCollab,array_map('intval',array_column($visibleExcluded,'id')),true),'excluded storefront does not expose collab');

    // Persisted order-item allocation, earnings and payout ledgers without external Stripe calls.
    DB::exec('insert into users(name,email,password_hash,role,status) values(?,? ,"x","buyer","active")',['Buyer','p14-buyer-'.$token.'@test']);$buyer=(int)DB::id();
    DB::exec('insert into orders(user_id,status,payment_status,subtotal,total,marketplace_fee_model,marketplace_fee_basis_points,marketplace_fixed_fee_cents,stripe_currency) values(? ,"paid","paid",10,10,"percentage_plus_fixed",900,30,"usd")',[$buyer]);$order=(int)DB::id();
    $checkout=new \App\Services\CheckoutOrderService();$item=$checkout->addItem(['order_id'=>$order,'collab_id'=>$zipCollab,'title'=>'ZIP Fixture','slug'=>'p14-zip-'.$token,'designer_id'=>$designers['host'],'seller_name'=>'Collab contributors','license_type'=>'collab_bundle','license_name'=>'Collab Bundle','fulfillment_type'=>'downloadable','unit_price'=>'10.00','total_price'=>'10.00','commission_rate'=>.09]);DB::exec('update order_items set platform_commission_amount=1.20,marketplace_percentage_fee_amount=.90,marketplace_fixed_fee_amount=.30,seller_payout_amount=8.80 where id=?',[$item]);
    $finalizer=new \App\Services\OrderFinalizationService();$finalizer->prepareCollabFinancialLedgers($order,'usd',false);
    $check((int)DB::row('select count(*) c from collab_order_allocations where order_item_id=?',[$item])['c']===2,'collab allocations persist for every eligible contributor');$check((int)DB::row('select count(*) c from seller_earnings where order_id=? and collab_id=?',[$order,$zipCollab])['c']===2,'seller earnings persist for every contributor');$check((int)DB::row('select count(*) c from seller_payouts where order_id=?',[$order])['c']===2,'seller payouts persist for every contributor');$check((int)round((float)DB::row('select sum(platform_commission_amount) n from seller_payouts where order_id=?',[$order])['n']*100)===120,'marketplace fee is assessed once across payout rows');
    $adminItems=\App\Controllers\AdminController::orderDetailItems($order);$check(count($adminItems)===1&&(int)$adminItems[0]['id']===$item,'Admin order reporting returns one shared collab item despite contributor earnings');
    $check((int)DB::row('select count(*) c from collab_order_allocations where order_id=? and order_item_id=?',[$order,$item])['c']===2,'Admin collab allocation reporting retains both contributors separately');
    $check((int)DB::row('select count(*) c from collab_order_allocations a join orders o on o.id=a.order_id where a.designer_id=? and o.payment_status="paid"',[$designers['eligible']])['c']===1,'seller collab sales reporting query returns allocation');$check((int)DB::row('select count(*) c from collab_order_allocations a join designers d on d.id=a.designer_id where a.collab_id=?',[$zipCollab])['c']===2,'Admin allocation reporting query returns contributors');
    DB::exec('insert into downloads(user_id,order_id,order_item_id,product_id,product_file_id,collab_id,status) values(?,?,?,null,null,?,"served")',[$buyer,$order,$item,$zipCollab]);$check((bool)DB::row('select id from downloads where order_item_id=? and collab_id=? and status="served"',[$item,$zipCollab]),'successful collab download logging persists');
    $refundController=new \App\Controllers\StripeController();
    $recordRefund=function(string$event,int$cumulative,int$delta)use($order,$item,$refundController){DB::exec('insert into marketplace_refund_observations(order_id,stripe_event_id,cumulative_refund_cents,refund_delta_cents,merchandise_refund_cents,tax_refund_cents,allocated_cents,allocation_status) values(?,?,?,?,?,0,?,"reconciled")',[$order,$event,$cumulative,$delta,$delta,$delta]);$ob=(int)DB::id();DB::exec('insert into marketplace_refund_allocations(refund_observation_id,order_id,order_item_id,merchandise_refund_cents,event_key,allocation_source) values(?,?,?,?,?,"admin")',[$ob,$order,$item,$delta,'p14-refund-'.$event]);$refundController->reconcileRefundPayouts($order);};
    $recordRefund('p14-partial-'.$token,100,100);$check((int)DB::row('select sum(refunded_allocation_cents) n from collab_order_allocations where order_item_id=?',[$item])['n']>0,'partial collab refund persists contributor reductions');
    DB::exec('update seller_payouts set payout_status="transferred",completed_economic_value_amount=original_seller_payout_amount where order_id=? and designer_id=?',[$order,$designers['host']]);
    $recordRefund('p14-successive-'.$token,300,200);$check((int)DB::row('select count(*) c from seller_financial_adjustments where order_id=? and designer_id=? and adjustment_type="refund_recovery"',[$order,$designers['host']])['c']>0,'successive refund creates transferred-payout recovery');
    $recordRefund('p14-full-'.$token,1000,700);$remaining=(int)round((float)DB::row('select sum(seller_payout_amount) n from seller_payouts where order_id=?',[$order])['n']*100);$check($remaining===0,'full merchandise refund removes all contributor entitlement');$check(!CollabService::itemDownloadable('partially_refunded',1000,1000),'fully refunded persisted item is denied download');
    $split=(new CollabPayoutService())->split(1000,120,[$designers['host'],$designers['eligible']]);$check(array_sum($split['allocations'])+$split['fee_cents']===1000,'one fee plus contributor allocations conserves sale cents');
    $check(CollabService::itemDownloadable('partially_refunded',1000,999)&&!CollabService::itemDownloadable('partially_refunded',1000,1000),'item-level full refund denies download while partial refund retains it');
    DB::exec('update collab_events set status="ended",ended_at=now() where id=?',[$closed]);$check(DB::row('select status from collab_events where id=?',[$closed])['status']==='ended','expired collab history is retained as ended');
    if($failures)throw new RuntimeException(implode('; ',$failures));
    echo "Phase 14 disposable database behavioral checks passed without external Stripe access.\n";
} catch(Throwable $error) { fwrite(STDERR,'Phase 14 database test failed: '.$error->getMessage()."\n"); $exit=1; }
finally { if($pdo->inTransaction())$pdo->rollBack(); foreach($paths as$path)if(is_file($path))@unlink($path); }
exit($exit??0);
