<?php
$root=dirname(__DIR__); require "$root/app/bootstrap.php";
use App\Services\CsvProductImportService;
$fail=0; $check=function($ok,$name)use(&$fail){echo($ok?'PASS':'FAIL').": $name\n";if(!$ok)$fail++;};
$service=new CsvProductImportService(); $tmp=sys_get_temp_dir().'/am-phase124-'.bin2hex(random_bytes(4)); mkdir($tmp);
$cases=[
 'shopify'=>["Handle,Title,Body (HTML),Variant Price,Variant SKU,Tags,Image Src\r\nhat,\"Hat, Blue\",\"Line one\nLine two\",5.00,H-1,blue,https://example.com/a.jpg\r\nhat,,,5.00,H-1,,https://example.com/b.jpg\r\n",1],
 'etsy'=>["\xEF\xBB\xBFListing ID,Title,Description,Price,Currency,Tags,SKU Numbers,Image URLs\n11,Etsy item,Text,4.00,USD,one|two,E-1,https://example.com/e.jpg\n",1],
 'payhip'=>["product_key,product_url,title,description,price,tags,sku,product_type,image_url\np1,https://payhip.com/b/p1,Payhip item,Text,3.00,tag,P-1,digital,https://example.com/p.jpg\n",1],
 'square'=>["Token,Item Name,Variation Name,SKU,Description,Category,Price,Item Type\ns1,Square item,One,S-1,\"<b>Safe</b><script>x</script>\",Art,6.00,Physical\ns1,Square item,Two,S-2,Safe,Art,7.00,Physical\n",1],
 'squarespace'=>["Product ID,Variant ID,Product Type,Product URL,Title,Description,SKU,Price,Categories,Tags,Hosted Image URLs\nss1,v1,DOWNLOAD,https://site/p,Space item,Text,SS-1,8.00,Art,tag,https://example.com/s.jpg\nss1,v2,DOWNLOAD,https://site/p,Space item,Text,SS-2,8.00,Art,tag,https://example.com/s2.jpg\n",1],
 'wix'=>["handleId,fieldType,Product Name,Description,Price,SKU,Media URL\nw1,PRODUCT,Wix item,Text,9.00,W-1,\nw1,VARIANT,,,10.00,W-2,\nw1,MEDIA,,,,,https://example.com/w.jpg\n",1],
 'weebly'=>["PRODUCT_ID,TITLE,DESCRIPTION,IMAGE,CATEGORIES,SKU,PRICE,PRODUCT TYPE,OPTION NAME,OPTION VALUE\nwb1,Weebly item,Text,https://example.com/wb.jpg,Art,WB-1,11.00,Digital,Size,One\nwb1,Weebly item,Text,,Art,WB-2,11.00,Digital,Size,Two\n",1],
 'woocommerce'=>["ID,Type,SKU,Name,Published,Short description,Description,Regular price,Categories,Tags,Images,Parent,meta:ignored\n21,variable,WC-1,Woo item,1,Short,Long,12.00,Art,tag,https://example.com/wc.jpg,,ignore\n22,variation,WC-2,Woo variation,1,,,12.00,,,,21,ignore\n",1],
];
foreach($cases as $source=>[$csv,$count]){$path="$tmp/$source.csv";file_put_contents($path,$csv);$r=$service->parse($path,$source);$check(!$r['needs_mapping']&&count($r['records'])===$count,"$source adapter recognizes and groups representative products");}
$shop=$service->parse("$tmp/shopify.csv",'shopify')['records'][0];
$check(count($shop['images'])===2&&str_contains($shop['description'],"Line two"),'CSV supports quoted commas, multiline cells, CRLF, variants, and images');
$square=$service->parse("$tmp/square.csv",'square')['records'][0];
$check(!str_contains($square['description'],'<script>')&&in_array('Variants have different prices; review and enter the Asset Moth price.',$square['warnings'],true),'HTML is converted to text and conflicting variants require review');
$manual="$tmp/manual.csv";file_put_contents($manual,"My Key,My Name,Cost\na,Manual,2.00\n");$needs=$service->parse($manual,'payhip');$mapped=$service->parse($manual,'payhip',['source_id'=>'My Key','title'=>'My Name','price'=>'Cost']);
$check($needs['needs_mapping']&&!$mapped['needs_mapping'],'Payhip and changed headers use manual column mapping');
$override=$service->parse($manual,'payhip',['source_id'=>'my key','title'=>'my name','price'=>'']);$check(!$override['needs_mapping']&&$override['records'][0]['price']===null,'optional mapping override can choose Do not import without duplicate mappings');
$wrong="$tmp/wrong.csv";file_put_contents($wrong,"Order ID,Buyer Email,Sale Date\n1,a@example.com,2026-01-01\n");try{$service->parse($wrong,'etsy');$rejected=false;}catch(RuntimeException $e){$rejected=str_contains($e->getMessage(),'product/listing');}$check($rejected,'wrong export types are rejected');
$controller=file_get_contents("$root/app/Controllers/SellerController.php");$routes=file_get_contents("$root/public/index.php");$migration=file_get_contents("$root/database/migrations/2026_08_21_phase_12_4_csv_product_import.sql");
$check(str_contains($controller,'requireOnboardingComplete')&&str_contains($routes,"/seller/products/import/{id}/process")&&str_contains($controller,'result_status="queued"'),'seller-owned confirmation durably queues the exact selection for bounded processing');
$js=file_get_contents("$root/assets/js/app.js");$progress=file_get_contents("$root/app/Views/seller/product_import_progress.php");$check(str_contains($js,'xhr.upload.addEventListener')&&str_contains($js,'Reading your CSV')&&str_contains($progress,'data-import-progress')&&str_contains($js,'data.retry_ms')&&str_contains($js,'data.activity'),'upload, parsing, action, and actual import progress states are rendered');
$check(str_contains($migration,'product_import_source_owner_unique')&&str_contains($migration,"ai_disclosure ENUM('No AI Used','AI Assisted','AI Generated') NULL"),'cross-import duplicate constraint and explicit AI review state are present');
$schema=file_get_contents("$root/database/schema.sql");$check(str_contains($schema,"'queued','processing'")&&str_contains($migration,'product_import_images')&&str_contains($controller,'processNextImportedImage')&&str_contains($controller,'productImportActivity')&&str_contains($controller,'select id from product_import_runs where id=? for update')&&str_contains($controller,'normalizeLegacyProductImport')&&str_contains($controller,'not exists(select 1 from product_import_images x where x.import_item_id=i.id and x.status in'),'schema and controller persist bounded resumable product/image work');
$write=function(string $name,string $csv)use($tmp){$path="$tmp/$name.csv";file_put_contents($path,$csv);return $path;};
$special=$service->parse($write('formula',"ID,Title,SKU,Description\n1,+Plus Size Bundle,@Home,\"=LOVE and \"\"quoted\"\"\"\n"),'payhip',['source_id'=>'id','title'=>'title','sku'=>'sku','description'=>'description'])['records'][0];
$check($special['title']==='+Plus Size Bundle'&&$special['sku']==='@Home'&&str_contains($special['description'],'=LOVE'),'formula-like prefixes and escaped quotes are preserved as data');
try{$service->parse($write('invalid-utf8',"ID,Title\n1,\xC3\x28\n"),'payhip');$ok=false;}catch(RuntimeException $e){$ok=str_contains($e->getMessage(),'UTF-8');}$check($ok,'invalid UTF-8 is rejected');
foreach(['blank'=>",Title\n1,A\n",'repeat'=>"ID,ID,Title\n1,2,A\n"] as $name=>$csv){try{$service->parse($write($name,$csv),'payhip');$ok=false;}catch(RuntimeException $e){$ok=str_contains($e->getMessage(),'headings');}$check($ok,"$name headings rejected");}
try{$service->parse($write('width',"ID,Title\n1,A,extra\n"),'payhip');$ok=false;}catch(RuntimeException $e){$ok=str_contains($e->getMessage(),'different number');}$check($ok,'row width mismatch rejected');
$long=str_repeat('A',191);$record=$service->parse($write('long',"ID,Title\n1,$long\n"),'payhip')['records'][0];$check($record['errors']&&mb_strlen($record['source_title_display'])===190,'oversized title is preview-safe and invalid before creation');
$unknown=$service->parse($write('privacy',"ID,Type,SKU,Name,Regular price,Buyer Note,meta:secret\n1,simple,S,Safe,2.00,private@example.com,secret\n"),'woocommerce')['records'][0];$encoded=json_encode($unknown);$check(!str_contains($encoded,'private@example.com')&&!str_contains($encoded,'secret'),'unknown private and meta columns are not persisted');
$grouped=$service->parse($write('union',"Handle,Title,Variant Price,Variant SKU,Tags,Product Category,Image Src,Option1 Name,Option1 Value\nh,A,5,S1,one,Art,\"https://example.com/a,b.jpg\",Size,Small\nh,,5,S2,two,Graphics,https://example.com/2.jpg,Size,Large\n"),'shopify')['records'][0];
$check($grouped['tags']===['one','two']&&count($grouped['categories'])===2&&count($grouped['variants'])===2,'grouped tags/categories are unioned and curated variants retained');
$check($grouped['images'][0]==='https://example.com/a,b.jpg'&&count($grouped['images'])===2,'source-aware image parsing preserves commas and order');
$physical=$service->parse($write('type',"ID,Title,Product Type\n1,Physical item,physical\n"),'payhip')['records'][0];$check($physical['source_type_requires_review']&&!empty($physical['warnings']),'non-digital source type creates review warning');
$conflict=$service->parse($write('conflict',"Handle,Title,Variant Price\nh,A,5\nh,,7\n"),'shopify')['records'][0];$check($conflict['price']===null&&$conflict['price_requires_review'],'conflicting price retains unresolved review state');
$foreign=$service->parse($write('foreign',"Listing ID,Title,Price,Currency\n1,A,5,EUR\n"),'etsy')['records'][0];$check($foreign['price']===null&&$foreign['price_requires_review'],'foreign currency is not converted and requires review');
$prefix=str_repeat('x',220);$a=$service->parse($write('key-a',"product_key,title\n{$prefix}a,A\n"),'payhip')['records'][0];$b=$service->parse($write('key-b',"product_key,title\n{$prefix}b,A\n"),'payhip')['records'][0];$check($a['source_id']===$b['source_id']&&$a['source_fingerprint']!==$b['source_fingerprint'],'long identity display truncation cannot collide duplicate fingerprints');
$sameTitle=$service->parse($write('same-title',"product_key,title\nfirst,Same\nsecond,Same\n"),'payhip')['records'];$check(count($sameTitle)===2&&$sameTitle[0]['source_fingerprint']!==$sameTitle[1]['source_fingerprint'],'same title with different source IDs remains distinct');

foreach(['square'=>"Token,Item Name,Price,Online Sale Price\nsale-1,Square,10,8\n",'squarespace'=>"Product ID,Title,Price,Sale Price\nsale-2,Space,10,7\n",'weebly'=>"PRODUCT_ID,TITLE,PRICE,SALE PRICE\nsale-3,Weebly,10,6\n"] as $source=>$csv){$sale=$service->parse($write('sale-'.$source,$csv),$source)['records'][0];$check($sale['price']==='10.00'&&!empty($sale['source_sale_prices']),$source.' sale price is preserved as source metadata without replacing base price');}

$renderProductForm=function(array $keys)use($root){$p=['id'=>1,'title'=>'Draft','description'=>'Description','price'=>null,'fulfillment_type'=>'downloadable','ai_disclosure'=>null];$errors=[];$importReviewErrors=[];$importReviewKeys=$keys;$importReviewContext=[];$images=[];$files=[];$cats=[];$tagText='';$licenseTypes=[['id'=>1,'license_key'=>'personal','name'=>'Personal','description'=>'','sort_order'=>10]];$productLicenses=[];$ipRisk=['matches'=>[],'requires_confirmation'=>false];$_POST=[];$_SERVER['REQUEST_METHOD']='GET';ob_start();include "$root/app/Views/seller/edit_product.php";return ob_get_clean();};$importedForm=$renderProductForm(['ai']);$normalForm=$renderProductForm([]);preg_match('/<select name="ai_disclosure"([^>]*)>/',$importedForm,$importedAi);preg_match('/<select name="ai_disclosure"([^>]*)>/',$normalForm,$normalAi);$check(!str_contains($importedAi[1]??'','required')&&str_contains($normalAi[1]??'','required'),'rendered imported AI gate permits a blank progressive save while normal product AI remains required');
$importDir=$service->importDirectory();if(!is_dir($importDir))mkdir($importDir,0750,true);$stale=$importDir.'/'.bin2hex(random_bytes(8)).'.csv';file_put_contents($stale,'old');touch($stale,time()-90000);$outside="$tmp/outside.csv";file_put_contents($outside,'keep');$service->cleanupStaleFiles();$service->removeTemporaryFile($outside);$check(!is_file($stale)&&is_file($outside),'stale and explicit cleanup remain contained to protected CSV directory');
$limit="ID,Title\n";for($i=0;$i<=CsvProductImportService::MAX_ROWS;$i++)$limit.="$i,A$i\n";try{$service->parse($write('limit',$limit),'payhip');$ok=false;}catch(RuntimeException $e){$ok=str_contains($e->getMessage(),'50,000');}$check($ok,'row limit fails explicitly without truncation');
array_map('unlink',glob("$tmp/*"));rmdir($tmp);exit($fail?1:0);
