<h1>Batch: <?=H::e($batch['name'])?></h1>
<?php $drafts=$submitted=$errors=$created=0; foreach($products as $x){$drafts+=(int)($x['status']==='draft');$submitted+=(int)($x['status']==='pending_review');$created+=(int)in_array($x['status'],['approved','published'],true);$errors+=(int)!empty($x['batch_errors']);} ?>
<div class="card"><strong>Batch summary:</strong> <?=$drafts?> draft products · <?=$submitted?> submitted products · <?=$errors?> products with errors · <?=$created?> successfully created listings</div>
<form method="post" class="card"><input type="hidden" name="_csrf" value="<?=H::csrf()?>"><input type="hidden" name="action" value="copy"><h2>Copy selected fields from Product 1 to all draft products</h2><p class="muted">Titles, slugs, preview images, and protected files are never copied. Copies are independent after this action.</p>
<?php $labels=['short_description'=>'Short description','description'=>'Full description','price'=>'Base price','category_id'=>'Category','tags'=>'Tags / keywords','ai_disclosure'=>'AI disclosure','licenses'=>'License settings, paid prices, POD and permissions','seo_title'=>'SEO title','seo_description'=>'SEO description','fulfillment_type'=>'Fulfillment type','manual_delivery_instructions'=>'Manual delivery instructions','is_hand_drawn'=>'Hand-drawn disclosure']; foreach(array_merge($copyFields,['tags','licenses']) as $field): ?><label class="checkbox-option"><input type="checkbox" name="copy_fields[]" value="<?=H::e($field)?>"> <?=H::e($labels[$field]??$field)?></label><?php endforeach; ?><button onclick="return confirm('Copy the selected fields from Product 1 to every other draft?');">Apply to All / Copy to All</button></form>
<form method="post"><input type="hidden" name="_csrf" value="<?=H::csrf()?>"><div class="responsive-table"><table><tr><th>Submit</th><th>Product</th><th>Status</th><th>Validation</th><th>Actions</th></tr>
<?php foreach($products as $index=>$p): ?><tr><td><?php if($p['status']==='draft'): ?><input type="checkbox" name="products[]" value="<?=$p['id']?>" aria-label="Select <?=H::e($p['title'])?>"><?php endif; ?></td><td><strong>Product <?=$index+1?>: <?=H::e($p['title'])?></strong><br><small>/product/<?=H::e($p['slug'])?></small></td><td><span class="badge"><?=H::e(ucwords(str_replace('_',' ',$p['status'])))?></span></td><td><?php if($p['batch_errors']): ?><ul class="notice error"><?php foreach($p['batch_errors'] as $error): ?><li><?=H::e($error)?></li><?php endforeach; ?></ul><?php else: ?><span class="badge">Ready</span><?php endif; ?><?php if($p['status']==='draft'): ?><label class="checkbox-option"><input type="checkbox" name="ip_rights_confirmation[]" value="<?=$p['id']?>"> I confirm I have the legal right to sell this product if its IP scan is flagged.</label><?php endif; ?></td><td><a class="btn" href="/seller/product/<?=$p['id']?>">Edit Product <?=$index+1?></a><?php if($p['status']==='draft'): ?><button form="remove-<?=$p['id']?>" onclick="return confirm('Permanently remove this draft product and its uploads?');">Remove</button><?php endif; ?></td></tr><?php endforeach; ?></table></div><button name="action" value="submit_selected">Submit Selected Valid Products</button> <button name="action" value="submit_all" onclick="return confirm('Submit every valid draft in this batch? Invalid products will remain drafts.');">Submit All Valid Products</button><p class="help-text">Clean products publish using the normal seller submission behavior. Flagged products require rights confirmation and IP review.</p></form>
<form method="post" class="inline"><input type="hidden" name="_csrf" value="<?=H::csrf()?>"><input type="hidden" name="action" value="add"><button>Add Another Product</button></form>
<?php foreach($products as $p): if($p['status']==='draft'): ?><form method="post" id="remove-<?=$p['id']?>"><input type="hidden" name="_csrf" value="<?=H::csrf()?>"><input type="hidden" name="action" value="remove"><input type="hidden" name="product_id" value="<?=$p['id']?>"></form><?php endif; endforeach; ?>
