<?php use App\Core\Helpers as H;?>
<h1>Promotions</h1>
<p>Promote your approved shop or product with an automatically generated sponsored card.</p>
<div class="card">
    <h2>How paid promotions work</h2>
    <p><strong>Website promotions</strong> begin after Stripe confirms payment and run for the purchased calendar-day duration. They rotate fairly with other active paid campaigns in the same placement. Impressions, clicks, and sales are not guaranteed.</p>
    <p><strong>Weekly Email promotions</strong> for 1, 2, 4, or 6 weeks are included in the next 1, 2, 4, or 6 eligible Creative Moth weekly marketplace emails. Your promoted shop or product must remain eligible through delivery.</p>
    <p><strong>Category promotions</strong> let you advertise an eligible shop or product in any active Creative Moth category. The promoted product does not have to be listed in that category.</p>
</div>
<form method="post" action="/seller/promos/checkout" class="card form promo-form" id="promo-form">
    <input type="hidden" name="_csrf" value="<?=H::csrf()?>">
    <label>Target <select name="target_type" id="promo-target"><option value="shop">Shop</option><option value="product" <?=empty($products)?'disabled':''?>>Product</option></select></label>
    <label id="promo-product">Product
        <?php if(empty($products)):?><span class="muted">You have no approved products available to promote. You can still promote your shop.</span><?php else:?><select name="product_id"><option value="">Choose product</option><?php foreach($products as $p):?><option value="<?=$p['id']?>"><?=H::e($p['title'])?></option><?php endforeach;?></select><?php endif;?>
    </label>
    <label>Placement <select name="placement" id="promo-placement"><option value="marketplace">Marketplace</option><option value="homepage">Homepage</option><option value="category">Category</option><option value="weekly_email">Weekly Email</option></select></label>
    <label id="promo-category">Category <select name="category_id"><option value="">Choose category</option><?php foreach($categories as $c):?><option value="<?=$c['id']?>"><?=H::e($c['name'])?></option><?php endforeach;?></select></label>
    <fieldset><legend>Package</legend><?php foreach($packages as $p):?><label class="promo-package" data-placement="<?=H::e($p['placement'])?>"><input type="radio" name="package_id" value="<?=$p['id']?>" data-summary="<?=$p['duration_value'].' '.$p['duration_unit'].($p['duration_value']>1?'s':'').' — '.H::money($p['price_cents']/100)?>"> <?=$p['duration_value'].' '.$p['duration_unit'].($p['duration_value']>1?'s':'')?> — <?=H::money($p['price_cents']/100)?></label><?php endforeach;?></fieldset>
    <p><strong>Final:</strong> <span id="promo-summary">Choose a package</span></p>
    <button>Buy Promotion</button>
</form>
<script>(()=>{const f=document.querySelector('#promo-form'),t=f.target_type,p=f.placement;function sync(){document.querySelector('#promo-product').hidden=t.value!=='product';document.querySelector('#promo-category').hidden=p.value!=='category';f.querySelectorAll('.promo-package').forEach(x=>x.hidden=x.dataset.placement!==p.value);const c=f.querySelector('input[name=package_id]:checked');if(c&&c.closest('label').hidden)c.checked=false;document.querySelector('#promo-summary').textContent=(f.querySelector('input[name=package_id]:checked')||{}).dataset?.summary||'Choose a package'}f.addEventListener('change',sync);sync()})();</script>
<h2>Campaign history</h2>
<?php if(empty($campaigns)):?><div class="card empty-state"><h3>No promotions yet</h3><p>Your purchased promotions and verified payment status will appear here.</p></div><?php else:?><div class="promo-table"><table><tr><th>Target</th><th>Placement/package</th><th>Payment / campaign</th><th>Schedule</th><th>Results</th></tr><?php foreach($campaigns as $a):$used=(int)($a['email_appearances_used']??0);$total=(int)($a['email_total_appearances']??0);?><tr><td><?=H::e($a['target_type']==='shop'?$a['display_name']:($a['product_title']??'Unavailable product'))?></td><td><?=H::e(ucwords(str_replace('_',' ',$a['placement'])))?><?php if($a['placement']==='category'):?><br>Category: <?=H::e($a['category_name']??'Unavailable category')?><?php endif;?><br><?=$a['duration_value'].' '.$a['duration_unit']?> / <?=H::money($a['price_cents']/100)?></td><td><?=H::e($a['payment_status'])?> / <?=H::e($a['status'])?></td><td><?php if($a['placement']==='weekly_email'):?>Appearances: <?=$used?> of <?=$total?><br>Remaining: <?=max(0,$total-$used)?><?php else:?><?=H::e($a['starts_at']??'—')?> – <?=H::e($a['ends_at']??'—')?><?php endif;?></td><td><?php if($a['placement']==='weekly_email'):?>Sends: <?=(int)$a['email_recipient_sends']?><br>Clicks: <?=(int)$a['clicks']?><?php else:?><?=(int)$a['impressions']?> impressions<br><?=(int)$a['clicks']?> clicks<?php endif;?></td></tr><?php endforeach;?></table></div><?php endif;?>
