<?php use App\Core\Helpers as H; ?>
<header class="dashboard-heading"><div><h1>Social Publishing</h1><p class="muted">Connect accounts, choose automatic posting, post eligible listings, and review delivery results.</p></div></header>
<?php if($boardError):?><div class="alert warning"><?=H::e($boardError)?></div><?php endif;?>
<div class="dashboard-grid"><?php foreach(['facebook'=>'Facebook Page','instagram'=>'Instagram professional account','pinterest'=>'Pinterest'] as $platform=>$label):$c=$connections[$platform]??null;$enabled=!empty($integrations[$platform]['is_enabled']);?>
<section class="card"><h2><?=H::e($label)?></h2><p><strong>Status:</strong> <?=$c?H::e(str_replace('_',' ',$c['connection_status'])):'Not connected'?><?php if(!$enabled):?> · temporarily disabled<?php endif;?></p>
<?php if($c):?><p><?=H::e($c['external_account_name'])?></p><form method="post" action="/seller/social/<?=$platform?>/settings"><input type="hidden" name="_csrf" value="<?=H::csrf()?>"><label><input type="checkbox" name="auto_post" value="1" <?=$c['auto_post_enabled']?'checked':''?>> Automatically Post Newly Published Products and Custom Designs</label><?php if($platform==='pinterest'):?><label>Board<select name="board" required><option value="">Choose a board</option><?php foreach($boards as $board):$value=$board['id'].'|'.str_replace('|','',(string)$board['name']);?><option value="<?=H::e($value)?>" <?=$c['pinterest_board_id']==($board['id']??'')?'selected':''?>><?=H::e($board['name']??'Board')?></option><?php endforeach;?></select></label><?php endif;?><button class="btn" type="submit">Save settings</button></form><form method="post" action="/seller/social/<?=$platform?>/disconnect"><input type="hidden" name="_csrf" value="<?=H::csrf()?>"><button class="btn alt" type="submit">Disconnect</button></form><?php else:?><form method="post" action="/seller/social/<?=$platform?>/connect"><input type="hidden" name="_csrf" value="<?=H::csrf()?>"><button class="btn" type="submit" <?=$enabled?'':'disabled'?>>Connect</button></form><?php endif;?></section><?php endforeach;?></div>
<section class="card"><h2>Post a product</h2><?php if(!$products):?><p>No approved products are eligible.</p><?php else:?><ul><?php foreach($products as $p):?><li><?=H::e($p['title'])?> — <a href="/seller/social/product/<?=(int)$p['id']?>">Post Now</a></li><?php endforeach;?></ul><?php endif;?></section>
<section class="card"><h2>Post a Custom Design</h2><?php if(!$customDesigns):?><p>No active Custom Designs are eligible.</p><?php else:?><ul><?php foreach($customDesigns as $s):?><li><strong>Custom Design:</strong> <?=H::e($s['title'])?> — <a href="/seller/social/custom-design/<?=(int)$s['id']?>">Post Now</a></li><?php endforeach;?></ul><?php endif;?></section>
<section class="card"><h2>Posting history</h2><div class="table-wrap"><table><thead><tr><th>Attempt</th><th>Listing</th><th>Listing type</th><th>Platform</th><th>Post type</th><th>Status</th><th>Details</th></tr></thead><tbody><?php foreach($logs as $log):$retryable=!empty($log['custom_service_id'])?(!empty($log['current_custom_service_id'])&&!empty($log['current_custom_service_active'])):(!empty($log['current_product_id'])&&in_array($log['current_product_status'],['approved','published'],true));?><tr><td><?=H::e($log['attempted_at'])?></td><td><?=H::e($log['listing_title'])?></td><td><?=H::e($log['listing_type'])?></td><td><?=H::e(ucfirst($log['platform']))?></td><td><?=H::e($log['trigger_type'])?></td><td><?=H::e($log['status'])?></td><td><?php if($log['status']==='failed'):?><?=H::e($log['error_message'])?><?php if($retryable):?><form method="post" action="/seller/social/retry/<?=(int)$log['id']?>"><input type="hidden" name="_csrf" value="<?=H::csrf()?>"><button type="submit">Retry</button></form><?php else:?><span class="muted">Retry unavailable because the listing is no longer active or published.</span><?php endif;?><?php else:?><?=H::e($log['platform_post_id']??'')?><?php endif;?></td></tr><?php endforeach;?></tbody></table></div></section>
