<?php use App\Core\Helpers as H; ?>
<h1>Analytics &amp; Reports</h1>
<p class="muted">Financial totals use completed payment and stored payout/refund ledgers; health indicators reflect recorded application issues only.</p>
<?php if($error):?><div class="alert error"><?=H::e($error)?></div><?php else:?>
<form class="card" method="get"><label>From <input type="date" name="from" value="<?=H::e($report['filters']['from'])?>"></label><label>To <input type="date" name="to" value="<?=H::e($report['filters']['to'])?>"></label><label>Compare with <select name="comparison"><option value="previous" <?=$report['filters']['comparison']==='previous'?'selected':''?>>Previous equivalent period</option><option value="year_over_year" <?=$report['filters']['comparison']==='year_over_year'?'selected':''?>>Same dates last year</option></select></label><button>Apply</button> <a class="btn" href="/admin/analytics.csv?<?=http_build_query(['from'=>$report['filters']['from'],'to'=>$report['filters']['to'],'comparison'=>$report['filters']['comparison']])?>">Export CSV</a></form>
<?php $labels=['gross_sales'=>'Gross sales','net_sales'=>'Net sales','platform_commission'=>'Platform commission','seller_earnings'=>'Seller earnings','discounts'=>'Discounts','refunds'=>'Refunds','tax_collected'=>'Tax collected','orders'=>'Orders'];?><section><h2>Marketplace overview</h2><div class="dashboard-grid"><?php foreach($labels as $key=>$label):?><div class="card"><strong><?=$key==='orders'?number_format($report['financials'][$key]):H::money($report['financials'][$key])?></strong><span><?=H::e($label)?></span></div><?php endforeach;?></div></section>
<section class="card"><h2>What this means</h2><ul><?php foreach($report['insights'] as $insight):?><li><?=H::e($insight)?></li><?php endforeach;?></ul></section>
<section class="card"><h2>Period comparison</h2><p class="muted"><strong><?=$report['filters']['comparison']==='year_over_year'?'Same dates last year':'Previous equivalent period'?>:</strong> <?=H::e($report['filters']['from'])?>–<?=H::e($report['filters']['to'])?> compared with <?=H::e($report['filters']['previous_from'])?>–<?=H::e($report['filters']['previous_to'])?>.</p><div class="table-wrap"><table><thead><tr><th>Metric</th><th>Current</th><th>Previous</th><th>Difference</th><th>Change</th></tr></thead><tbody><?php foreach($labels+['buyers_growth'=>'New buyers','sellers_growth'=>'New sellers'] as $key=>$label):$c=$report['comparisons'][$key];?><tr><th><?=H::e($label)?></th><td><?=H::e((string)$c['current'])?></td><td><?=H::e((string)$c['previous'])?></td><td><?=H::e((string)$c['difference'])?></td><td><?=$c['percent']===null?'Not available — prior value is zero':H::e((string)$c['percent']).'%'?></td></tr><?php endforeach;?></tbody></table></div></section>
<section class="card"><h2>Marketplace health</h2><div class="dashboard-grid"><?php foreach($report['health'] as $key=>$value):?><div><strong><?=number_format((int)$value)?></strong><br><?=H::e(ucwords(str_replace('_',' ',$key)))?></div><?php endforeach;?></div></section>
<?php $tables=[['Sales by day of week',$report['sales_by_weekday'],['weekday_name'=>'Day','orders'=>'Qualifying orders']],['Revenue by traffic source',$report['traffic_sources'],['traffic_source'=>'Source','orders'=>'Orders','net_revenue'=>'Net revenue']],['Marketplace searches',$report['searches'],['normalized_query'=>'Search term','searches'=>'Searches','successful_searches'=>'With results','zero_result_searches'=>'Zero results','last_searched_at'=>'Last searched']],['Search trend by day',$report['search_trends'],['search_date'=>'Date','searches'=>'Searches','successful_searches'=>'With results','zero_result_searches'=>'Zero results']],['Top sellers',$report['sellers'],['display_name'=>'Seller','orders'=>'Orders','net_sales'=>'Net sales','earnings'=>'Earnings']],['Top products',$report['products'],['title'=>'Product','display_name'=>'Seller','units'=>'Units','gross_sales'=>'Gross sales']],['Customer ranking',$report['customers'],['name'=>'Customer','order_count'=>'Qualifying orders','last_order_at'=>'Last order']],['Coupon performance',$report['coupons'],['code'=>'Code','scope'=>'Scope','uses'=>'Uses','discount_amount'=>'Discount']],['Promo performance',$report['promos'],['placement'=>'Placement','status'=>'Status','campaigns'=>'Campaigns','impressions'=>'Impressions','clicks'=>'Clicks','spend_cents'=>'Spend (cents)']],['Referral performance',$report['referrals'],['referral_type'=>'Type','referrals'=>'Referrals','rewarded'=>'Rewarded']],['Bundle events',$report['bundles'],['title'=>'Event','orders'=>'Orders','earnings_cents'=>'Earnings (cents)']],['Buyer / seller growth',$report['growth'],['day'=>'Date','buyers'=>'Buyers','sellers'=>'Sellers']]];foreach($tables as [$title,$rows,$columns]):?><section class="card"><h2><?=H::e($title)?></h2><?php if(!$rows):?><p class="muted"><?=in_array($title,['Marketplace searches','Search trend by day'],true)?'No search history is available for this period. Search tracking begins with Phase 15.':'No data for this period.'?></p><?php else:?><div class="table-wrap"><table><thead><tr><?php foreach($columns as $heading):?><th><?=H::e($heading)?></th><?php endforeach;?></tr></thead><tbody><?php foreach($rows as $row):?><tr><?php foreach($columns as $key=>$heading):?><td><?=H::e((string)$row[$key])?></td><?php endforeach;?></tr><?php endforeach;?></tbody></table></div><?php endif;?></section><?php endforeach;?>
<section class="card"><h2>Failed payments</h2><?php if(!$report['failures']['payments']):?><p class="muted">No failed or review-required payments for this period.</p><?php else:?><div class="table-wrap"><table><tr><th>Order</th><th>Status</th><th>Review</th><th>Recorded</th></tr><?php foreach($report['failures']['payments'] as $row):?><tr><td>#<?=(int)$row['id']?></td><td><?=H::e($row['payment_status'])?></td><td><?=empty($row['manual_review_required'])?'No':'Yes'?></td><td><?=H::e($row['created_at'])?></td></tr><?php endforeach;?></table></div><?php endif;?></section>
<section class="card"><h2>Webhook issues</h2><?php if(!$report['failures']['webhooks']):?><p class="muted">No webhook issues for this period.</p><?php else:?><div class="table-wrap"><table><tr><th>Event</th><th>Type</th><th>Status</th><th>Issue</th><th>Recorded</th></tr><?php foreach($report['failures']['webhooks'] as $row):?><tr><td><?=H::e($row['stripe_event_id'])?></td><td><?=H::e($row['event_type'])?></td><td><?=H::e($row['processing_status'])?></td><td><?=empty($row['processing_error'])?'Failed processing':'Processing error recorded — review Payment / Stripe logs'?></td><td><?=H::e($row['created_at'])?></td></tr><?php endforeach;?></table></div><?php endif;?></section>
<?php endif;?>
