<?php use App\Core\Helpers as H; ?>
<h1><?=$mode==='credits'?'Marketplace Credits':'Referrals & Seller Referral Payouts'?></h1>
<?php if($mode==='credits'):?>
<p>Credit history is immutable. Adjustments create new audited ledger entries.</p>
<form method="get" action="/admin/credits" class="card form" role="search"><label>Search users<input name="q" value="<?=H::e($query)?>" maxlength="190"></label><button class="btn">Search</button></form>
<div class="responsive-table"><table><thead><tr><th>User</th><th>Total</th><th>Reserved</th><th>Available</th><th>Review</th></tr></thead><tbody><?php foreach($users as $user):?><tr><td><?=H::e($user['name'])?><br><small><?=H::e($user['email'])?></small></td><td><?=H::money($user['total_balance'])?></td><td><?=H::money($user['reserved_balance'])?></td><td><?=H::money($user['available_balance'])?></td><td><a href="/admin/credits?user_id=<?=(int)$user['id']?>">Review account</a></td></tr><?php endforeach;?><?php if(!$users):?><tr><td colspan="5">No matching users.</td></tr><?php endif;?></tbody></table></div>
<nav aria-label="User results pages"><a href="?q=<?=rawurlencode($query)?>&amp;page=<?=max(1,$page-1)?>">Previous</a> · <a href="?q=<?=rawurlencode($query)?>&amp;page=<?=$page+1?>">Next</a></nav>
<?php if($selected):?><section class="card"><h2><?=H::e($selected['name'])?></h2><p>Total <?=H::money($selected['total_balance'])?> · Reserved <?=H::money($selected['reserved_balance'])?> · Available <?=H::money($selected['available_balance'])?></p><?php if(H::canAdmin('credits.adjust')):?><form method="post" action="/admin/credits/adjust" class="form"><input type="hidden" name="_csrf" value="<?=H::csrf()?>"><input type="hidden" name="user_id" value="<?=(int)$selected['id']?>"><label>Adjustment amount<input name="amount" required inputmode="decimal" placeholder="10.00 or -5.00"></label><label>Reason<textarea name="reason" required minlength="3" maxlength="500"></textarea></label><button class="btn">Record adjustment</button></form><?php endif;?></section>
<h2>Selected user ledger</h2><div class="responsive-table"><table><thead><tr><th>Type</th><th>Amount</th><th>Status</th><th>Order</th><th>Referral</th><th>Related</th><th>Admin</th><th>Reason</th><th>Created</th></tr></thead><tbody><?php foreach($ledger as $entry):?><tr><td><?=H::e(ucwords(str_replace('_',' ',$entry['type'])))?></td><td><?=H::money($entry['amount'])?></td><td><?=H::e($entry['status'])?></td><td><?=$entry['order_id']?'#'.(int)$entry['order_id']:'—'?></td><td><?=$entry['referral_id']?'#'.(int)$entry['referral_id']:'—'?></td><td><?=$entry['related_transaction_id']?'#'.(int)$entry['related_transaction_id']:'—'?></td><td><?=H::e($entry['admin_name']??'—')?></td><td><?=H::e($entry['description']??'—')?></td><td><?=H::e($entry['created_at'])?></td></tr><?php endforeach;?><?php if(!$ledger):?><tr><td colspan="9">No credit activity.</td></tr><?php endif;?></tbody></table></div><?php endif;?>
<?php else:?>
<p>Referral reward and payout history is immutable.</p>
<h2>Seller-referral commission totals</h2><div class="responsive-table"><table><thead><tr><th>Referrer</th><th>Referred store</th><th>Eligibility</th><th>Unpaid</th><th>Paid</th><th>Recovery</th><th>Lifetime net</th></tr></thead><tbody><?php foreach($commissionTotals as $total):?><tr><td><?=H::e($total['referrer_name'])?></td><td><?=H::e($total['referred_store']??'Store unavailable')?></td><td><?=$total['commission_ended_at']?'Stopped '.H::e($total['commission_ended_at']):'Active'?></td><td><?=H::money(((int)$total['unpaid_cents'])/100)?></td><td><?=H::money(((int)$total['paid_cents'])/100)?></td><td><?=H::money(((int)$total['recovery_cents'])/100)?></td><td><?=H::money(((int)$total['lifetime_cents'])/100)?></td></tr><?php endforeach;?></tbody></table></div>
<h2>Monthly seller-referral payouts</h2><form method="get" action="/admin/referrals"><select name="payout_status"><option value="">All</option><?php foreach(['processing','paid','failed','not_ready'] as $status):?><option value="<?=$status?>" <?=$payoutStatus===$status?'selected':''?>><?=H::e($status)?></option><?php endforeach;?></select><button>Filter</button></form><div class="responsive-table"><table><thead><tr><th>Referrer</th><th>Period</th><th>Amount</th><th>Status</th><th>Transfer</th><th>Action</th></tr></thead><tbody><?php foreach($payouts as $batch):?><tr><td><?=H::e($batch['referrer_name'])?></td><td><?=H::e($batch['period_start'])?>–<?=H::e($batch['period_end'])?></td><td><?=H::money(((int)$batch['amount_cents'])/100)?></td><td><?=H::e($batch['status'])?></td><td><?=H::e($batch['stripe_transfer_id']??'—')?></td><td><?php if(H::canAdmin('payouts.manage')&&in_array($batch['status'],['failed','not_ready','processing'],true)):?><form method="post" action="/admin/seller-referral-payouts/<?=(int)$batch['id']?>/retry"><input type="hidden" name="_csrf" value="<?=H::csrf()?>"><button>Retry</button></form><?php else:?>—<?php endif;?></td></tr><?php endforeach;?></tbody></table></div>
<h3>Transfer-attempt history</h3><div class="responsive-table"><table><thead><tr><th>Batch</th><th>Status</th><th>Transfer</th><th>Attempted</th><th>Result</th></tr></thead><tbody><?php foreach($attempts as $attempt):?><tr><td>#<?=(int)$attempt['batch_id']?></td><td><?=H::e($attempt['status'])?></td><td><?=H::e($attempt['stripe_transfer_id']??'—')?></td><td><?=H::e($attempt['attempted_at'])?></td><td><?=H::e($attempt['failure_reason']??'—')?></td></tr><?php endforeach;?></tbody></table></div>
<h2>Matching referrals</h2><div class="responsive-table"><table><thead><tr><th>Referrer</th><th>Referred user</th><th>Buyer status</th><th>Seller status</th><th>Rewards</th></tr></thead><tbody><?php foreach($referrals as $referral):?><tr><td><?=H::e($referral['referrer_name'])?></td><td><?=H::e($referral['referred_name'])?></td><td><?=H::e($referral['buyer_status'])?></td><td><?=H::e($referral['seller_status'])?></td><td>Buyer <?=H::money($referral['buyer_referrer_reward_amount'])?> / Seller <?=H::money($referral['seller_referrer_reward_amount'])?></td></tr><?php endforeach;?></tbody></table></div>
<?php endif;?>
