<h1>Order #<?=$order['id']?>
</h1><section class="card"><h2>Payment breakdown</h2><p>Subtotal <?=H::money($order['subtotal'])?> · Coupon −<?=H::money($order['coupon_discount']??0)?> · Tax +<?=H::money($order['tax_amount']??0)?> · Credit −<?=H::money($order['credits_applied']??0)?> · Stripe paid <?=H::money($order['stripe_paid_amount']??0)?> · Final <?=H::money($order['total'])?></p><p>Credit: <?=H::e(['none'=>'Not used','reserved'=>'Reserved','finalized'=>'Redeemed','released'=>'Released'][$order['credit_payment_status']??'none']??'Unknown')?> · <?=!empty($order['internally_completed'])?'Internal store-credit completion':'Stripe completion'?></p></section>
<p>Buyer: <?=H::e($order['buyer_name'])?> (<?=H::e($order['buyer_email'])?>)</p>
<p>Status: <?=H::e($order['status'])?> · Payment: <strong><?=H::e($order['payment_status'] ?? $order['status'])?></strong> · Total: <?=H::money($order['total'])?>
</p>
<?php if(!empty($order['coupon_code'])):?><p>Coupon <?=H::e($order['coupon_code'])?> saved <?=H::money($order['coupon_discount'] ?? 0)?>. Commission is based on discounted item totals.</p><?php endif;?>
<section class="card">
  <h2>Tax details</h2>
  <p>Tax collected: <strong><?=H::money($order['tax_amount'] ?? 0)?></strong></p>
  <p>Provider: <?=H::e($order['tax_provider'] ?? 'stripe_tax')?></p>
  <p>Status: <?=H::e($order['tax_status'] ?? 'pending')?></p>
  <p>Calculation: <?=H::e($order['tax_calculation_id'] ?? 'Not created')?> · Transaction: <?=H::e($order['tax_transaction_id'] ?? 'Not created')?> (<?=H::e(ucfirst($order['tax_transaction_status'] ?? 'pending'))?>)</p>
  <p>Liability owner: <?=H::e($order['tax_liability_owner'] ?? 'platform')?></p>
  <?php if(!empty($order['tax_collected_at'])):?><p>Collected at: <?=H::e($order['tax_collected_at'])?></p><?php endif;?>
  <?php if(!empty($order['tax_snapshot'])):?><details><summary>Stripe tax snapshot/reference</summary><pre style="white-space:pre-wrap; overflow-wrap:anywhere;"><?=H::e($order['tax_snapshot'])?></pre></details><?php endif;?>
</section>
<?php if(!empty($order['internally_completed'])):?><p class="notice warning">Seller payouts for this platform-funded credit order are held as <strong>Platform credit — admin transfer required</strong>; no buyer Stripe source charge exists.</p><?php endif;?>
<section class="card"><h2>Seller financial snapshots</h2><table><tr><th>Seller</th><th>Gross before coupon</th><th>Coupon discount</th><th>Post-discount gross / basis</th><th>Percentage fee</th><th>Fixed fee</th><th>Total fee</th><th>Entitlement</th><th>Payout / transfer</th><th>Refund / post-refund</th><th>Recovery</th></tr><?php foreach(($sellerFinancial??[]) as $s):?><tr><td><?=H::e($s['seller_name'])?></td><td><?=H::money($s['pre_discount_gross'])?></td><td><?=H::money($s['coupon_discount'])?></td><td><?=H::money($s['gross_amount'])?></td><td><?=H::money($s['marketplace_percentage_fee_amount'])?></td><td><?=H::money($s['marketplace_fixed_fee_amount'])?></td><td><?=H::money($s['platform_commission_amount'])?></td><td><?=H::money($s['seller_payout_amount'])?></td><td><?=H::e(str_replace('_',' ',$s['payout_status']))?><br><?php if($s['transfer_amount_after_recovery']!==null):?>Actual transfer <?=H::money($s['transfer_amount_after_recovery'])?><?php else:?><span class="muted">Legacy transfer amount not separately snapshotted</span><?php endif;?><br><?=H::e($s['stripe_transfer_id']??'No transfer ID')?></td><td>Allocated <?=H::money(((int)$s['refunded_cents'])/100)?><br>Remaining entitlement <?=H::money($s['seller_payout_amount'])?></td><td>Required <?=H::money(((int)$s['recovery_amount_cents'])/100)?><br>Applied <?=H::money(((int)$s['recovery_applied_cents'])/100)?><br>Reserved <?=H::money(((int)$s['recovery_reserved_cents'])/100)?><br>Waived/resolved <?=H::money(((int)$s['recovery_closed_cents'])/100)?><br>Remaining <?=H::money(((int)$s['recovery_balance_cents'])/100)?></td></tr><?php endforeach;?></table></section>
<?php foreach(($refundObservations??[]) as $ob):?><?php if($ob['allocation_status']==='needs_allocation'):?><section class="card notice warning"><h2>Allocate refund observation #<?=(int)$ob['id']?></h2><p>Stripe event <?=H::e($ob['stripe_event_id'])?> has <strong><?=H::money(((int)$ob['refund_delta_cents'])/100)?></strong> outstanding. Merchandise plus tax must equal this amount exactly. Tax never changes seller earnings.</p><?php if(H::canAdmin('orders.manage')):?><form method="post"><input type="hidden" name="_csrf" value="<?=H::csrf()?>"><input type="hidden" name="action" value="allocate_refund"><input type="hidden" name="refund_observation_id" value="<?=(int)$ob['id']?>"><?php foreach(($refundAllocations??[]) as $r):?><label><?=H::e($r['product_title']??('Item #'.$r['id']))?> — original <?=H::money($r['total_price'])?>, previously refunded <?=H::money(((int)$r['refunded_cents'])/100)?><input type="number" min="0" max="<?=max(0,(int)round((float)$r['total_price']*100)-(int)$r['refunded_cents'])?>" name="refund_cents[<?=(int)$r['id']?>]" value="0"></label><?php endforeach;?><label>Refunded tax cents<input type="number" min="0" name="tax_refund_cents" value="0"></label><button>Validate, allocate, and reconcile</button></form><?php endif;?></section><?php elseif($ob['allocation_status']==='allocated'):?><section class="card notice warning"><h2>Refund observation #<?=(int)$ob['id']?> awaits reconciliation</h2><p>The exact item/tax allocation is already stored. Do not allocate it again.</p><?php if(H::canAdmin('orders.manage')):?><form method="post"><input type="hidden" name="_csrf" value="<?=H::csrf()?>"><input type="hidden" name="action" value="retry_refund_reconciliation"><input type="hidden" name="refund_observation_id" value="<?=(int)$ob['id']?>"><button>Retry stored reconciliation</button></form><?php endif;?></section><?php endif;?><?php endforeach;?>
<section class="card"><h2>Stripe payment details</h2><p>Provider: <?=H::e($order['payment_provider'] ?? $order['payment_processor'] ?? "")?> · Session: <?=H::e($order['stripe_checkout_session_id'] ?? "")?> · Intent: <?=H::e($order['stripe_payment_intent_id'] ?? "")?> · Charge: <?=H::e($order['stripe_charge_id'] ?? "")?></p><p>Stripe amount: <?=H::e($order['stripe_amount_total'] ?? "")?> <?=H::e(strtoupper($order['stripe_currency'] ?? ""))?> · Paid: <?=H::e($order['paid_at'] ?? "")?> · Failed: <?=H::e($order['failed_at'] ?? "")?> · Refunded: <?=H::e($order['refunded_at'] ?? "")?></p><p>Manual review: <?=!empty($order['manual_review_required'])?'Required':'No'?> <?=H::e($order['manual_review_reason'] ?? "")?></p><p><a href="/admin/payment-logs">View all payment logs</a></p></section>
<table>
    <tr>
        <th>Product</th>
        <th>Designer</th>
        <th>Purchased permissions</th>
        <th>Item Total</th>
        <th>Marketplace fee</th>
        <th>Seller Payout</th><th>Payout Status</th><th>Fulfillment</th><th>Admin override</th>
    </tr>
    <?php foreach($items as $i):?>
        <tr>
           <td>
           <?=H::e($i['title'])?>
           </td>
           <td>
           <?=H::e($i['designer_name'])?> (<?=H::e($i['designer_email'])?>)</td>
           <td>
           <?=H::e($i['license_name'] ?: $i['license_type'])?><?php if(!empty($i['license_description'])):?><br><span class="muted"><?=H::e($i['license_description'])?></span><?php endif;?>
           </td>
           <td>
           <?=H::money($i['total_price'])?>
           </td>
           <td>
           <?=H::money($i['platform_commission_amount']??$i['commission_amount']??($i['total_price']*$i['commission_rate']))?><br><span class="muted">Percentage <?=H::money($i['marketplace_percentage_fee_amount']??0)?> · Fixed <?=H::money($i['marketplace_fixed_fee_amount']??0)?></span>
           </td>
           <td>
           <?=H::money($i['seller_payout_amount'] ?? $i['seller_earning'] ?? ($i['total_price']-($i['total_price']*$i['commission_rate'])))?>
           </td>
           <td><?=H::e(str_replace('_', ' ', $i['ledger_payout_status'] ?? $i['seller_payout_status'] ?? 'pending_payment'))?><?php if(!empty($i['ledger_transfer_error']) || !empty($i['stripe_transfer_error'])):?><br><span class="badge no">transfer failed</span><br><span class="muted"><?=H::e($i['ledger_transfer_error'] ?? $i['stripe_transfer_error'])?></span><?php endif;?><br><span class="muted">Stripe: <?=H::e($i['stripe_account_status'] ?? 'not_connected')?> / <?=(!empty($i['stripe_details_submitted']) && !empty($i['stripe_payouts_enabled'])) ? 'payout-ready' : 'not payout-ready / onboarding incomplete'?></span><?php if(($i['ledger_payout_status'] ?? '') === 'platform_credit_hold' && !empty($i['seller_payout_id'])):?><?php if(H::canAdmin('payouts.manage')):?><form method="post" action="/admin/platform-credit-payouts/<?=(int)$i['seller_payout_id']?>/settle"><input type="hidden" name="_csrf" value="<?=H::csrf()?>"><button type="submit">Transfer from platform balance</button></form><?php endif;?><?php elseif(!empty($i['platform_credit_settled_at'])):?><br><span class="muted">Settled <?=H::e($i['platform_credit_settled_at'])?></span><?php endif;?></td>
           <td><?=H::e($i['fulfillment_type'] ?? 'downloadable')?><?php if(($i['fulfillment_type'] ?? '')==='google_drive'):?><br>Email: <?=H::e($i['buyer_google_drive_email'] ?: 'Needed')?><br>Status: <?=H::e(str_replace('_',' ', $i['manual_delivery_status']))?><?php endif;?></td>
           <td><?php if(($i['fulfillment_type'] ?? '')==='google_drive'):?><?php if(H::canAdmin('orders.manage')):?><form method="post"><input type="hidden" name="_csrf" value="<?=H::csrf()?>"><input type="hidden" name="action" value="override_fulfillment"><input type="hidden" name="order_item_id" value="<?=$i['id']?>"><select name="manual_delivery_status"><?php foreach(['pending_delivery','buyer_email_needed','ready_for_seller_delivery','delivered','cancelled_refunded'] as $st):?><option value="<?=$st?>" <?=$i['manual_delivery_status']===$st?'selected':''?>><?=H::e(str_replace('_',' ',$st))?></option><?php endforeach;?></select><input name="delivery_notes" value="<?=H::e($i['delivery_notes'] ?? '')?>"><button>Update</button></form><?php endif;?><?php endif;?></td>
        </tr>
    <?php endforeach;?>
</table>
<h2>Seller refund adjustments and recoveries</h2><table><tr><th>Seller</th><th>Type</th><th>Original</th><th>Applied</th><th>Reserved</th><th>Remaining</th><th>Status</th><th>Note / action</th></tr><?php foreach(($adjustments??[]) as $a):?><tr><td><?=H::e($a['seller_name'])?></td><td><?=H::e(str_replace('_',' ',$a['adjustment_type']))?></td><td><?=H::money(((int)($a['original_amount_cents']??$a['amount_cents']))/100)?></td><td><?=H::money(((int)($a['applied_cents']??0))/100)?></td><td><?=H::money(((int)($a['reserved_cents']??0))/100)?></td><td><?=H::money(((int)$a['balance_cents'])/100)?></td><td><?=H::e($a['status'])?></td><td><?=H::e($a['note']??'')?><?php if($a['status']==='open'&&(int)($a['reserved_cents']??0)===0&&in_array($a['adjustment_type'],['refund_recovery','manual_recovery'],true)):?><?php if(H::canAdmin('orders.manage')):?><form method="post"><input type="hidden" name="_csrf" value="<?=H::csrf()?>"><input type="hidden" name="adjustment_id" value="<?=(int)$a['id']?>"><input name="resolution_note" maxlength="500" required placeholder="Resolution note"><button name="action" value="resolve_adjustment">Resolve</button><button name="action" value="waive_adjustment">Waive</button></form><?php endif;?><?php endif;?></td></tr><?php endforeach;?><?php if(empty($adjustments)):?><tr><td colspan="8" class="muted">No seller financial adjustments.</td></tr><?php endif;?></table>
<p>
<a href="/admin/orders">Back to orders</a>
</p>

<h2>Order payment transactions</h2><table><tr><th>Type</th><th>Status</th><th>Amount</th><th>Message</th><th>Date</th></tr><?php foreach(($transactions ?? []) as $t):?><tr><td><?=H::e($t['transaction_type'])?></td><td><?=H::e($t['payment_status'])?></td><td><?=H::money($t['amount'])?> <?=H::e(strtoupper($t['currency']))?></td><td><?=H::e($t['message'] ?? '')?></td><td><?=$t['created_at']?></td></tr><?php endforeach;?></table>
