<h1>Review Moderation</h1>
<form method="get" class="card">
  <label>ID / order / item <input name="q" value="<?=H::e($filters['q'])?>"></label><label>Buyer <input name="buyer" value="<?=H::e($filters['buyer'])?>"></label><label>Seller <input name="seller" value="<?=H::e($filters['seller'])?>"></label><label>Product <input name="product" value="<?=H::e($filters['product'])?>"></label>
  <label>Rating <select name="rating"><option value="">All</option><?php for($n=1;$n<=5;$n++):?><option value="<?=$n?>" <?=$filters['rating']===(string)$n?'selected':''?>><?=$n?></option><?php endfor;?></select></label>
  <label>From <input type="date" name="date_from" value="<?=H::e($filters['date_from'])?>"></label><label>To <input type="date" name="date_to" value="<?=H::e($filters['date_to'])?>"></label>
  <label>Reported <select name="reported"><option value="">All</option><option value="yes" <?=$filters['reported']==='yes'?'selected':''?>>Reported</option><option value="no" <?=$filters['reported']==='no'?'selected':''?>>Not reported</option></select></label>
  <label>Status <select name="status"><option value="">All statuses</option><?php foreach(['published'=>'Published','under_review'=>'Under Review','removed'=>'Removed by Admin'] as $v=>$label):?><option value="<?=$v?>" <?=$filters['status']===$v?'selected':''?>><?=$label?></option><?php endforeach;?></select></label><button>Filter</button>
</form>
<?php foreach($reviews as $r):?><article class="card">
  <h2>Review #<?=(int)$r['id']?> — <?=H::e($r['product_title_snapshot'])?></h2><dl><dt>Buyer</dt><dd><?=H::e($r['buyer_name_snapshot'])?></dd><dt>Seller</dt><dd><?=H::e($r['seller_name_snapshot'])?></dd><dt>Order / item</dt><dd>#<?=(int)$r['order_id']?> / #<?=(int)$r['order_item_id']?></dd><dt>Rating</dt><dd><?=(int)$r['rating']?> / 5</dd><dt>Submitted</dt><dd><?=H::e($r['reviewed_at'])?></dd><dt>Edited</dt><dd><?=H::e($r['edited_at']??'Never')?></dd><dt>Moderation</dt><dd><?=H::e($r['moderation_status'])?></dd></dl>
  <p><?=nl2br(H::e($r['review_text']??''))?></p>
  <?php if($r['reply_text']):?><aside><strong>Seller reply (<?=H::e($r['reply_moderation_status'])?>)</strong><p><?=nl2br(H::e($r['reply_text']))?></p><small><?=H::e($r['reply_created_at'])?><?php if(strtotime($r['reply_updated_at'])>strtotime($r['reply_created_at'])):?> · Edited<?php endif;?></small></aside><?php endif;?>
  <?php foreach($reports[(int)$r['id']]??[] as $report):?><section><h3>Report #<?=(int)$report['id']?> — <?=H::e($report['status'])?></h3><p><?=H::e($report['reason'])?>: <?=nl2br(H::e($report['details']??''))?></p><p>Admin note: <?=H::e($report['admin_note']??'Not reviewed')?> · Reviewed: <?=H::e($report['reviewed_at']??'No')?></p><?php if(H::canAdmin('reviews.manage')):?><form method="post"><input type="hidden" name="_csrf" value="<?=H::csrf()?>"><input type="hidden" name="operation" value="report"><input type="hidden" name="report_id" value="<?=(int)$report['id']?>"><select name="report_status"><option value="reviewing">Reviewing</option><option value="reviewed">Reviewed</option><option value="no_action">No Action</option><option value="resolved">Resolved</option></select><textarea name="internal_note" required maxlength="2000" placeholder="Required Admin note"></textarea><button>Update Report</button></form><?php endif;?></section><?php endforeach;?>
  <?php if(H::canAdmin('reviews.manage')):?><form method="post"><input type="hidden" name="_csrf" value="<?=H::csrf()?>"><input type="hidden" name="operation" value="review"><input type="hidden" name="review_id" value="<?=(int)$r['id']?>"><select name="action"><option value="under_review">Under Review</option><option value="removed">Remove by Admin</option><option value="restored">Restore</option></select><input name="reason" maxlength="500" required placeholder="Required reason"><textarea name="internal_note" maxlength="2000" required placeholder="Required internal note"></textarea><button>Moderate Review</button></form>
  <?php if($r['reply_id']):?><form method="post"><input type="hidden" name="_csrf" value="<?=H::csrf()?>"><input type="hidden" name="operation" value="reply"><input type="hidden" name="reply_id" value="<?=(int)$r['reply_id']?>"><select name="action"><option value="removed">Remove Reply</option><option value="restored">Restore Reply</option></select><input name="reason" maxlength="500" required placeholder="Required reason"><textarea name="internal_note" maxlength="2000" required placeholder="Required internal note"></textarea><button>Moderate Seller Reply</button></form><?php endif;?><?php endif;?>
</article><?php endforeach;?>
