<?php
use App\Core\Helpers as H;
$role=H::user()['role'] ?? '';
$area=($path==='/notifications'||$path==='/account') ? ($role==='admin'?'admin':($role==='designer'?'seller':'buyer')) : (str_starts_with($path,'/admin')?'admin':(str_starts_with($path,'/seller')?'seller':'buyer'));
$links=[];
if($area==='buyer') $links=[['/dashboard','Overview',['/dashboard']],['/dashboard/purchases','Purchases',['/dashboard/purchases','/dashboard/order/']],['/dashboard/downloads','Downloads',['/dashboard/downloads']],['/dashboard/wishlist','Wishlist',['/dashboard/wishlist']],['/dashboard/following','Following',['/dashboard/following']],['/dashboard/referrals','Referrals',['/dashboard/referrals']],['/account','Account',['/account']],['/notifications','Notifications',['/notifications']]];
elseif($area==='seller'&&in_array($role,['designer','admin'],true)) $links=[['/seller','Seller overview',['/seller']],['/seller/onboarding','Readiness',['/seller/onboarding']],['/seller/products','Products',['/seller/products','/seller/product/']],['/seller/sales','Sales / orders',['/seller/sales','/seller/order-item/']],['/seller/store','Store & licenses',['/seller/store']],['/seller/receipt-settings','Receipts',['/seller/receipt-settings']],['/seller/stripe','Payouts / Stripe',['/seller/stripe']],['/seller/coupons','Coupons',['/seller/coupons']],['/seller/referrals','Referrals',['/seller/referrals']],['/seller/rank','Rank',['/seller/rank']],['/account','Account',['/account']],['/notifications','Notifications',['/notifications']]];
elseif($area==='admin'&&$role==='admin') $links=[['/admin','Admin overview',['/admin']],['/admin/users','Users',['/admin/users']],['/admin/applications','Applications',['/admin/applications','/admin/applications/']],['/admin/designers','Sellers',['/admin/designers']],['/admin/products','Products',['/admin/products','/admin/products/']],['/admin/ip-risk-terms','IP Risk Terms',['/admin/ip-risk-terms','/admin/ip-risk-terms/']],['/admin/categories','Categories',['/admin/categories']],['/admin/coupons','Coupons',['/admin/coupons','/admin/coupons/']],['/admin/orders','Orders',['/admin/orders','/admin/order/']],['/admin/referrals','Credits & Referrals',['/admin/referrals','/admin/credits']],['/admin/homepage','Homepage',['/admin/homepage']],['/admin/ads','Ads',['/admin/ads']],['/admin/payment-logs','Payments / Stripe',['/admin/payment-logs']],['/admin/waitlist','Waitlist',['/admin/waitlist']],['/admin/email-campaigns','Email campaigns',['/admin/email-campaigns','/admin/email-campaigns/']],['/account','Account',['/account']],['/notifications','Notifications',['/notifications']]];
$isActive=static function(array $matches)use($path):bool{foreach($matches as $match){if($path===$match||str_ends_with($match,'/')&&str_starts_with($path,$match))return true;}return false;};
?>
<?php if($links):?><nav class="dashboard-nav" aria-label="Dashboard sections"><?php foreach($links as [$href,$label,$matches]):$active=$isActive($matches);?><a href="<?=$href?>" class="<?=$active?'active':''?>"<?=$active?' aria-current="page"':''?>><?=H::e($label)?></a><?php endforeach;?></nav><?php endif;?>
