<?php
use App\Core\Database as DB;
use App\Services\SocialCredentialCipher;

function runPhase136ApprovalWorkflowScenarios(PDO $pdo, callable $check): void
{
    $token=bin2hex(random_bytes(6));$userIds=[];$sellerId=0;$productIds=[];$batchId=0;$categoryId=0;$termId=0;
    $run=function(string $mode,int $productId,int $userId,string $role='designer',int $batch=0,string $title='')use(&$categoryId):void{
        $env=['APP_ENV'=>'test','RUN_DISPOSABLE_DB_TESTS'=>'1','PHASE136_WORKFLOW'=>$mode,'PHASE136_PRODUCT_ID'=>(string)$productId,'PHASE136_USER_ID'=>(string)$userId,'PHASE136_ROLE'=>$role,'PHASE136_BATCH_ID'=>(string)$batch,'PHASE136_TITLE'=>$title,'PHASE136_CATEGORY_ID'=>(string)$categoryId,'SOCIAL_CREDENTIAL_ENCRYPTION_KEY'=>$_ENV['SOCIAL_CREDENTIAL_ENCRYPTION_KEY'],'APP_URL'=>'https://market.test'];
        $parts=[];foreach($env as $key=>$value)$parts[]=$key.'='.escapeshellarg($value);$command=implode(' ',$parts).' '.escapeshellarg(PHP_BINARY).' '.escapeshellarg(__DIR__.'/Phase136WorkflowRunner.php');exec($command,$output,$code);if($code!==0)throw new RuntimeException("Production workflow $mode exited with $code.");
    };
    try{
        $pdo->beginTransaction();
        DB::exec('insert into users(name,email,password_hash,role,status) values(?,?,?,?,"active")',['Workflow Seller','phase136-workflow-'.$token.'@example.test','x','designer']);$sellerUser=(int)DB::id();$userIds[]=$sellerUser;
        DB::exec('insert into users(name,email,password_hash,role,status) values(?,?,?,?,"active")',['Workflow Admin','phase136-admin-'.$token.'@example.test','x','admin']);$adminUser=(int)DB::id();$userIds[]=$adminUser;
        DB::exec('insert into admin_access_profiles(user_id,full_access,granted_by) values(?,1,?)',[$adminUser,$adminUser]);
        DB::exec('insert into categories(name,slug,description,is_active) values(?,?,?,1)',['Phase 13.6 Workflow','phase136-workflow-category-'.$token,'Disposable workflow category']);$categoryId=(int)DB::id();
        DB::exec('insert into ip_risk_terms(term,normalized_term,category,internal_note,is_enabled,created_by_admin_id,updated_by_admin_id) values(?,?,"brand",?,1,?,?)',['Phase136 Risk '.$token,'phase136 risk '.$token,'Disposable workflow term',$adminUser,$adminUser]);$termId=(int)DB::id();
        DB::exec('insert into designers(user_id,display_name,store_slug,bio,status,stripe_connect_account_id,stripe_payouts_enabled,stripe_details_submitted) values(?,?,?,? ,"approved","acct_test",1,1)',[$sellerUser,'Workflow Shop','phase136-workflow-'.$token,'Phase 13.6 workflow fixture biography.']);$sellerId=(int)DB::id();
        $credential=SocialCredentialCipher::encrypt(['access_token'=>'workflow-page-token','user_access_token'=>'workflow-user-token']);DB::exec('insert into seller_social_connections(designer_id,platform,external_account_id,external_account_name,encrypted_credentials,connection_status,auto_post_enabled,connected_at) values(?,"facebook","workflow-page","Workflow Page",?,"connected",1,now())',[$sellerId,$credential]);DB::exec('update social_platform_integrations set is_enabled=1,disabled_reason=null where platform="facebook"');
        $make=function(string $status,string $suffix)use($sellerId,$token,$categoryId,&$productIds){DB::exec('insert into products(designer_id,category_id,title,slug,description,price,fulfillment_type,ai_disclosure,status) values(?,?,?,?,?, ?,"downloadable","No AI Used",?)',[$sellerId,$categoryId,'Workflow '.$suffix,'phase136-workflow-'.$token.'-'.$suffix,'Phase 13.6 workflow description',10,$status]);$id=(int)DB::id();$productIds[]=$id;DB::exec('insert into product_images(product_id,image_path,sort_order) values(?,?,0)',[$id,'/uploads/workflow-'.$suffix.'.jpg']);DB::exec('insert into product_files(product_id,storage_path,original_name,file_size,mime_type) values(?,?,?,?,?)',[$id,'workflow/'.$suffix.'.zip',$suffix.'.zip',10,'application/zip']);return$id;};
        $adminProduct=$make('pending_review','admin');$ipProduct=$make('pending_review','ip');$singleProduct=$make('draft','single');$batchProduct=$make('draft','batch');$saveProduct=$make('pending_review','save');
        DB::exec('insert into product_batches(designer_id,name) values(?,?)',[$sellerId,'Workflow Batch']);$batchId=(int)DB::id();DB::exec('insert into product_batch_items(batch_id,product_id,sort_order) values(?,?,1)',[$batchId,$batchProduct]);
        DB::exec('insert into product_ip_risk_scans(product_id,seller_id,content_fingerprint,match_fingerprint,active_match_count,scanned_at) values(?,?,?, ?,1,now())',[$ipProduct,$sellerUser,str_repeat('a',64),str_repeat('b',64)]);$scan=(int)DB::id();DB::exec('insert into product_ip_risk_detections(product_id,scan_id,ip_risk_term_id,matched_term,matched_value_key,category,source_field,is_active,first_detected_at,last_detected_at) values(?,?,?,?,?,?,"title",1,now(),now())',[$ipProduct,$scan,$termId,'fixture','fixture','brand']);DB::exec('insert into product_ip_risk_states(product_id,latest_scan_id,review_status,latest_match_fingerprint) values(?, ?,"pending_review",?)',[$ipProduct,$scan,str_repeat('b',64)]);
        $pdo->commit();
        foreach([['admin',$adminProduct,$adminUser,'admin',0,'Workflow admin'],['ip',$ipProduct,$adminUser,'admin',0,'Workflow ip'],['single',$singleProduct,$sellerUser,'designer',0,'Workflow single'],['batch',$batchProduct,$sellerUser,'designer',$batchId,'Workflow batch'],['seller_save',$saveProduct,$sellerUser,'designer',0,'Workflow save']] as [$mode,$product,$user,$role,$batch,$title]){
            $run($mode,$product,$user,$role,$batch,$title);$row=DB::row('select status from products where id=?',[$product]);$count=(int)(DB::row('select count(*) c from social_post_logs where product_id=? and platform="facebook" and trigger_type="automatic"',[$product])['c']??0);$check(in_array($row['status']??'', ['approved','published'],true)&&$count===1,"real $mode production workflow publishes and dispatches exactly once");$run($mode,$product,$user,$role,$batch,$title);$repeat=(int)(DB::row('select count(*) c from social_post_logs where product_id=? and platform="facebook" and trigger_type="automatic"',[$product])['c']??0);$check($repeat===1,"real $mode repeat/edit does not duplicate automatic posting");
        }
    }finally{
        if($pdo->inTransaction())$pdo->rollBack();$pdo->beginTransaction();
        if($productIds){$marks=implode(',',array_fill(0,count($productIds),'?'));DB::exec("delete from notifications where user_id in (?,?)",$userIds);DB::exec("delete from social_post_logs where product_id in ($marks)",$productIds);DB::exec("delete from product_ip_rights_confirmations where product_id in ($marks)",$productIds);DB::exec("delete from product_ip_risk_review_history where product_id in ($marks)",$productIds);DB::exec("delete from product_ip_risk_detections where product_id in ($marks)",$productIds);DB::exec("delete from product_ip_risk_states where product_id in ($marks)",$productIds);DB::exec("delete from product_ip_risk_scans where product_id in ($marks)",$productIds);DB::exec("delete from product_batch_items where product_id in ($marks)",$productIds);if($batchId)DB::exec('delete from product_batches where id=?',[$batchId]);DB::exec("delete from product_license_types where product_id in ($marks)",$productIds);DB::exec("delete from product_tags where product_id in ($marks)",$productIds);DB::exec("delete from product_files where product_id in ($marks)",$productIds);DB::exec("delete from product_images where product_id in ($marks)",$productIds);DB::exec("delete from admin_logs where entity_type=\"product\" and entity_id in ($marks)",$productIds);DB::exec("delete from products where id in ($marks)",$productIds);}
        DB::exec('delete from email_messages where recipient_email in (?,?)',['phase136-workflow-'.$token.'@example.test','phase136-admin-'.$token.'@example.test']);if($sellerId){DB::exec('delete from seller_social_connections where designer_id=?',[$sellerId]);DB::exec('delete from designers where id=?',[$sellerId]);}if($termId){DB::exec('delete from ip_risk_term_aliases where ip_risk_term_id=?',[$termId]);DB::exec('delete from ip_risk_terms where id=?',[$termId]);}if($categoryId)DB::exec('delete from categories where id=?',[$categoryId]);if($userIds){DB::exec('delete from admin_access_profiles where user_id=?',[$userIds[1]]);DB::exec('delete from users where id in (?,?)',$userIds);}$pdo->commit();
    }
}
