<h1><?=H::e($title)?></h1>
<?php if($page === 'about'): ?>
<section class="card"><h2>What Asset Moth is</h2><p>Asset Moth is a digital design marketplace for buyers who need downloadable creative files and for independent designers who want a reviewed storefront for their work.</p><p>Buyers can browse categories, view product license details, and purchase digital files. Designers can apply to sell, manage a storefront, upload product previews and protected files, and submit products for review.</p></section>
<section class="card"><h2>Explore the marketplace</h2><p><a href="/browse">Browse products</a>, learn how to <a href="/sell">sell on Asset Moth</a>, read the <a href="/buyer-faq">Buyer FAQ</a>, visit the <a href="/seller-faq">Seller FAQ</a>, or <a href="/contact">contact support</a>.</p></section>
<?php elseif($page === 'contact'): ?>
<section class="card"><h2>Support guidance</h2><p>For product, license, account, order, or download questions, start with the relevant FAQ and include clear details when requesting help.</p><ul><li>Buyers: review <a href="/buyer-faq">Buyer FAQ</a> and <a href="/licensing-help">Licensing Help</a>.</li><li>Sellers: review <a href="/seller-faq">Seller FAQ</a> and product review expectations.</li><li>Orders/downloads: log in and check dashboard purchases and downloads.</li></ul><p>If you still need help, include the product or order details, your account email, the page URL involved, and a clear description of the issue when you contact support.</p></section>
<?php elseif($page === 'terms'): ?>
<section class="card"><h2>Using the marketplace</h2><p>These terms describe practical expectations for using Asset Moth. Users are responsible for accurate account information, lawful activity, and respecting intellectual property.</p><h2>Purchases and downloads</h2><p>Products are digital downloads. Buyers receive access through protected account download routes after checkout. Digital resale, redistribution, file sharing, or claiming a designer's work as your own is prohibited.</p><h2>Licenses</h2><p>Product pages show personal use, commercial license availability, POD permission, file types, and AI disclosure where applicable. Buyers must follow the license shown on the product page.</p><h2>Seller responsibilities</h2><p>Designers must upload original work or work they have rights to sell, provide accurate descriptions and previews, disclose AI use, and submit products for review. The marketplace may moderate, reject, disable, or remove listings that appear unsafe, infringing, misleading, or incomplete.</p><h2>Prohibited content and accounts</h2><p>Users may not upload infringing, deceptive, harmful, illegal, or rights-violating content. Accounts may be restricted when marketplace rules, security, or legal rights are at risk.</p><h2>Refunds and support</h2><p>Because products are digital files, refund and support requests are reviewed based on the issue reported, order details, download or access problems, duplicate purchase concerns, file problems, and the license information shown on the product page.</p><h2>Changes and contact</h2><p>Terms may be updated as marketplace operations mature. For questions, visit <a href="/contact">Contact</a>.</p></section>
<?php elseif($page === 'privacy'): ?>
<section class="card"><h2>Information collected</h2><p>Asset Moth collects information users provide when creating accounts, submitting designer applications, managing storefronts, listing products, placing orders, downloading files, wishlisting products, following stores, or contacting support.</p><h2>Order, seller, and technical information</h2><p>The application stores account records, order and order item data, download audit information, seller application data, product uploads, and basic technical details such as IP address and user agent for protected download logging.</p><h2>How information is used</h2><p>Information is used to operate accounts, review applications and products, process marketplace orders, deliver protected downloads, protect security, troubleshoot issues, and improve marketplace content.</p><h2>Cookies and sessions</h2><p>The site uses session cookies for login, CSRF protection, and account workflows. Additional analytics or advertising cookies should only be described here after they are actually configured.</p><h2>Sharing and protection</h2><p>Information may be shared when needed to operate the marketplace, comply with law, investigate abuse, or protect rights. Access should be limited to authorized roles, and private downloads are not served directly from public folders.</p><h2>User choices</h2><p>Users can manage account details when logged in and request help through the Contact page. This policy may be updated as marketplace operations, security needs, or legal requirements change.</p></section>
<?php elseif($page === 'licensing-help'): ?>
<section class="card"><h2>Personal and commercial use</h2><p>Personal use is intended for non-commercial projects. If a product offers a commercial license, buyers may select it during purchase for qualifying business use shown on the product page.</p><h2>POD permission</h2><p>Product pages show whether print-on-demand use is allowed. If POD is not allowed, do not upload the design to POD services or use it on products sold through POD workflows.</p><h2>Allowed examples</h2><ul><li>Use a purchased SVG in a personal craft project.</li><li>Use a commercial-license product in business marketing when the listing allows it.</li><li>Use POD only when the product page says POD is allowed.</li></ul><h2>Not allowed</h2><ul><li>Resell, share, give away, or redistribute downloaded files.</li><li>Claim a designer's work as your own.</li><li>Use a product outside the permissions shown on its page.</li></ul><p>See the <a href="/buyer-faq">Buyer FAQ</a>, <a href="/seller-faq">Seller FAQ</a>, <a href="/terms">Terms</a>, or <a href="/browse">browse designs</a>.</p></section>
<?php elseif($page === 'buyer-faq'): ?>
<section class="card"><h2>Buyer questions</h2><h3>How do I find products?</h3><p>Use <a href="/browse">Browse</a>, category pages, and product search filters.</p><h3>Do I need an account?</h3><p>An account is used for checkout, purchases, protected downloads, wishlists, and follows.</p><h3>Where are downloads?</h3><p>After checkout, log in and visit dashboard purchases or downloads.</p><h3>Can I use files commercially or for POD?</h3><p>Only when the product page and selected license allow it. Read <a href="/licensing-help">Licensing Help</a>.</p><h3>What if a file is missing or unclear?</h3><p>Use the <a href="/contact">Contact</a> page and include your order details, product name, account email, and a clear description of the missing file, unclear license, or download problem.</p><h3>Are refunds automatic?</h3><p>Refunds are not automatic. Digital product concerns are reviewed based on order details, download/access issues, duplicate purchase concerns, file problems, and the license information shown before purchase.</p></section>
<?php elseif($page === 'seller-faq'): ?>
<section class="card"><h2>Seller questions</h2><h3>How do I apply?</h3><p>Create or log in to an account and submit the <a href="/apply">designer application</a>.</p><h3>Is approval guaranteed?</h3><p>No. Applications are manually reviewed before seller access is granted.</p><h3>What can approved sellers manage?</h3><p>Approved sellers can manage storefront details, upload preview images and protected files, set product title, descriptions, SEO fields, categories, tags, file types, license settings, POD permission, and AI disclosure.</p><h3>Are products reviewed?</h3><p>Yes. Products can be draft, pending review, approved, rejected, or disabled.</p><h3>What content is expected?</h3><p>Only upload original work or files you have the right to sell. Copyright, trademark, misleading, or incomplete listings may be rejected or disabled.</p><h3>Where can I get help?</h3><p>Read <a href="/licensing-help">Licensing Help</a>, <a href="/terms">Terms</a>, or <a href="/contact">Contact</a>.</p></section>
<?php endif; ?>
