<?php
namespace App\Controllers;
use App\Core\Database as DB; use App\Core\Helpers as H;
class AdminController { private function gate(){H::requireRole('admin');}
 public function home(){ $this->gate(); H::view('admin/home',['s'=>DB::row('select (select count(*) from users) users,(select count(*) from designers) designers,(select count(*) from designer_applications where status="pending") apps,(select count(*) from products where status="pending_review") products,(select count(*) from orders) orders,(select coalesce(sum(total),0) from orders) gross,(select coalesce(sum(commission_amount),0) from platform_commissions) commission')]);}
 public function users(){ $this->gate(); if($_POST) DB::exec('update users set status=? where id=?',[$_POST['status'],$_POST['id']]); H::view('admin/table',['title'=>'Users','rows'=>DB::rows('select id,name,email,role,status,created_at from users order by created_at desc')]);}
 public function applications(){ $this->gate(); if($_POST){$a=DB::row('select * from designer_applications where id=?',[$_POST['id']]); if($_POST['action']==='approve'){DB::exec('update designer_applications set status="approved",admin_notes=? where id=?',[$_POST['reason']??'',$a['id']]); DB::exec('insert into designers (user_id,display_name,store_slug,bio,social_links,status,creator_rank) values (?,?,?,?,?,?,?)',[$a['user_id'],$a['display_name'],$a['desired_slug'],$a['bio'],$a['social_links'],'approved','Bronze']); DB::exec('update users set role="designer" where id=?',[$a['user_id']]);} else DB::exec('update designer_applications set status="denied",denial_reason=? where id=?',[$_POST['reason'],$a['id']]);} H::view('admin/applications',['apps'=>DB::rows('select da.*,u.email from designer_applications da join users u on u.id=da.user_id order by da.created_at desc')]);}
 public function designers(){ $this->gate(); if($_POST) DB::exec('update designers set creator_rank=? where id=?',[$_POST['creator_rank'],$_POST['id']]); H::view('admin/designers',['designers'=>DB::rows('select d.*,u.email from designers d join users u on u.id=d.user_id')]);}
 public function products(){ $this->gate(); if($_POST){$status=$_POST['action']==='approve'?'approved':($_POST['action']==='disable'?'disabled':'rejected'); DB::exec('update products set status=?, rejection_reason=?, updated_at=now() where id=?',[$status,$_POST['reason']??'',$_POST['id']]);} H::view('admin/products',['products'=>DB::rows('select p.*,d.display_name from products p join designers d on d.id=p.designer_id order by p.updated_at desc')]);}
 public function categories(){ $this->gate(); if($_POST) DB::exec('insert into categories (name,slug,description,is_active) values (?,?,?,1) on duplicate key update name=values(name),description=values(description),is_active=values(is_active)',[$_POST['name'],H::slug($_POST['slug']),$_POST['description']]); H::view('admin/categories',['cats'=>DB::rows('select * from categories')]);}
 public function orders(){ $this->gate(); H::view('admin/table',['title'=>'Orders','rows'=>DB::rows('select * from orders order by created_at desc')]);}
 public function referrals(){ $this->gate(); H::view('admin/table',['title'=>'Referrals','rows'=>DB::rows('select * from referrals order by created_at desc')]);}
 public function homepage(){ $this->gate(); if($_POST){DB::exec('insert into homepage_features (feature_type,feature_id,sort_order,is_active) values (?,?,?,1)',[$_POST['feature_type'],$_POST['feature_id'],$_POST['sort_order']]);} H::view('admin/homepage',['features'=>DB::rows('select * from homepage_features')]);}
 public function ads(){ $this->gate(); if($_POST) DB::exec('insert into ads (product_id,designer_id,placement,start_date,end_date,status) values (?,?,?,?,?,?)',[$_POST['product_id'],$_POST['designer_id'],$_POST['placement'],$_POST['start_date'],$_POST['end_date'],$_POST['status']]); H::view('admin/ads',['ads'=>DB::rows('select * from ads')]);}
}
