<?php
namespace App\Controllers;
use App\Core\Database as DB; use App\Core\Helpers as H;
class CartController {
 public function show(){H::view('buyer/cart',['items'=>$this->items()]);}
 private function items(){ $out=[]; foreach($_SESSION['cart']??[] as $id=>$c){$p=DB::row('select p.*,d.display_name from products p join designers d on d.id=p.designer_id where p.id=? and p.status="approved"',[$id]); if($p){$p['commercial_selected']=$c['commercial']??false; $p['line_total']=$p['price']+($p['commercial_selected']?$p['commercial_license_price']:0); $out[]=$p;}} return $out;}
 public function add($id){H::requireLogin(); $owned=DB::row('select oi.id from order_items oi join orders o on o.id=oi.order_id where o.user_id=? and oi.product_id=?',[H::user()['id'],$id]); if(!$owned) $_SESSION['cart'][$id]=['commercial'=>isset($_POST['commercial'])]; H::redirect('/cart');}
 public function remove($id){unset($_SESSION['cart'][$id]); H::redirect('/cart');}
 public function license($id){$_SESSION['cart'][$id]['commercial']=isset($_POST['commercial']); H::redirect('/cart');}
 public function checkout(){H::requireLogin(); $items=$this->items(); if($_POST && $items){$total=array_sum(array_column($items,'line_total')); DB::exec('insert into orders (user_id,status,payment_mode,subtotal,total) values (?,?,?, ?,?)',[H::user()['id'],'paid','sandbox',$total,$total]); $order=DB::id(); foreach($items as $p){$comm=round($p['line_total']*.20,2); DB::exec('insert into order_items (order_id,product_id,designer_id,license_type,unit_price,commercial_license_price,total_price,commission_rate) values (?,?,?,?,?,?,?,?)',[$order,$p['id'],$p['designer_id'],$p['commercial_selected']?'commercial':'personal',$p['price'],$p['commercial_selected']?$p['commercial_license_price']:0,$p['line_total'],.20]); DB::exec('insert into seller_earnings (order_id,product_id,designer_id,buyer_id,gross_sale,marketplace_commission,seller_earning,status) values (?,?,?,?,?,?,?,?)',[$order,$p['id'],$p['designer_id'],H::user()['id'],$p['line_total'],$comm,$p['line_total']-$comm,'estimated']); DB::exec('insert into platform_commissions (order_id,product_id,designer_id,gross_sale,commission_amount,referral_commission_placeholder) values (?,?,?,?,?,?)',[$order,$p['id'],$p['designer_id'],$p['line_total'],$comm,0]); DB::exec('update products set sales_count=sales_count+1 where id=?',[$p['id']]); } $_SESSION['cart']=[]; H::redirect('/dashboard/purchases');} H::view('buyer/checkout',['items'=>$items]);}
}
