<?php
namespace App\Controllers;
use App\Core\Database as DB; use App\Core\Helpers as H; use App\Services\CustomDesignService;
final class CustomDesignController {
 public function index():void{$services=DB::rows('select s.*,d.display_name,(select image_path from custom_service_images where custom_service_id=s.id order by sort_order,id limit 1) preview_image from custom_design_services s join designers d on d.id=s.designer_id where s.is_active=1 and d.status="approved" order by s.created_at desc');H::view('public/custom_services',['services'=>$services]);}
 public function detail($slug):void{$service=$this->publicService($slug);$this->detailView($service,[]);}
 public function purchase($slug):void{H::requireLogin();H::verifyCsrf();$s=$this->publicService($slug);try{(new CustomDesignService)->submitRequest($s,(int)H::user()['id'],$_POST,$_FILES);}catch(\InvalidArgumentException $e){$this->detailView($s,[$e->getMessage()]);}catch(\Throwable $e){H::flash('error','Custom-design checkout could not be started.');H::redirect('/custom-design/'.$slug);}}
 private function publicService(string $slug):array{return DB::row('select s.*,d.display_name,d.user_id seller_user_id from custom_design_services s join designers d on d.id=s.designer_id where s.slug=? and s.is_active=1 and d.status="approved"',[$slug])??H::abort(404);}
 private function detailView(array $s,array $errors):void{$balances=H::user()?(new \App\Services\CreditService)->balances((int)H::user()['id']):['available'=>'0.00'];H::view('public/custom_service',['service'=>$s,'questions'=>DB::rows('select * from custom_service_questions where custom_service_id=? order by sort_order,id',[$s['id']]),'images'=>DB::rows('select * from custom_service_images where custom_service_id=? order by sort_order,id',[$s['id']]),'balances'=>$balances,'errors'=>$errors]);}
 public function sellerList():void{H::requireSeller();$d=(new CustomDesignService)->seller((int)H::user()['id']);H::view('seller/custom_services',['services'=>DB::rows('select * from custom_design_services where designer_id=? order by updated_at desc',[$d['id']])]);}
 public function sellerEdit($id='new'):void{H::requireSeller();$api=new CustomDesignService;$d=$api->seller((int)H::user()['id']);$s=$id==='new'?null:(DB::row('select * from custom_design_services where id=? and designer_id=?',[(int)$id,$d['id']])??H::abort(404));$errors=[];if($_SERVER['REQUEST_METHOD']==='POST'){H::verifyCsrf();$errors=$api->saveService((int)H::user()['id'],$s?(int)$s['id']:null,$_POST,$_FILES);if(!$errors){H::flash('success','Custom-design service saved.');H::redirect('/seller/custom-designs');}}H::view('seller/custom_service_form',['service'=>$s,'questions'=>$s?DB::rows('select * from custom_service_questions where custom_service_id=? order by sort_order,id',[$s['id']]):[],'images'=>$s?DB::rows('select * from custom_service_images where custom_service_id=? order by sort_order,id',[$s['id']]):[],'errors'=>$errors]);}
 public function sellerOrders():void{H::requireSeller();$d=(new CustomDesignService)->seller((int)H::user()['id']);H::view('seller/custom_orders',['orders'=>DB::rows('select co.*,o.payment_status,u.name buyer_name,JSON_UNQUOTE(JSON_EXTRACT(co.service_snapshot,"$.title")) title from custom_orders co join orders o on o.id=co.order_id join users u on u.id=co.buyer_user_id where co.designer_id=? and o.payment_status in ("paid","partially_refunded","refunded") order by co.created_at desc',[$d['id']])]);}
 public function buyerOrders():void{H::requireLogin();H::view('buyer/custom_orders',['orders'=>DB::rows('select co.*,o.payment_status,d.display_name,JSON_UNQUOTE(JSON_EXTRACT(co.service_snapshot,"$.title")) title from custom_orders co join orders o on o.id=co.order_id join designers d on d.id=co.designer_id where co.buyer_user_id=? order by co.created_at desc',[H::user()['id']])]);}
 public function buyerOrder($id):void{$this->orderForSide('buyer',(int)$id);}
 public function sellerOrder($id):void{$this->orderForSide('seller',(int)$id);}
 private function orderForSide(string $side,int $id):void{H::requireLogin();$api=new CustomDesignService;$o=$api->order($id,(int)H::user()['id'],$side);if($_SERVER['REQUEST_METHOD']==='POST'){H::verifyCsrf();try{$api->transition($o,(int)H::user()['id'],$_POST['action']??'',$_FILES);H::flash('success','Custom order updated.');H::redirect('/'.$side.'/custom-orders/'.$id);}catch(\Throwable $e){H::flash('error',$e->getMessage());}}$conversation=DB::row('select id from message_conversations where custom_order_id=?',[$id]);H::view($side.'/custom_order',['order'=>$o,'brief'=>json_decode($o['brief_snapshot'],true)?:[],'files'=>DB::rows('select * from custom_order_files where custom_order_id=? order by created_at,id',[$id]),'history'=>DB::rows('select h.*,u.name actor_name from custom_order_status_history h left join users u on u.id=h.actor_user_id where h.custom_order_id=? order by h.created_at desc,h.id desc',[$id]),'conversation'=>$conversation]);}
 public function file($id):void{H::requireLogin();$f=(new CustomDesignService)->file((int)$id,(int)H::user()['id']);$base=realpath(app_path('storage/protected_uploads/custom_designs'));$real=realpath(app_path('storage/protected_uploads/'.ltrim($f['storage_path'],'/')));if(!$base||!$real||!str_starts_with($real,$base.DIRECTORY_SEPARATOR)||!is_file($real)||!is_readable($real))H::abort(404);header('Content-Type: application/octet-stream');header('Content-Length: '.filesize($real));header("Content-Disposition: attachment; filename*=UTF-8''".rawurlencode($f['original_name']));header('X-Content-Type-Options: nosniff');header('Cache-Control: private, no-store');readfile($real);exit;}
 public function adminOrders():void{H::requireRole('admin');H::view('admin/custom_orders',['orders'=>DB::rows('select co.*,o.payment_status,o.total,u.name buyer_name,d.display_name,JSON_UNQUOTE(JSON_EXTRACT(co.service_snapshot,"$.title")) title,(select count(*) from custom_order_files f where f.custom_order_id=co.id and f.file_kind="final") final_count from custom_orders co join orders o on o.id=co.order_id join users u on u.id=co.buyer_user_id join designers d on d.id=co.designer_id order by co.created_at desc')]);}
 public function adminOrder($id):void{H::requireRole('admin');$o=DB::row('select co.*,o.payment_status,o.total,o.manual_review_required,o.manual_review_reason,u.name buyer_name,d.display_name from custom_orders co join orders o on o.id=co.order_id join users u on u.id=co.buyer_user_id join designers d on d.id=co.designer_id where co.id=?',[$id])??H::abort(404);$reports=DB::rows('select r.id,r.status,r.reason,r.created_at from message_reports r join message_conversations c on c.id=r.conversation_id where c.custom_order_id=? order by r.created_at desc',[$id]);H::view('admin/custom_order',['order'=>$o,'brief'=>json_decode($o['brief_snapshot'],true)?:[],'files'=>DB::rows('select id,file_kind,original_name,file_size,created_at from custom_order_files where custom_order_id=?',[$id]),'reports'=>$reports]);}
}
