<?php
namespace App\Controllers;
use App\Core\Database as DB;
use App\Core\Helpers as H;
use App\Services\MessagingService;

final class MessagingController
{
    private MessagingService $service;
    public function __construct(){ $this->service=new MessagingService; }
    private function uid():int{H::requireLogin();return(int)H::user()['id'];}
    private function validSide(string $side):string{if(!in_array($side,['buyer','seller'],true))H::abort(404);if($side==='seller')H::requireSeller();return$side;}
    public function inbox($side):void{$uid=$this->uid();$side=$this->validSide($side);$archived=($_GET['archived']??'')==='1';$rows=$this->service->inbox($uid,$side,$archived);$all=$this->service->inbox($uid,$side,false);H::view('messages/index',['side'=>$side,'conversations'=>$rows,'archived'=>$archived,'totalUnread'=>array_sum(array_column($all,'unread_count'))]);}
    public function thread($side,$id):void{$uid=$this->uid();$side=$this->validSide($side);$c=$this->service->conversation((int)$id,$uid);if($this->service->side($c,$uid)!==$side)H::abort(404);if($_SERVER['REQUEST_METHOD']==='POST'){H::verifyCsrf();try{$this->service->send($c,$uid,$_POST['body']??'',$_FILES['attachments']??[]);H::flash('success','Message sent.');}catch(\InvalidArgumentException $e){H::flash('warning',$e->getMessage());}H::redirect("/$side/messages/".(int)$id);}$this->service->markRead($c,$uid);$messages=$this->service->messages($c);$other=$side==='buyer'?(int)$c['seller_user_id']:(int)$c['buyer_user_id'];H::view('messages/thread',['side'=>$side,'conversation'=>$c,'messages'=>$messages,'attachments'=>$this->service->attachments($messages),'blocked'=>$this->service->blocked($uid,$other),'myBlock'=>(bool)DB::row('select id from message_blocks where blocker_user_id=? and blocked_user_id=? and removed_at is null',[$uid,$other])]);}
    public function startProduct($id):void{H::verifyCsrf();$cid=$this->service->startProduct((int)$id,$this->uid());H::redirect('/buyer/messages/'.$cid);}
    public function startStore($id):void{H::verifyCsrf();$cid=$this->service->startStore((int)$id,$this->uid());H::redirect('/buyer/messages/'.$cid);}
    public function startBuyerOrder($id):void{H::verifyCsrf();$cid=$this->service->startBuyerOrderItem((int)$id,$this->uid());H::redirect('/buyer/messages/'.$cid);}
    public function startSellerOrder($id):void{H::verifyCsrf();H::requireSeller();$cid=$this->service->startSellerOrderItem((int)$id,$this->uid());H::redirect('/seller/messages/'.$cid);}
    public function archive($side,$id):void{H::verifyCsrf();$uid=$this->uid();$side=$this->validSide($side);$c=$this->service->conversation((int)$id,$uid);if($this->service->side($c,$uid)!==$side)H::abort(404);$this->service->archive($c,$uid,($_POST['archive']??'1')==='1');H::redirect("/$side/messages".((($_POST['archive']??'1')==='1')?'':'?archived=1'));}
    public function block($side,$id):void{H::verifyCsrf();$uid=$this->uid();$side=$this->validSide($side);$c=$this->service->conversation((int)$id,$uid);if($this->service->side($c,$uid)!==$side)H::abort(404);$this->service->block($c,$uid,($_POST['block']??'1')==='1');H::redirect("/$side/messages/".$c['id']);}
    public function report($side,$id):void{H::verifyCsrf();$uid=$this->uid();$side=$this->validSide($side);$c=$this->service->conversation((int)$id,$uid);if($this->service->side($c,$uid)!==$side)H::abort(404);try{$this->service->report($c,$uid,$_POST['reason']??'',$_POST['details']??'');H::flash('success','Conversation reported for review.');}catch(\InvalidArgumentException $e){H::flash('warning',$e->getMessage());}H::redirect("/$side/messages/".$c['id']);}
    public function attachment($id):void{$a=$this->service->attachmentForUser((int)$id,$this->uid())??H::abort(404);$this->serve($a);}
    private function serve(array $a):never{$base=realpath(app_path('storage/protected_uploads/messages'));$real=realpath(app_path('storage/protected_uploads/messages/'.$a['stored_name']));if(!$base||!$real||!str_starts_with($real,$base.DIRECTORY_SEPARATOR)||!is_file($real)||!is_readable($real))H::abort(404);header('Content-Type: '.$a['mime_type']);header('Content-Length: '.filesize($real));header("Content-Disposition: inline; filename*=UTF-8''".rawurlencode($a['original_name']));header('X-Content-Type-Options: nosniff');readfile($real);exit;}
    public function adminReports($id=null):void{H::requireRole('admin');$reports=DB::rows('select r.*,d.display_name shop_name,u.name reporter_name from message_reports r join message_conversations c on c.id=r.conversation_id join designers d on d.id=c.designer_id join users u on u.id=r.reporter_user_id order by field(r.status,"open","reviewing","resolved","dismissed"),r.created_at desc');$detail=null;$messages=[];$attachments=[];if($id){$detail=DB::row('select r.id report_id,r.conversation_id,r.reporter_user_id,r.reason,r.details,r.status,r.moderator_user_id,r.moderator_notes,r.created_at report_created_at,r.reviewed_at,c.buyer_user_id,c.seller_user_id,c.designer_id,c.product_id,c.order_id,c.order_item_id,c.context_label,c.context_key,c.buyer_archived_at,c.seller_archived_at,c.buyer_last_read_message_id,c.seller_last_read_message_id,c.last_message_at,c.created_at conversation_created_at,c.updated_at,d.display_name shop_name,u.name buyer_name from message_reports r join message_conversations c on c.id=r.conversation_id join designers d on d.id=c.designer_id join users u on u.id=c.buyer_user_id where r.id=?',[(int)$id])??H::abort(404);$conversation=$detail;$conversation['id']=$detail['conversation_id'];$messages=$this->service->messages($conversation);$attachments=$this->service->attachments($messages);}H::view('admin/message_reports',compact('reports','detail','messages','attachments'));}
    public function moderate($id):void{H::requireRole('admin');H::verifyCsrf();$status=$_POST['status']??'';if(!in_array($status,['open','reviewing','resolved','dismissed'],true))H::abort(422);$notes=mb_substr(trim($_POST['notes']??''),0,1000);if($status==='open')DB::exec('update message_reports set status="open",moderator_user_id=null,moderator_notes=null,reviewed_at=null where id=?',[(int)$id]);else DB::exec('update message_reports set status=?,moderator_user_id=?,moderator_notes=?,reviewed_at=now() where id=?',[$status,H::user()['id'],$notes,(int)$id]);H::redirect('/admin/message-reports/'.(int)$id);}
    public function adminAttachment($reportId,$id):void{H::requireRole('admin');$a=$this->service->attachmentForReportedConversation((int)$reportId,(int)$id)??H::abort(404);$this->serve($a);}
}
