<?php
namespace App\Controllers;
use App\Core\Database as DB; use App\Core\Helpers as H;
class PublicController {
 public function home(){ H::view('public/home',['cats'=>DB::rows('select * from categories where is_active=1 order by sort_order,name limit 8'),'products'=>DB::rows("select p.*,d.display_name,d.store_slug from products p join designers d on d.id=p.designer_id where p.status='approved' and p.is_featured=1 order by p.updated_at desc limit 8"),'designers'=>DB::rows('select * from designers where status="approved" and is_featured=1 limit 6')]); }
 public function browse(){ $w=["p.status='approved'"]; $q=[]; if($_GET['q']??''){$w[]='(p.title like ? or p.description like ?)';$q[]='%'.$_GET['q'].'%';$q[]='%'.$_GET['q'].'%';} if($_GET['category']??''){$w[]='c.slug=?';$q[]=$_GET['category'];} if($_GET['file_type']??''){$w[]='p.file_types like ?';$q[]='%'.$_GET['file_type'].'%';} if($_GET['ai']??''){$w[]='p.ai_disclosure=?';$q[]=$_GET['ai'];} if(isset($_GET['pod'])&&$_GET['pod']!==''){$w[]='p.pod_allowed=?';$q[]=(int)$_GET['pod'];} $sort=['popular'=>'p.sales_count desc','price_asc'=>'p.price asc','price_desc'=>'p.price desc']; $order=$sort[$_GET['sort']??'']??'p.created_at desc'; H::view('public/browse',['products'=>DB::rows('select p.*,d.display_name,d.store_slug,c.name category_name from products p join designers d on d.id=p.designer_id left join categories c on c.id=p.category_id where '.implode(' and ',$w).' order by '.$order,$q),'cats'=>DB::rows('select * from categories where is_active=1')]); }
 public function category($slug){ $cat=DB::row('select * from categories where slug=?',[$slug])??H::abort(404); $_GET['category']=$slug; $this->browse(); }
 public function product($slug){ $p=DB::row('select p.*,d.display_name,d.store_slug,c.name category_name from products p join designers d on d.id=p.designer_id left join categories c on c.id=p.category_id where p.slug=? and p.status="approved"',[$slug])??H::abort(404); H::view('public/product',['p'=>$p,'images'=>DB::rows('select * from product_images where product_id=?',[$p['id']]),'tags'=>DB::rows('select t.* from tags t join product_tags pt on pt.tag_id=t.id where pt.product_id=?',[$p['id']])]); }
 public function store($slug){ $d=DB::row('select * from designers where store_slug=? and status="approved"',[$slug])??H::abort(404); H::view('public/store',['d'=>$d,'products'=>DB::rows('select * from products where designer_id=? and status="approved"',[$d['id']]),'followers'=>DB::row('select count(*) c from follows where designer_id=?',[$d['id']])['c']??0]); }
 public function static(){ $page=trim(parse_url($_SERVER['REQUEST_URI'],PHP_URL_PATH),'/'); H::view('static/page',['title'=>ucwords(str_replace('-',' ',$page))]); }
}
