<?php
namespace App\Controllers;
use App\Core\Database as DB; use App\Core\Helpers as H;
class SellerController { private function d(){return DB::row('select * from designers where user_id=?',[H::user()['id']]);}
 public function apply(){H::requireLogin(); if($_POST){DB::exec('insert into designer_applications (user_id,display_name,desired_slug,bio,portfolio_url,social_links,design_types,uses_ai,agreement,status) values (?,?,?,?,?,?,?,?,?,"pending")',[H::user()['id'],$_POST['display_name'],H::slug($_POST['desired_slug']),$_POST['bio'],$_POST['portfolio_url'],$_POST['social_links'],$_POST['design_types'],$_POST['uses_ai']??'no',isset($_POST['agreement'])]); H::redirect('/dashboard');} H::view('seller/apply');}
 public function home(){H::requireSeller(); $d=$this->d(); H::view('seller/home',['d'=>$d,'stats'=>DB::row('select count(*) total, sum(status="approved") approved, sum(status="pending_review") pending from products where designer_id=?',[$d['id']??0])]);}
 public function storeSettings(){H::requireSeller(); $d=$this->d(); if($_POST){DB::exec('update designers set display_name=?,store_slug=?,bio=?,social_links=?,announcement=?,updated_at=now() where id=?',[$_POST['display_name'],H::slug($_POST['store_slug']),$_POST['bio'],$_POST['social_links'],$_POST['announcement'],$d['id']]);} H::view('seller/store',['d'=>$this->d()]);}
 public function products(){H::requireSeller(); $d=$this->d(); H::view('seller/products',['products'=>DB::rows('select * from products where designer_id=? order by updated_at desc',[$d['id']])]);}
 public function editProduct($id=null){H::requireSeller(); $d=$this->d(); $p=$id?DB::row('select * from products where id=? and designer_id=?',[$id,$d['id']]):null; if($_POST){$status=$_POST['action']==='review'?'pending_review':'draft'; $fileTypes=implode(',',$_POST['file_types']??[]); if($p){DB::exec('update products set title=?,slug=?,description=?,price=?,category_id=?,tags_text=?,file_types=?,commercial_license_enabled=?,commercial_license_price=?,pod_allowed=?,ai_disclosure=?,status=?,updated_at=now() where id=?',[$_POST['title'],H::slug($_POST['slug']),$_POST['description'],$_POST['price'],$_POST['category_id']?:null,$_POST['tags'],$fileTypes,isset($_POST['commercial_license_enabled']),$_POST['commercial_license_price'],isset($_POST['pod_allowed']),$_POST['ai_disclosure'],$status,$p['id']]);}else{DB::exec('insert into products (designer_id,category_id,title,slug,description,price,tags_text,file_types,commercial_license_enabled,commercial_license_price,pod_allowed,digital_resale_prohibited,ai_disclosure,status) values (?,?,?,?,?,?,?,?,?,?,?,?,?,?)',[$d['id'],$_POST['category_id']?:null,$_POST['title'],H::slug($_POST['slug']),$_POST['description'],$_POST['price'],$_POST['tags'],$fileTypes,isset($_POST['commercial_license_enabled']),$_POST['commercial_license_price'],isset($_POST['pod_allowed']),1,$_POST['ai_disclosure'],$status]); $id=DB::id();} if(!empty($_FILES['download']['tmp_name'])){$name=uniqid().'-'.basename($_FILES['download']['name']); move_uploaded_file($_FILES['download']['tmp_name'],app_path('storage/protected_uploads/'.$name)); DB::exec('insert into product_files (product_id,storage_path,original_name,file_size,mime_type) values (?,?,?,?,?)',[$id,$name,$_FILES['download']['name'],$_FILES['download']['size'],$_FILES['download']['type']]);} H::redirect('/seller/products');} H::view('seller/edit_product',['p'=>$p,'cats'=>DB::rows('select * from categories where is_active=1')]);}
 public function disableProduct($id){H::requireSeller(); DB::exec('update products set status="disabled" where id=? and designer_id=?',[$id,$this->d()['id']]); H::redirect('/seller/products');}
 public function sales(){H::requireSeller(); H::view('seller/sales',['sales'=>DB::rows('select se.*,p.title,u.email from seller_earnings se join products p on p.id=se.product_id join users u on u.id=se.buyer_id where se.designer_id=?',[$this->d()['id']])]);}
 public function referrals(){H::requireSeller(); H::view('seller/referrals',['refs'=>DB::rows('select * from referrals where referrer_user_id=?',[H::user()['id']])]);}
 public function rank(){H::requireSeller(); H::view('seller/rank',['d'=>$this->d()]);}
}
