<section class="hero card" style="text-align:center;">
    <h1>Sell digital designs on Asset Moth.</h1>
    <p>Apply for a reviewed designer storefront where you can present your brand, upload digital products, set license options, and submit products for marketplace review.</p>
    <p><a class="btn" href="/apply">Apply to Sell</a> <a class="btn alt" href="/seller-faq">Read Seller FAQ</a></p>
</section>
<section class="card"><h2>What approved designers can do</h2><div class="grid"><div><h3>Build a public storefront</h3><p>Add a display name, slug, bio, images, announcement, and SEO title/description.</p></div><div><h3>Publish reviewed products</h3><p>Create product listings with descriptions, previews, protected download files, tags, category, and SEO fields.</p></div><div><h3>Clarify current product settings</h3><p>Use current fields for personal use, commercial license availability, POD permission, resale restrictions, and AI disclosure.</p></div></div></section>
<section class="card"><h2>What can you sell?</h2><p>Asset Moth is built for downloadable design assets and creative files. Product submissions are reviewed before publication, and each listing should clearly describe what buyers receive.</p><div class="grid"><div><h3>Design files</h3><ul><li>SVG files</li><li>PNG files</li><li>Sublimation designs</li><li>Seamless patterns</li><li>Digital papers</li><li>Clipart</li></ul></div><div><h3>Templates and graphics</h3><ul><li>Canva templates</li><li>Business templates</li><li>Printables</li><li>Mockups</li><li>Website graphics</li><li>Alphas</li></ul></div><div><h3>Specialty creative files</h3><ul><li>Fonts</li><li>Laser files</li><li>Embroidery files</li><li>DTF files</li><li>Tumbler wraps</li><li>Procreate brushes and stamps</li></ul></div></div></section>
<section class="card"><h2>Marketplace standards</h2><ul><li>Applications and product submissions are manually reviewed.</li><li>Only upload original work or files you have rights to sell.</li><li>AI-assisted or AI-generated content must be disclosed in product fields.</li><li>Products should use accurate previews, descriptions, categories, tags, and license settings.</li></ul></section>
<section class="card"><h2>How applying works</h2><ol><li>Create or log in to a buyer account.</li><li>Submit a designer application with your public name, desired store slug, bio, portfolio, design types, and AI-use disclosure.</li><li>An admin reviews the application. Approval is not guaranteed and may depend on marketplace fit, originality, and completeness.</li><li>If approved, you can access the seller dashboard, set up your storefront, and submit products for review.</li></ol></section>
<section class="card"><h2>Helpful resources</h2><p><a href="/licensing-help">Licensing Help</a> explains personal, commercial, POD, and resale rules. <a href="/terms">Terms</a> describe marketplace responsibilities. <a href="/contact">Contact</a> lists support guidance.</p></section>
<section class="card" style="text-align:center;"><h2>Ready to apply?</h2><p>Tell us about your design work and the types of digital files you want to sell.</p><a class="btn" href="/apply">Start Designer Application</a></section>
